### ISSUE TITLE
Update "What makes a good research presentation"

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#1007]
The [current one](https://github.com/foundersandcoders/master-reference/blob/change/week1/coursebook/week-1/presentation-guidance.md) doesn't really address the issue. It also doesn't recommend ***including code snippets***, which for most topics, are essential to a good presentation.

It could also usefully include: https://github.com/FAC-Sixteen/research/blob/master/README.md

It might also be useful to include links to a couple of well-received examples, e.g. https://github.com/FAC-Sixteen/research/blob/master/week2/Asynchronous%20JS.md

@charlielafosse any others you can think of?

**Comment by sofer** [comment]
Also, possibly move it out of coursebook/week-1 and into coursebook/general

**Comment by sofer** [comment]
And combine how to do good research with how to do a good presentation

**Comment by charlielafosse** [comment]
Will dig through recent presentations and try find some gooduns

**Comment by charlielafosse** [comment]
todo
 1. How to carry out good research
2. What makes a good _research_ presentation
3. Previous examples
