### ISSUE TITLE
Conflicting image carousel instructions

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/master-reference#1045]
The image carousel prereq on the website links to a [markdown file in this repo](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/prerequisites/image-carousel.md). However they have conflicting instructions.

The website says:
>the image carousel must be built into your website, a link to a separate page or CodePen will not be accepted

whereas the linked file says:
> We suggest you build this in CodePen or a similar tool of your choice

We should probably either update the file in this repo or remove it entirely and just put the information on the website.

**Comment by josephgattuso** [comment]
Hi @oliverjam, I would gladly take this issue!  Let me know if I can assist.  Please note this would be my #firstcommit (not considering my own repos) and support/guidance is warmly welcomed - check out pull request #1046. In retrospect, I likely did this in the wrong order and this is duly noted 🤓

**Comment by josephgattuso** [comment]
Full disclosure: not technically my #firstcommit. I do happen to be a [recently published](https://do-community.github.io/cloud_haiku/haikus/objective-cloud) poet.
😂
