### ISSUE TITLE
New curriculum

### ISSUE THREAD

**Issue by teenie-quaggard** [foundersandcoders/master-reference#1048]
@oliverjam and @astroash are working on a revamp of the London Master Reference. 

@astroash has been turning these overall learning outcomes into more specific learning objectives. [These can be found here.](https://foundersandcoders.gitbook.io/master_reference/) The idea is that each objective should be something that is concrete enough for someone to see and provide feedback on during code review.

We would like FAC17 to look over this initial outline and to answer the following questions in a comment below:

1. Do you have any suggestion for additional overall learning outcomes? Have we missed anything?
2. Do you have any project ideas for each week?
3. What's your week?
4. Please come up with a list of learning objectives (like Ash has done in [week one of the Gitbook](https://foundersandcoders.gitbook.io/master_reference/)) which are applicable to the outcomes of your given week. Don't worry, they don't need to be exhaustive, this is meant to be an initial brainstorm.

This is a brief outline of the contents of each week, so far:

### Concept
- Static website

### Project
???

### Learning outcomes
- semantic HTML
- accessibility
- performance
- git/git workflow

### Tool focus
- debug CSS

### JS focus
- DOM manipulation

### CSS focus
- responsiveness (mobile/desktop)
- transitions
- Flexbox (navbar)

### Testing focus
- manual QA

### Concept
- HTTP

### Project
???

### Learning outcomes
- req/res
- fetch

### Tool focus
- debugging js
- (chrome) network tab
- postman

### JS focus
- array methods

### CSS focus
- grid (render a grid of data)

### Testing focus
- make DOM tests pass

### Concept
- Build systems

### Project
???

### Learning outcomes
- npm
- automated testing
- searchable api / form
- error handling

### Tool focus
- linting
- prettier

### JS focus
- object manipulation
- client side validation

### CSS focus
- client side validation

### Testing focus
- automated unit tests

### Concept
- Node

### Project
- Vanilla HTML form

### Learning outcomes
- vanilla server
- buffers/streams
- core node modules
- CommonJS modules system
- forms/posting/redirecting

### Tool focus
- debugging server
- nodemon

### JS focus
- error first callbacks

### CSS focus
- forms with more than just a text input

### Testing focus
- server testing -> response
- TDD with Supertest

### Concept
- Databases

### Project
???

### Learning outcomes
- schema design
- SQL
- DB setup / management

### Tool focus
- PSQL
- environments

### JS focus
- abstraction

### CSS focus
???

### Testing focus
- DB Testing

### Concept
- Authentication

### Project
???

### Learning outcomes
- Hashing / salting
- JWT
- sessions / cookies
- Bcrypt
- SSL
- Stateless vs. stateful sessions

### Tool focus
- applications tab (chrome)
- CI (Github actions vs. Travis)

### JS focus
- Create your own promises

### CSS focus
- Logging in UX

### Testing focus
???

### Concept
- Express

### Project
- User profiles??

### Learning outcomes
- Templating
- Design patterns (MVC)
- Rest APIs
- Middleware (as a concept)

### Tool focus
- More advanced Postman

### JS focus
- Template literals

### CSS focus
- Potentially a CSS preprocessor

### Testing focus
- Mocking

### Concept
- Full-stack app

### Project
???

### Learning outcomes
- Full stack error handling
- Handlers
- Build steps

### JS focus
- Throwing and catching errors

### Testing focus

**Comment by georgiamshaw** [comment]
Week 1 - Jan, Leonie, Sam
Week 2 - Emmanuel, Franchy
Week 3 - Georgia, Tony
Week 4 - Christine, Victor
Week 5 - Colette, Andy
Week 6 - Gigi, Gregor
Week 7 - Jack, Martha
Week 8 - Reuben, Sarah

**Comment by teenie-quaggard** [comment]
As we will be postponing any big changes to the curriculum until FAC19, I will close this issue.
