### ISSUE TITLE
Week8 - replace introduction to express with slides

### ISSUE THREAD

**Issue by reubengt** [foundersandcoders/master-reference#1057]
As referenced in @jameslevine 's mentor feedback here:
https://github.com/foundersandcoders/master-reference/issues/997#issue-446184005

fac16 and fac17 found the [introduction to express](https://github.com/foundersandcoders/introduction-to-express) on day 1 of express week quite long and wordy, and it took longer than expected because mentors were waiting on everyone to read through.

an alternative would be to deliver this information as a presentation, thus giving more control over time to the mentors, and opening the room for discussion.

With @bobbysebolao 's approval, I made some slides and did a test run for fac18.
I can send out a poll for how they found the presentation.

I made it with fac's slide kit, so I can make a pull request on the slide kit repo for these,
but [here is a hackmd version](https://hackmd.io/treNCrYPTva8WyJXq-JZcg?edit)

what is the consensus on replacing the introduction to express with slides?

**Comment by oliverjam** [comment]
This is a great intro, especially the overview of frameworks/abstraction 🎉 

Given we're changing the curriculum quite a bit I imagine the current intro will be replaced anyway.

I'm not sure that we want to rely on always having a mentor who is willing and able to deliver material as a presentation, but the content could definitely work as material in the new curriculum.

**Comment by bobbysebolao** [comment]
I also love the code snippets you've used to illustrate the difference between Node with and without Express 🚀 

Quite a few people from FAC17/16 liked the idea of there being a short presentation to set the stage for each week, delivered by mentors. Presentations already exist for certain weeks (weeks 6 and 7 definitely have them). If there are sufficient speakers notes, I think it's fair to ask mentors to deliver these intros.

**Comment by reubengt** [comment]
I'm willing to work on speaker notes a little bit, or convert this to a writeup if necessary.
@oliverjam what's the current status of week8 on the new curriculum?

**Comment by oliverjam** [comment]
Express is going to be introduced in Week 7 rather than 8. The main change is we're planning on focusing on building a RESTful JSON API, but that should affect the general introduction.

You can see the proposed learning outcomes for the week here if you like:

https://github.com/foundersandcoders/coursebook/pull/5/files

**Comment by reubengt** [comment]
should this issue be closed then? since it's presently unclear how these proposed changes will fit into the new curriculum?

**Comment by oliverjam** [comment]
Maybe a more generic issue about opening each week with a short presentation introducing the main topic would be useful? On the new [coursebook repo](https://github.com/foundersandcoders/coursebook)

**Comment by bobbysebolao** [comment]
Created [an issue](https://github.com/foundersandcoders/coursebook/issues/15) in the new coursebook that relates to this thread
