### ISSUE TITLE
Gitter channels

### ISSUE THREAD

**Issue by Jbarget** [foundersandcoders/master-reference#11]
We have **a lot** of gitter channels under the foundersandcoders organisation, id like to propose having a single place (in the README or as the Wiki) listing all the live channels and a short description about them. A glossary.

**Comment by des-des** [comment]
I agree, @Jbarget what do you think of an md file inside this repo?

**Comment by Jbarget** [comment]
Sounds good!

**Comment by eliascodes** [comment]
@des-des @Jbarget did you see that [this](https://github.com/foundersandcoders/wiki/wiki/Gitter-Room-Index) is a thing? We've solved the problem of too many gitter channels with too many indexes of gitter channels 😆

**Comment by Jbarget** [comment]
bloody inception!

**Comment by iteles** [comment]
@eliascodes @jbarget But having said that, the wiki repo doesn't have a stated purpose so I'm not sure it'll be used, whereas there's a greater chance people will see it here :blush:

**Comment by bradreeder** [comment]
Closed #19 .
