### ISSUE TITLE
"annoying" security reasons is a bit loaded.

### ISSUE THREAD

**Issue by mantagen** [foundersandcoders/master-reference#145]
Does anyone feel strongly that it should remain in this?
https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-1/project.md#build-a-one-page-portfolio-website-for-you-and-your-team
@bradreeder

**Comment by bradreeder** [comment]
I don't have a strong preference. @njsfield @jsms90 @Cleop ?

**Comment by njsfield** [comment]
The original statement was a lot longer, it was something like 'As a user using an old tiny computer with javascript enabled for annoying security reasons that uses IE7', intended to imply (in a lighthearted manner) what a user might say if they were a bit frustrated about the limitations of the technology used in their working environment. 

The IE7 part was taken out, so now the undertone of the statement is less clear and yeah, comes across quite loaded. I think subjective 'annoying' word can be removed. @all thoughts?

**Comment by jsms90** [comment]
@mantagen Good point. I read it in the way that @njsfield intend it. But it seems like it's very easy for it to sound derogatory towards IE7 users? Rather than light-hearted and jokey, which was definitely the intent

**Comment by des-des** [comment]
@mantagen Merged!

**Comment by mantagen** [comment]
:+1:
