### ISSUE TITLE
Visualisations

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/master-reference#15]
I think we want to get this back into the course. Leaflet d3 chart.js

**Comment by Jbarget** [comment]
The curriculum topics seem to be set and looking good. Was there any discussion about visualisations being introduced as stretch goals within projects?
@des-des @bradreeder

**Comment by bradreeder** [comment]
@Jbarget There hasn't been so far. If you can think of a way that visualisations would tie into practicing CSS, then @njsfield 's suggestion here might be interesting #25 .

**Comment by des-des** [comment]
@shiryz :taco:
