### ISSUE TITLE
When is first day of curriculum planning? (Is Good Friday a day off?)

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#153]
Should be decided asap and communicated to FAC10

![image](https://cloud.githubusercontent.com/assets/15656538/23212069/edc42a18-f8fc-11e6-8911-8db2c4d23ffd.png)

**Comment by bradreeder** [comment]
Main reasoning for why I'd suggest doing the first day at the end of the first part of the course:

* The curriculum is fresh on the student's minds. If we do the first day too long after the first 8-weeks I wonder if the quality of feedback would decrease.
* If mentors are assigned at the end of this day it gives them good notice, including over the reading break, to consider the week they're assigned to.

If people object to us setting a precedent of coming in on bank holidays, I think the first curriculum-planning day should be the first day after coming back from the break.

**Comment by jsms90** [comment]
This issue needs to be resolved asap for FAC10. @bradreeder and I have spoken about this a lot. Good Friday isn't your average bank holiday and it has already been communicated to at least one person in FAC10 that this will be a day off.

I'm going to close this issue as decided - Good Friday is a day off.

I'm going to open a new issue about **when** this curriculum planning day should be for all future cohorts
