### ISSUE TITLE
general folder need project-planning.md

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#154]
After a conversation with @iteles @njsfield , we feel like there is need for a checklist to explain what we expect to see from students.

e.g.
+ start with readme & github in general (commit history), move on to UX - demo website, move on to code
+ what do we want to see from code

Structure:
15 mins presentation (strict timing! everything takes as long as you let it take)
5 mins critique from alumni / questions from students

**Comment by bradreeder** [comment]
Sounds good. If you find the time by all means go ahead.
