### ISSUE TITLE
Add project presentation structure to weekly-project.md

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#156]
Previous FACs (or at least FAC9) have struggled to know exactly what was expected from their presentations, or what constitutes a "good" presentation. Especially when it comes to the code itself.

**Comment by bradreeder** [comment]
Just writing up what @jsms90 put on the whiteboard for FAC10 in case it gets lost:

## Project presentation structure

Show your readme: why/ what/ how
* How did you split up the work
* How did you pair

Show your use of github
* show commit history
* show PR history

Walkthrough UX
* demo your website
* how well does it conform to your brief. i.e. user-stories.

Walkthrough code
* file structure
* prioritise things you learned that were new to you, which the rest of your cohort could benefit from hearing about.
* something cool
* something that was hard
