### ISSUE TITLE
First curriculum planning day - last Friday of week 8

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#159]
As per the discuss in #153 (specific to FAC10), we need to decide which day on the course will be the first curriculum planning day - when the cohort assigns themselves to particular weeks (& discusses the overall structure of the course??)

Week 8 has already been planned as a 4 day week, and @bradreeder has suggested that the last day of weeks 1-8 be the first curriculum planning day.

Thoughts? (I have assigned the week 8 mentors as well, to see how they feel)

**Comment by bradreeder** [comment]
See my comment in #153

**Comment by nelsonic** [comment]
please excuse my _ignorance_ but what is there (_left_) to _plan_...?

**Comment by bradreeder** [comment]
I think @jsms90 is referring to the first curriculum-planning day for FAC11 @nelsonic

**Comment by nelsonic** [comment]
@bradreeder yes, I _understood_ the description of the issue 
but I thought the _idea_ of having a "Master Reference" (_i.e. curriculum_) 
meant that we _won't **need**_ to do _more_ planning...? 

Aren't the F&C10 Cohort going to _edit_ the reference _as-they-go_...?
(_i.e. create an issue if you have a question/idea, discuss it with your peers on GitHub 
and once there's a conclusion, PR an update to the respective section of the repo..._)
What am I _missing_...?

Having grown up with teachers, I've never _understood_ why there is _so much_ (_repetitive_) planning ... I mean how much has _really_ changed about how we build web Apps in the past year? 
can't we just ***lead by example*** by writing good readmes/tutorials 
and/or iterate/expand the knowledge base such that we can _all_ learn _useful/interesting_ things _remotely_ ***without*** regardless of our ability to take a "_4 month career break_"...?

**Comment by bradreeder** [comment]
@nelsonic I think curriculum-planning over time will develop more along the lines of what we've spoken about. I.e. it being largely the case of mentors iterating the existing curriculum. I hope `curriculum-planning` can more and more become a form of `sprint-review` & `sprint-planning`. 

Even in the most agile version of the curriculum we'd still need to:

* Collect feedback from the cohort (so we can maximise validated learning) & assign mentors to weeks.
* Iteratively improve existing resources.
* Identify resources that we need and start creating them.
* Update the coursebook and relevant curriculum docs.

This should become less and less time consuming as we go as our processes become leaner. But there's still a lot to do, and my experience with FAC so far is that if we don't set people time aside to do this it likely won't happen.

**Comment by jsms90** [comment]
@nelsonic What if, in the future, we ever need to make more drastic changes to the curriculum. Like introducing functional programming early on? Each iteration should build on the last. But we don't want to get stuck in our ways, and assume the changes will only ever be minute, just because we have solid docs now.

I think that having a day, where you assess the overarching 8 weeks is a good idea. Mostly, it's a chance to reflect on the experience as a whole, and not plan your weeks in isolation from each other. That's when students choose which week they want to take on. I wouldn't expect huge changes every time, but it's good not to assume that students only ever need to make minor tweaks.

As for
> what is there (left) to plan...?

Looooads! Hahaha. The first time we ever get documentation down is definitely not going to be the final draft. Rigorous documentation, and passing on info between mentors, between weeks and between cohort's, will help us to notice patterns. Only once we see those, can we make the most meaningful of changes.

**Comment by jsms90** [comment]
This "day" is no longer happening at all.

All curriculum planning is happening during week 17
