### ISSUE TITLE
Mentorship scheme for current students

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#170]
We did this for FAC9 and my impression (?) is that it didn't develop much. The issue is being closed in `london-programme` but it might be worth [referencing](https://github.com/foundersandcoders/london-programme/issues/87#event-914266313) it here in case we decide to do this again another time.

@eliascodes @des-des @sohilpandya @harrygfox @JMurphyWeb @ivanmauricio @Jbarget @otajor  @nogainbar @minaorangina @heron2014 @heatherlauren @eleanorreem @msmichellegar @sofiapoh

Do you have any feedback on how this went for FAC9, whether you think it could be worthwhile to try again, what changes you would suggest if we did it again?

**Comment by minaorangina** [comment]
@bradreeder I think it was definitely a positive thing, but it needs to be built upon and managed. Something like scheduled catch up weeks that mentors are suggested to make use of could go a long way. Or a semi-official meet your mentor session of some sort in the beginning?

**Comment by des-des** [comment]
@bradreeder I am still broadly in favour of this idea, although I will admit I managed this badly when I tried to do it in London.

**Comment by eliascodes** [comment]
I think if we want this we should be clearer on what role we expect mentors to fulfill, and set some more concrete expectations. We can then think about whether these relationships need any kind of process attached to them (like @minaorangina suggests) or whether they can remain loose and informal.

For my part, I was never really sure what I was meant to be offering my mentee, other than a point of contact. Mainly I ended up giving advice about what to do post-course and doing a code review and CV review as well, which I was happy to do.

**Comment by bradreeder** [comment]
@jsms90 @Cleop @lucymonie @skibinska @denesnori @emilyb7 @shiryz @marisid 
@Jwhiles @RhodesPeter @SavageWilliam @stevehopkinson @tbtommyb @esraajb @njsfield @msachi

**Comment by msachi** [comment]
I agree with @eliascodes - I was never sure what I could or should have expected from my mentor. If there was more structure to it then it could be more useful. That said, personally I'm not sure there's a great need for it in a place like F&C - we're such a small and well connected community, and I've always felt comfortable asking for help whoever was around or whoever I though might know more. I see everyone as my mentors (and as students) ;)

**Comment by sohilpandya** [comment]
My experience was an interesting one. Met @stevehopkinson once during week one, then around week six, actually became more in contact once the course finished and he started to look for jobs. But he'll be able to tell you if I was helpful in any way. 😊

**Comment by lucymonie** [comment]
I also think mentors should be at least FAC[n-2]. I don't think it really works to have the people who have just finished being mentors, partly because they have enough to do with teaching and preparing workshops etc, but also because many haven't gone through the process of getting a developer job yet, and that could be really helpful.

**Comment by shiryz** [comment]
I think having a mentor is great way for fac to have an idea on how students are doing, having people in the space all the time is amazing for questions on technical things but some individuals would prefer a one on one sit down.
Other than having a point of contact for the mentee, I see the mentor as someone who offers "emotional support", even if it's just by having a chat.
For me talking about what's stressing me out helps me identify the problem and how to solve it.
For this to be productive, it does need more structure, as a beginning maybe add dates (which weeks and when in the week), fom of communicaion (one on one, gitter, phone...), and key points the mentors should ask about...  
I can also help with setting up the structure :smile: .

**Comment by tbtommyb** [comment]
@eliascodes was my mentor and I thought did a good job. I agree it was a bit unclear what we were all supposed to be doing but I just viewed it as having a person willing to help me if I needed it.

Really I think F&C's role in this should be to just put willing people in touch and leave them to it. People will have different ideas about what they want out of it and will need help in different ways. I do understand the desire to make more of a structure but it should be entirely optional and presented in a 'if this works for the pair of you' way.

I agree with @lucymonie that mentors should preferably not be from the previous F&C or two.

**Comment by msmichellegar** [comment]
Like the idea of having mentors from a few FACs prior. Could be a cool way to keep alumni engaged in the community, and give current students an insight into the journey from going through the course to working as a developer. As well as having someone to chat to about the course/whatever else anyone wants from a mentor. Agree that there doesn't need to be too much structure.

**Comment by emilyb7** [comment]
To follow on from @msmichellegar's comments...

Michelle and I certainly didn't follow a particular structure. Maybe more guidance could be useful to those who feel like they got little out of the mentor-mentee relationship.

But for me this was a great opportunity to make contacts within the wider FAC community that I wouldn't have made otherwise. Michelle has given me lots of insight into FAC history and into life after FAC too :) And having a mentor led to exciting things like having private node tuition in Lisbon, which def doesn't fit into the usual structure, but I'm certain it wouldn't have happened if this mentorship thing hadn't existed!

**Comment by shiryz** [comment]
To clarify, by structure I do mean guidelines which the mentor may or may not choose to follow. From my previous experience as a mentor (not in FAC), it was useful to have guidelines and checkpoints so I wouldn't forget crucial points I needed to ask about, these were extremely helpful with my first mentee.

**Comment by msmichellegar** [comment]
Haha loving the mentor/mentee bonding in this issue. @emilyb7 👯

**Comment by msmichellegar** [comment]
Totally agree with what @emilyb7 said. I think having mentors who are a bit more removed from FAC can be a really good thing. People currently teaching the cohort will already be known to the students, and will probably already be sharing their experiences. But having access to a wider network is really beneficial, especially for career development. It's a different perspective. And I think a lot of alumni would jump at the chance to have a tangible opportunity to contribute to the FAC community.

**Comment by marisid** [comment]
I just wanna say that my mentor was @minaorangina and she did a great job :+1: She gave me a very useful insight to the life after F&C, her own career path and some info about the job hunting process. It was really good to know that there is someone I can turn to for feedback on a personal project, for general questions and support anytime during the course. 

I believe the mentor role is vital in the F&C course and I agree with everything @shiryz said about having a structure and that some people prefer the one-to-one interaction to discuss their progress. Also, great points by @lucymonie and @msmichellegar about having at least F&C[n-2] mentors with some experience outside F&C to offer thoughtful guidance.

**Comment by jsms90** [comment]
The feedback from the FAC9 buddy system indicated that more concrete expectations should be set for mentors.

During week 3 of the next programme, something similar was brought in again for FAC10 #209. A pastoral care team formed and [buddies were assigned](https://github.com/foundersandcoders/london-curriculum/blob/master/student-support-team.md).

Alumni were expected to go on 3 "walks" with the students assigned to them. These walks are intended as regular check ins and [advice](https://github.com/foundersandcoders/london-programme/issues/209#issuecomment-285085697) was given by @sofer and @iteles about the kinds of questions that might be helpful to ask.

This issue was therefore resolved. So I'm closing this now.

But an issue may get raised about changing the current process for future cohorts.

**Comment by harrygfox** [comment]
@jsms90 all of that stuff should be documented outside the issues somewhere - if you want Mentors to look at it in the future. Also, there's baaaaaaaaaaaare good stuff above that should be documented too. Like in a mentoring readme - not in this issue which will be buried and forgotten!
- mentors being FAC[n-2] @lucymonie 
- guidelines for mentors @shiryz 

This system of open issues close issues open more issues jeeeeeeezuz. 😭 🔫

**Comment by shiryz** [comment]
@harrygfox , the guidelines are outlined in this issue, though I agree this should be documented in .md, it wasn't easy to trace.

**Comment by shiryz** [comment]
@harrygfox the guidelines are outlined [here](https://github.com/foundersandcoders/london-programme/issues/209) , though I agree this needs to be documented in .md, it wasn't easy to trace.

**Comment by jsms90** [comment]
I _completely_ agree! It should be properly documented!! It is just right at the end of my to do list, behind a lot of more imminent things like curriculum planning.

I have been trying hard to make sure it's at least in an issue, so I can find it later. But reintroducing this mentor/buddy system for FAC10 almost didn't happen at all. It was a mad scramble on my part just to gather everyone together at all.

The reason that I have closed this issue without bothering to document it first, is that I don't think I will find the time to write up a doc. When I do find the time, I'm going to be raising a new issue about how the process should change. So leaving this one open seems pointless.

> This system of open issues close issues open more issues jeeeeeeezuz.

That's what you do :stuck_out_tongue_winking_eye: Open a small granular thing, fix it (in this case, I consider getting the group together enough of a fix, even without documentation beyond [this]()https://github.com/foundersandcoders/london-curriculum/blob/master/student-support-team.md) & close.

This one shouldn't have stayed open for so many months in the first place :upside_down_face:

**Comment by bradreeder** [comment]
@jsms90 Let's leave this open for now. I'd like to revisit this before the start of next curriculum. 👍

**Comment by jsms90** [comment]
Sorry @harrygfox. I've been thinking a lot about what you said. And I think you're right. Opening and closing tonnes of issues is completely unhelpful. Not least because you miss out on the historical discussion on this topic, the next time you come to discuss it.

@bradreeder Sounds good.

**Comment by eliascodes** [comment]
https://github.com/foundersandcoders/master-reference/blob/master/pastoral-care.md
