### ISSUE TITLE
Standardise Morning Challenges

### ISSUE THREAD

**Issue by Jbarget** [foundersandcoders/master-reference#173]
As mentioned here https://github.com/foundersandcoders/master-reference/issues/43#issuecomment-282711843 i've seen a few morning challenges with a `solution` branch. 

![screen shot 2017-02-27 at 15 16 21](https://cloud.githubusercontent.com/assets/11725595/23362710/be775ff8-fcff-11e6-877b-e801ea8d227a.png)

Its quite common that people on the course ask for a rounded solution to look over and I think it would be a good structure to implement for any morning challenges that we use.

That way students become familiar with our resources and if they want to return to them in the future they know where to look instead of having to remember where solutions are kept for individual morning-challenges.

PS. I've added the labels i think are appropriate but if im missing or should remove any, please do

**Comment by eliascodes** [comment]
I think solutions files/directories on master should be preferred; maintenance becomes more difficult and less transparent when using a solution branch.

**Comment by Jbarget** [comment]
@eliascodes i agree, sounds good
