### ISSUE TITLE
Curriculum planning: FAC9 feedback overview

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#18]
This issue is intended as an overview of FAC9 feedback to remain open until the end of curriculum planning and their high priority issues are resolved. 

Particular points should be discussed further in their linked issue, not here.

----------------------

Curriculum draft alumni peer review #10 

----------------------

Ordered by priority as decided by FAC9 consensus.

Top priority:

* Gitbook: tighter scheduling, learning objectives, and context at beginning of each week #28 
* Restructure readme day #17
* Regular architecture / design pattern talks & workshops throughout curriculum #22 
* Week 1 toolkit proposal #24 
* Regular testing/ tdd workshops throughout course #16 

Secondary priority:

* Adjustments to week structure #27 
* Focus on organising weeks around the project #23 
* More CSS/ best practices #25
* Front-end framework/ build-tools #14  
* Make pre-course compulsory #26 
* Teaching and planning resources #23 
* Wellbeing resources #20 
* Informative classroom environment foundersandcoders/business#112

----------------------

Points specific to a week, and its s-g-c notes, are raised in an issue for that week to be consulted by mentors when they plan their week.

* Precourse #26 -- Jen, Cleo, Nick
* Week 1: Toolkit #24 -- Jen, Cleo, Nick
* Week 2: TDD/Testing #16 -- Ewelina, John, Peter
* Week 3: API #29 -- Emily, Ewelina, Lucy
* Week 4: Node core 1 #30 -- Marina, Will, Steve
* Week 5: Node core 2 #31 -- Nick, Marko, John
* Week 6: PostgreSQL #32 -- Emily, Tom, Steve
* Week 7: Hapi Templates #33 -- Marko, Will, Marina
* Week 8: Hapi Auth #34 -- Nori, Jen, Lucy
* Week 9: Redis, Pub/Sub, Sockets #35 -- Nori, Tom, Peter
* Week 10: UX (To be decided) #36

**Comment by bradreeder** [comment]
To be discussed post-UX week: 

* UX as week 2 rather than week 10 (or as week 10)
* Present updated curriculum draft
* How mentoring will relate to Nazareth
* Assign mentors to weeks

**Comment by des-des** [comment]
@bradreeder can we close now?
