### ISSUE TITLE
Swap order of play on Friday afternoon

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#196]
The end of the day currently looks like this: 

> 15:00-16:20 - Presentations (20 mins per group)
16:20-17:00 - Team Retrospectives (Team S-G-C)
17:00-18:00 - External Speaker or Upstairs Project

Let me suggest:

> 15:00-15:40 - Team Retrospectives (Team S-G-C)
15:40-17:00 - Presentations (20 mins per group)
17:00-18:00 - External Speaker or Upstairs Project

This is so that if the external speaker wants to, they can sit in on the presentations without having to then wait around during the team retrospectives.

**Comment by bradreeder** [comment]
@sofer My only objection would be that the presentations are technically a part of the group work and very often groups talk about the presentation during the retrospective. 

I'm for tighter time-boxing personally. What do others think?

**Comment by sofer** [comment]
@bradreeder this is a good point. Could we perhaps experiment with swapping the order in a week when an employer has expressed an interest in participating in the presentations and then review how successful it has been.

**Comment by jsms90** [comment]
@sofer Do we have any coming up?

As far as I know, The Guardian are the only ones so far, who incorporate a code review. And they're coming in on Thursday.

**Comment by sofer** [comment]
@jsms90 if I start offering it as an option, then it is likely that employers will take it up. Cubik are coming in next week. that means the possibility of Tim Ruffles reviewing people's projects. It would be an immense shame if we missed that opportunity.

**Comment by jsms90** [comment]
@sofer getting this changed for today onwards. Cool if we close this issue?

**Comment by jsms90** [comment]
Since the external speaker isn't coming before 5pm this week, Based on [FAC10's S-G-C last week](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-5.md#minutes), we're trying this running order:
14:00-14:30 Teams walk through the code together
14:30-15:30 Presentations (15 mins per group)
15:30-16:45 Group s-g-c
16:45-17:00 Team s-g-c

**Comment by jsms90** [comment]
Now that the speaker schedule is being organised more formally - combination of the Course Facilitator and hiring manager roles https://github.com/foundersandcoders/international/issues/57 - we are routinely offering external speakers the chance to watch presentations.

So I'm going to submit a PR to swap the order of play, as suggested
