### ISSUE TITLE
Wellbeing resource

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#20]
It was suggested in today's feedback session that we should have a document on stress-management, wellbeing, factoring your free-time, while at FAC.

If there are any suggestions for what this could include or look like please discuss here.

Related: #18

**Comment by njsfield** [comment]
Thanks for creating this good sir :) @iteles would you be able to share the suggestions/resources you mentioned earlier? I'll also try and connect with as many people as possible over the next few days to create a list of suggestions/advice, then make a PR

**Comment by iteles** [comment]
Yes! Some thoughts off the top of my head which we can add to:
+ @tsop14 has offered to come in and do (cheap!) yoga classes once a week from 08h30 - 09h30 or so
+ Cohorts have assigned a pair to cook lunch for the rest of the cohort once a week and everyone eats together
+ Spending time together in the park (mostly a summer one, admittedly)

Resources forthcoming when I have a sec!

**Comment by jsms90** [comment]
@iteles woohoo! Will @tsop14 only start with FAC10? ;)

**Comment by nelsonic** [comment]
`Yes`, having @tsop14 lead Yoga is going to be _awesome_!
`And` there's also: https://pragprog.com/book/jkthp/the-healthy-programmer
which has _many_ practical tips. 👍

**Comment by njsfield** [comment]
Awesome @iteles :), giving a Yoga option and potentially continuing meditation (via a resource on running meditation sessions to encourage current students to organise if they desire, or @msachi being resident monk for FAC10 ;) would be great. Thanks for the recommendation @nelsonic ! Looks very helpful, have you got a copy I could borrow to read? I'm a little light on moneyz atm but would love to read it.

Would it be appropriate to create a short survey for current/past FAC to collect data about lifestyle choices/tips that have helped people throughout the course?

**Comment by msachi** [comment]
I think it's a great idea to survey current / past students. In addition to asking the general question of what helped them to stay well, I would also ask more specifically what problems they encountered (e.g. exhaustion, frustration with team mates, etc.) and how they dealt with them -- and whether there some issues that they never managed to deal with effectively.

Mindfulness skills have benefited me tremendously throughout the course, and I will draft a README of summary points / tips that I think would be helpful to everyone (probably even without using the word mindfulness). I'd also like to try to address some of the problems that the students come up with in the survey, from a mindfulness perspective.

I'm intending to continue organising the meditation sessions in the new year so it would be great to mention this in the document alongside the yoga and other options.

@nelsonic The book looks great! I've also heard very good things about this one (even if the title sounds a bit less inclusive): https://www.zenprogrammer.org/

**Comment by shiryz** [comment]
@bradreeder is this something that you'd still like to do? if not, can you please close the issue.

**Comment by bradreeder** [comment]
@shiryz I'm not assigned to this one. I think @njsfield & @msachi were originally working on this. @ameliejyc springs to mind a good person to work on this too as she recently did a talk on mental wellbeing. Don't mind being closed if they're not interested in pursuing.

**Comment by zurda** [comment]
@njsfield , @msachi , @ameliejyc , are you working on this issue, or could it be closed? I'm happy to help with this if needed, LMK  (cc: @shiryz )

**Comment by astroash** [comment]
closing as no longer relevant. Feel free to reopen if this is not the case 🙂
