### ISSUE TITLE
Project management skills

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#21]
@iteles @nelsonic @des-des We've agreed it would be a good idea to gradually introduce project management skills throughout the curriculum to be integrated with the student's project work. Integration of agile methodologies is related.

Current topics in the draft:

* Git workflow
* User stories
* Committing against issues
* Pull requests. Across team QA, passing branches
* Git hooks
* User-testing
* UX

Questions:

* What subjects are we missing?
* What's the ideal order to present them in and on what weeks' projects?
* Should we introduce team roles like project manager and product owner at a certain point in the course? Related #18 
* Can we incorporate actual user-testing into the curriculum, perhaps in UX week or week 11+ ?

**Comment by jsms90** [comment]
Personally, I am strongly against introducing team roles. Although these roles may simulate a real-life working scenario, I don't think that it helps with the peer-led aspect of the course! I think it would encourage the idea that one person can overrule the others. Negotiating in making decisions is a brilliant skill, and not one that we should help the students to shy away from.

It also doesn't make sense to be done in a completely artificially created way (e.g. in the real world, the product owner is not the same person as one of the developers on our team)

**Comment by nelsonic** [comment]
@jsms90 _totally_ see your point of view on this. 👀  👍 
What I would _add_ to your observation regarding the "real-life working scenario" is that _encouraging_ people to "_role-play_" a different "_role_" _can_ stimulate them to consider a new perspective. This is something we _really_ need to write an _hypothesis_ for and figure out a way of collecting data/feedback to determine if people are being "_forced_" out of their "_comfort zone_" but still in a reasonably "_safe space_" and thus _learning_ a new things. 🤔

**Comment by jsms90** [comment]
We don't necessarily need to introduce separate roles, telling students "you are the scrum master for this project" (at least not in the first 8 weeks). But regardless of role assignment, all students should be aware of the skills above.

FAC9 didn't hear about any of the following until week 12+
+ labels & milestones
+ epic issues & checkboxes
+ user stories
+ committing against issues
+ user testing

When curriculum planning for FAC10, we introduced:
+ labels and milestones in week 1
+ committing against issues in week 1 (verbally)
+ user stories in the project briefs

FAC9 had 2 weeks (9-10) on UX

FAC10 & FACN1 had UX in week 10 as part of the 3 week project
FAC10 had user testing at the end of week 10 and the end of week 13
FACN1 had user testing at the end of week 13

We're introducing elements of [this "github guide"](https://github.com/foundersandcoders/master-reference/issues/218#issuecomment-299698116) to FAC11 based on their week 1 SGC:
> Merging without reviewing/resolving conflicts thoroughly
> More discussions between all the members of the team (Rebeca)
> Should have more time, 10 - 15 mins to review code (Minesh)

and it's clear that we need a more thorough explanation of "branch = feature" based on how often "stop what you're doing and merge my PR" is said by every cohort #398

**Comment by shiryz** [comment]
Roles are being introduced in London (see the following https://github.com/foundersandcoders/master-reference/issues/856) so will close this issue, if anyone feels like this hasn't been fully discussed, please reopen
