### ISSUE TITLE
Confusion with the 'Testing in hapi & server.inject workshop' (week 7 day 2)

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/master-reference#217]
https://github.com/SavageWilliam/injector
Some feedback from FACN1 re this workshop from today (we didn't finish it, decided to move on to something else):
- instructions were unclear- were we supposed to be imitating the server.inject method? Better info at the start of the readme would have been good
- make it clear which endpoint we are supposed to be testing with the first test (/string), maybe include brief info about the endpoints which have been written
- was the function supposed to take an options object? i.e. containing the path
- **main feedback** it wasn't really related to Hapi or handlebars at all, and we felt we should have been focusing on these today (morning of day 2) (which is part of the reason we decided to skip it)- this would have been better suited to week 4 or 5 when we used shot.inject

**Comment by jsms90** [comment]
@SavageWilliam Could you share your experience of running this workshop with FAC10?

**Comment by eliascodes** [comment]
No longer in the curriculum
