### ISSUE TITLE
Mentor's handbook

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#23]
Something I think we should create is a handbook for mentoring which could be introduced during curriculum planning as a workshop on how to plan and teach weeks. This way we can try to ensure a similar guideline is followed. Related #18 

Could include:

* Lists of good teaching/ coaching techniques: e.g. explaining new terminology, providing clear context, revisiting learning outcomes & new terminology during weekly whiteboard session, etc.
* Clear principles & guidelines for constructing your week: e.g. organising the week around what they will need for the project, etc.
* Iterative updates any time S-G-C notes relate to mentoring.
* List of things a mentor needs to prepare/ ensure happens. e.g. Making sure an external code review occurs on Friday mornings.

**Comment by bradreeder** [comment]
Resources suggested by FAC9 in gitter channel:

* Basic guide to lesson planning: http://www.crlt.umich.edu/gsis/p2_5
* Page of resources on curriculum and lesson planning: https://www.edutopia.org/article/new-teachers-lesson-curriculum-planning-resources
* Article on traps you can fall into when designing a curriculum: http://www.mckinsey.com/business-functions/strategy-and-corporate-finance/our-insights/daniel-kahneman-beware-the-inside-view
* Maker's academy curriculum: http://www.makersacademy.com/curriculum/
* General Assembly curriculum: https://ga-core.s3.amazonaws.com/production/uploads/program/course_catalog/128/WDI_CourseCurriculum_v2.0.pdf

**Comment by bradreeder** [comment]
I'm going to flag this as priority-2, as something for me to start preparing in advance of curriculum planning in January.

**Comment by bradreeder** [comment]
I'm not going to attach s-g-c notes that are related to mentoring skills in general to a specific week. Instead I'll post them here to be factored into the various drafts of this resource:

##### Project

* project-first curriculum design: students learn primarily through project-work. Careful attention should be put into choosing the project and designing the week around it.
* key skills objective at start of project.

##### Gitbook/ structure

* Consistent week-by-week structure.
* Update gitbook well in advance of each week. Keep it up to date as changes to the curriculum occur.
* Informative gitbook. But just enough the right amount of resources provided, it needs to not be overwhelming.
* Introduce the day's timetable at the start of the day and write up on whiteboard. Make it clear in the gitbook what the timetable is for each day, for each hour.
* Share S-G-C notes with upcoming week leaders to keep them in the loop.
* Give a head's up on next week's themes -- but don't give compulsory homework.

##### Techniques

* Don't move goalposts -- be consistent.
* Provide clear instructions to each task. Contextual info on topic at start of each week.
* Don't use small text sizes when projecting.
* Ensure there's someone around on the floor at all times for questions. Students tend to feel nervous going upstairs.
* Lollipopping -- try to find ways to engage with everyone in the classroom. Don't have favourites or only engage with the most vocal.
* Avoid giving students options on what to do. It's generally a sign you haven't prepared material.
* Step by step workshops like nodegirls.
* Ensure every new piece of terminology is explained and revisited in the weekly whiteboard session.
* If a workshop is intended to be fun and creative, ensure it is provided with clear objectives.
* Try to warn away from unstructured meetings. e.g. S-G-C's can easily derail, try to move things along swiftly.

##### Code-alongs

* Favoured as Monday morning workshop when introducing a new topic.
* Go slow and ensure regularly that everyone is keeping up.
* Prepare a readme to accompany the workshop for students to use as a reference.

**Comment by bradreeder** [comment]
Personal note: consult notes here https://github.com/bradreeder/Node-Intro-Workshop

**Comment by iteles** [comment]
Some historical (but partly still relevant) thoughts here: https://github.com/foundersandcoders/playbook/blob/master/teaching.md

**Comment by nelsonic** [comment]
@iteles `'member` when the "**playbook**" was _the place_ all the _detail_ was going to be kept...?
(_i.e. why do we have a "master reference" **aswell**...? what's the difference...?_)

**Comment by iteles** [comment]
No difference, one was just forgotten. It's kind of a shame to lose the commit history of either at this point.

**Comment by nelsonic** [comment]
http://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories

**Comment by shiryz** [comment]
Will close this issue since we have a resource if someone feels this is still relevant, please reopen
