### ISSUE TITLE
Node installation

### ISSUE THREAD

**Issue by ronanyeah** [foundersandcoders/master-reference#230]
I think the [precourse](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/precourse/installation-list.md) section should recommend [nvm](https://github.com/creationix/nvm) for installing Node.js.

**Comment by jsms90** [comment]
@ronanyeah wanna make a PR?

**Comment by ronanyeah** [comment]
@jsms90 yeah I'll do it this week
