### ISSUE TITLE
in coursebook/precourse/installation-list.md a minor change

### ISSUE THREAD

**Issue by Grenoblois** [foundersandcoders/master-reference#232]
In https://github.com/foundersandcoders/master-reference/blob/master/coursebook/precourse/installation-list.md

##We read: 

Chrome extensions:
- JSONView
- Google Cast
- Postman

##We should read:

Chrome extensions:
- JSONView
- Postman

=====

->Cast now integrated into Chrome.

**Comment by ronanyeah** [comment]
@Grenoblois Yeah looks good, make a PR. :+1:

**Comment by eliascodes** [comment]
Done via aed0ee953ae32b20953d3b65d3225d4379051104
