### ISSUE TITLE
Long term vision for master reference

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/master-reference#233]
Right now, the master reference will not really scale for more than one campus. It has mostly worked for London and Nazareth, but we have already [run into problems](https://github.com/foundersandcoders/master-reference/issues/163). Mostly this has been okay, as me and @bradreeder have been collaborating closely.

We need to define a long term vision to address the problems of reusability, scalability and autonomy.

**Comment by bradreeder** [comment]
Closed #234
