### ISSUE TITLE
advertising our community on our website

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#236]
1.
**As a** student nearing the end of the course
**I want to** see examples of CVs/portfolio websites
**So that** I can see what kind of thing would help me to gain employment

![image](https://cloud.githubusercontent.com/assets/15656538/25805248/c50917c8-3407-11e7-83d1-1bd8f574557d.png)

Note: Might be better off in a "freelancers" repo? But might be useful to have a link here, so that potential applicants are more likely to see it?

2.
**As a** potential applicant to the course
**I want to** see examples of CVs/portfolio websites
**So that** I can see what kind of level I should expect to get to by the end of the course  
&  
**so that** I can find out what kind of jobs people aim for after the course

### Suggested action steps
Website task group: https://github.com/foundersandcoders/our-site/issues/425
Marketing task group: https://github.com/foundersandcoders/london-marketing/issues/10
Involvement from the Freelance Committe (if it still exists @sohilpandya ?) and/or @freelancedad ?

**Comment by jsms90** [comment]
![image](https://cloud.githubusercontent.com/assets/15656538/25807517/c5437762-340f-11e7-9f52-f10c6fd12689.png)

**Comment by jsms90** [comment]
@harrygfox 
> sounds potentially impossible to maintain / keep up to date - maybe a where are they now of just the last cohort? (based on your user story)

#### Task groups
Each cohort now has a website task group (who are always a bit lost, because they don't really know what their remit is) & a marketing task group. This combination would make it very easy to ensure that the new cohort's details get put onto the website. They have 2 ours of business dev time each week during their course.

If someone within our community and/or the committees take it upon themselves to oversee this, it could be a roaring success.

#### Links for previous alumni don't _need_ to stay up to date
A "where are they now" implies that it should be up to date. What I'm suggesting is more about our entire community (i.e. anyone who wants to be on our website, not _necessarily_ every single individual who has ever gone through the course) is showcased :tada: After all, we're all about the community, right?

+ Photos will never be out of date - they are always of the time when that person was on the course :grin: 
+ Github links will never really be out of date.
+ LinkedIn links will rarely be out of date.
+ Personal websites may go out of date. But!
  + For every new cohort, they will at the very least have their one-page website from when they applied to the course
  + Every member of our community is welcome to update our website with their own details _if they care_. If they aren't fussed.....then what does it matter? :sweat_smile:

**Comment by jsms90** [comment]
@ronanyeah 
> I could put it together if we had a good place to get all the usernames from
> maybe members of the organisation
> github API?

Someone's week 8 project must be perfect for this!

**Comment by jsms90** [comment]
@ronanyeah 
A branch is coming from @m4v15's week 8 project https://github.com/FACN1/week8-sulias

**Comment by m4v15** [comment]
https://github.com/FACN1/Reavis/tree/allofFac I kind of adapted our week 8 project to do something like this  - db_build builds a database of fac members

https://github.com/FACN1/Reavis/tree/justfacn1 slightly different api call to get just members of FACN1

**Comment by jsms90** [comment]
@ronanyeah https://github.com/dwyl/who

**Comment by oliverjam** [comment]
I think @akin909 tried to build something like this a while ago but had trouble because lots of the Github organisations for various cohorts are private (or don't appear to have all the cohort members etc).

This is a really cool idea though, even if we have to manually compile the data. I doubt it would be that hard for at least the previous few cohorts.

**Comment by m4v15** [comment]
I did it a while ago and can't really remember properly, but I think I ran into the same problem and got around it by using my own github api key in the request header - members of an organisation can see all other members, private or public. https://developer.github.com/v3/orgs/members/

**Comment by m4v15** [comment]
[Super basic rebuild and deployment of FAC member database](https://facdb.herokuapp.com/)

Adapted from our week 8 hapi-auth project. 

[Source here (on allofFac branch)](https://github.com/m4v15/Reavis/tree/allofFac)

Like I say, adapted from another project so errr ignore the readme and messy code plz thnx

**Comment by emilyb7** [comment]
@m4v15 that's a really cool project!

I think it would be really nice if we had everyone divided up according to their cohort. This would mean manually compiling a list of everyone's GitHub handle.

But I don't think there's any way for us to use the API directly anyway, as we can't make 100+ requests to the GitHub API every time someone goes to the page, and (as far as I know) we don't have any way of using an access token / caching the data with the basic GitHub pages setup (please correct me if I'm wrong!).

However, we could probably create some kind of script that does that hard work for us, and run an update from time to time to check for changed data, etc?

**Comment by eliascodes** [comment]
@emilyb7 Suggest heroku app running a cron job scheduled every ~1-3 months saving user names/handles/img URLs to DB, exposed via API that can be queried from the client. That way you avoid any additional build steps or periodic re-deploys of the gh-pages site.

**Comment by jsms90** [comment]
I don't actually know whether this is the best way of going about it anyway.

I think people's names should be on there, not just their github handles. Not everyone puts their name on github.
A photo of someone's face would be better than [whatever someone's github profile pic is](https://github.com/bradreeder/) :laughing:

**Comment by zurda** [comment]
Is this an ongoing discussion, or is this outdated? cc: @sofer

**Comment by m4v15** [comment]
I think outdated as website was redesigned since then. Anyway, I don't think issue belongs in master reference and should be either in london-programme our our current site repo.
