### ISSUE TITLE
wrapping up week 12 - change final day from week 1-8 structure

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#237]
### Why
+ The "code review, respond to issues, present" structure makes a lot of sense when the week's objective is _learning that technology_. Jumping in to someone else's project cold is valuable experience. But is an hour of code review the best thing for delivering the desired [learning outcomes](https://github.com/foundersandcoders/master-reference/blob/62d2049a8f6dfbd158779617c936c3d6b36b4550/coursebook/fragments/product-build/learning-outcomes.md#learning-outcomes) of this 3 week project?
+ During weeks 1-8, students are already aware of what the project _is_ before code reviewing. So issues can be more technically focused. Then it is still manageable to respond to issues right before presentations.
+ In order to help people step into the codebase & make the hour of code review more fruitful, it might be useful for teams to present their idea again _first_. But does it still feel as worthwhile to code review and respond to issues _after_ presentations are finished?
+  Towards the end of those 8 weeks, it becomes increasingly difficult to code review each others projects anyway. If people are using technologies that the others have never used, it might make code reviewing even harder, and less useful.
+ Without being able to step into the codebase as quickly, the issues that they raise might be more user-focused issues. This kind of feedback is probably more useful to receive in the context of user testing / research, that is seen as part of feedback & therefore helps in planning for the next sprint. If they find out that the UX is not ideal via github issues directly before they present, this can just be disheartening instead of productive.
+ FACN1 haven't really done any user testing yet, and will miss this valuable lesson if it is left out of these 3 weeks altogether.

### What / How - Timeline
**Morning**
+ Intro on how to conduct user testing  
(maybe FAC10 don't need this as much. FACN1 seem to have had less on _how_ to conduct interviews)
+ Plan user testing
+ Conduct user testing - _OUTSIDE THE SPACE_

While students are conducting user interviews, any alumni who are free could code review their projects? Since they don't have any QA-ing during these 3 weeks, this would be the only opportunity to get proper technical feedback on everything they have implemented. But I don't think that going through this feedback and responding to issues is _essential_ for achieving the learning outcomes.

In future, we may want to think about adding this external code review into the morning of day 3? How about raising this idea during S-G-C and seeing what they think?

**Afternoon**
+ Plan presentations
+ Deliver presentations:
  + Briefly go over the idea, as it was defined during the pitch / sprint planning
  + Demonstrate the existing features, specifically mentioning how well the initial users stories were met  
(Think: presentations that your dev team might give to the PO, or a presentation that the PO might use for further funding)
  + Describe the next features you would implement  
(Think: what did we learn from user testing & how can that inform our next sprint?)
  + Q&A from the rest of the cohort
  + Follow up by describing one technical challenge & one non-technical challenge  
(Think: what did we learning about Agile Development (SCRUM)?)
+ Stop go continue

**Comment by jsms90** [comment]
![image](https://cloud.githubusercontent.com/assets/15656538/25867549/8c5df97e-3502-11e7-934c-60113d4a3b9f.png)
![image](https://cloud.githubusercontent.com/assets/15656538/25867587/ae52e0a8-3502-11e7-96b3-28491fa28601.png)
![image](https://cloud.githubusercontent.com/assets/15656538/25867608/bd74d6cc-3502-11e7-8c46-46671b6a149c.png)
![image](https://cloud.githubusercontent.com/assets/15656538/25867616/c94ba44e-3502-11e7-8c08-36afb91dd61a.png)

**Comment by jsms90** [comment]
**Intro on how to conduct user testing**
UX week articles from dropbox:
+ [5 steps to create good user interview questions](https://medium.com/interactive-mind/5-steps-to-create-good-user-interview-questions-by-metacole-a-comprehensive-guide-8a591b0e2162)
+ [User Interviews - the beginners guide](http://theuxreview.co.uk/user-interviews-the-beginners-guide/) 

FAC9 examples:
+ https://github.com/FAC9/ux-ui-project/blob/master/ui-testing.md
+ https://github.com/FAC9/future-leaders/blob/master/docs/user-testing.md

**Presentations**
+ Largely like a [sprint review demo](https://www.agil8.com/sprint-review-much-just-demo/).
+ But instead of being conducted by the dev team & aimed at the PO, students are conducting it with the PO to other dev teams. Hence the small intro to the project, "as it was defined during the pitch / sprint planning".

Suggestions from @des-des:
> I think no code review, since the code bases are prob mostly quite big. I think some students will feel very lost. I think the focus is on what has been created. I think straight into demos. Maybe to SGC before demos. Maybe after the demo, students can take questions, then talk about one technical challenge and one non-technical challenge (i.e. teamwork) they faced.

I've updated the timeline above accordingly:
+ Removed
>  + Explain how you worked as a team  
> (Think: what did we learning about Agile Development (SCRUM)?)

Added:
>  + Q&A from the rest of the cohort
>  + Describe one technical challenge & one non-technical challenge  
> (Think: what did we learning about Agile Development (SCRUM)?)

I'm not sure about SGC before presentations. In some ways, it's better to end the day with presentations because it's kind of ending on a high. On the other hand, you don't hear anything about presentations themselves during SGC & FAC10 feedback has repeatedly been to have presentations straight after lunch :thinking:

**Comment by jsms90** [comment]
Suggestions from @des-des:
> I think no code review, since the code bases are prob mostly quite big. I think some students will feel very lost. I think the focus is on what has been created. I think straight into demos. Maybe to SGC before demos. Maybe after the demo, students can take questions, then talk about one technical challenge and one non-technical challenge (i.e. teamwork) they faced.

I've updated the timeline above accordingly:
+ Removed
>  + Explain how you worked as a team  
> (Think: what did we learning about Agile Development (SCRUM)?)

Added:
>  + Q&A from the rest of the cohort
>  + Describe one technical challenge & one non-technical challenge  
> (Think: what did we learning about Agile Development (SCRUM)?)

I'm not sure about SGC before presentations. In some ways, it's better to end the day with presentations because it's kind of ending on a high. On the other hand, you don't hear anything about presentations themselves during SGC & FAC10 feedback has repeatedly been to have presentations straight after lunch :thinking:

**Comment by jsms90** [comment]
After [reading up on sprint reviews](http://agileforeveryone.com/2013/03/20/17/) (and after my own experience with IP Cortex), I wonder whether it might be worth putting an actual sprint review into these 3 weeks & not conflating it with presentations

**Comment by beardfacebo** [comment]
@jsms90 happy to share experience of leading sprint reviews if possible

@bradreeder If you want AFC staff/UCL students/Tavi staff as user tests today/tomorrow let me know and I'll see who I can drum up, especially if you want specific user bases. Also happy to give feedback on technical choices as part of larger considerations (most of my job atm) if helpful at all.

**Comment by jsms90** [comment]
The [tips](https://github.com/FAC9/future-leaders/blob/d12df8559d7464dbc7be509aedea413f9064faca/docs/user-testing-advice.md) that @Cleop got for our group in FAC9's UX/UI week might also help

**Comment by jsms90** [comment]
Given that this is the first time we're doing it in Nazareth, and we don't know how receptive people will be, I've suggested that they come back 15 mins before lunch & report back on how many interviews they've managed to conduct so far.

@m4v15 had a good idea - do a little brainstorming as a group about good locations to try. FACN1 spent 10-15 mins discussing this before planning their scripts

**Comment by jsms90** [comment]
Questions that have come up so far:
+ Will people really give you the time? Isn't this just annoying, like stopping people on the street & asking someone to fill in a survey?
+ Would this be our job in the working world? Does it depend on the size of the company? Will we actually be expected to do this, or whose job is it?
+ What was your opening line to people when you did this?

**Comment by jsms90** [comment]
Notes from Thursday:
**Where to start**
FAC9 spent a lot of time setting up an HTTPS server for the first time.
FAC10 have set up a server from scratch more often & have seen HTTPS in week 8 already. They might appreciate more theoretical understanding of how HTTPS works.

Should we start them off with a server already written, to save time? Or would it be beneficial to allow them to do it themselves?
**Action point:** Give boilerplate code. The starting point of the workshop is to clone a repo with an HTTPS server already set up

**Resources before the weekend**
+ Classes
+ Promises

**Gap between high level explanation of problem & setting of task**
+ More intro to WebRTC methods e.g. RTCPeerConnection?

**Comment by jsms90** [comment]
Non-technical challenges (during presentations):
+ Raising issues - either went too broad or too granular. Don't know how to solve that, but think that going granular is probably bettert
+ For time management - putting time estimates on github issues was really useful, in case one of us has missed a day or something takes too long. Just tracking how long things are taking is useful, and also for planning out what 
+ If we had known how much time we would lost on setting up SASS and Babel, we might have scrapped the time we spent on that, in favour of making a more complete product. But I do I regret that? Well, it wasn't a waste in terms of learning. It was really good to learn how to use those technologies.
+ Being in a group of 4. We had so many opinions. Having 1 girl with 3 guys. Felt like we needed to be a project manager / owner. I didn't want to be it, because I wanted to be doing it together. I found that the github issues didn't really work for us. I think they were too small. It didn't really work for us, splitting the user journies into stories into technical tasks. Maybe use user stories as a reference point, but only technical tasks are issues.

**Comment by jsms90** [comment]
SGC notes from FACN1
https://github.com/foundersandcoders/nazareth-curriculum/blob/154e553ae03b07f6c5f59845828fca9872d58624/stop-go-continue/fac-n1/week-13.md

**Comment by bradreeder** [comment]
@jsms90 Thanks a lot for this. I will be sure to keep to the same schedule tomorrow. 👍

**Comment by des-des** [comment]
lol great late night curriculum planning by me
 >  I think straight into demos. Maybe to SGC before demos. Maybe after the demo, students can take questions

**Comment by des-des** [comment]
@jsms90 broadly agreeing with all this. Do you want to turn it into a pull request (branch off the still unmerged #103 pull then we can review it once that one is in)?

**Comment by jsms90** [comment]
@des-des already done #238

It has WIP in the title, just to make sure no one merges it before #103

**Comment by jsms90** [comment]
@njsfield has made some more [user testing materials](https://gist.github.com/njsfield/cad2904e0fa3a74b32fd5accbca50c2e) for day 15 :heart_eyes_cat: 
(just trying to get it all in one place in this issue, so we can get everything into `master-reference` to be iterated upon)

**Comment by bradreeder** [comment]
@jsms90 Converting the UX week from dropbox to github is next on my todo list and will be done tomorrow but thanks for the offer. 👍

**Comment by jsms90** [comment]
@des-des I don't think this issue is finished?

> I think we need to do the following:
>
> * Update design thinking workshop file as it's not self-evident how to do the workshop from the timeline alone.
> * @harrygfox maybe we should add your slides for your Monday talk? 
> * Google Ventures Tuesday, Wednesday and Friday need more detailed descriptions of tasks involved. @harrygfox Did you use any resources that are not referenced in the dropbox?
> * Add a suggested format for running the presentations.

Or would you say that they should raise separate issues for the addition of each of these things to the FAC10 version?

I've said that I don't think they should just continue adding, never-endingly to the same PR. But I know you like WIP pull requests.

Thoughts?

**Comment by des-des** [comment]
@jsms90 actually that was you not me..

![image](https://cloud.githubusercontent.com/assets/12845233/26580991/70359334-4532-11e7-88c5-397a06e01fec.png)

**Comment by jsms90** [comment]
So it was. Just had a look back. I said to make more issues, didn't I? :flushed: 

What do you think? Commit & PR against this one or raise granular issues?
