### ISSUE TITLE
Week 8 - suggestions for reading break

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#246]
It's likely worth us creating a file for the week 8 folder including suggestions for how to use the reading break. For example:

* Creating a github cv with a skills summary like https://github.com/SimonLab/CV#skills
* Updating your linkedin + endorsing others in cohort.
* Getting started on portfolio site.
* Coming up with a project idea to pitch + background research.

**Comment by iteles** [comment]
We should also actively encourage at least two days of rest and family time because people tend to be pretty exhausted by this point.

**Comment by zurda** [comment]
For us at FAC-15, we received a well organised email from @freelancedad with a list of recommended reading material and links. Is this also available for other programs, and could this be closed - or is there additional action needed on this issue?
