### ISSUE TITLE
Hapi vs. Express

### ISSUE THREAD

**Issue by majakudlicka** [foundersandcoders/master-reference#251]
**WHY**

There is a prevalent feeling in the cohort that it would have been more useful to have learnt Express.js instead of Hapi.js. framework. There is also a feeling that the reasons why Hapi was chosen have not been properly explained to us. Please note that this is a repeated issue - other cohorts have had similar concerns.

**WHAT**

We propose to teach Express instead of Hapi.

- Hapi had 292,962 downloads last month vs Express having been downloaded 11,122,837 times. This implies that Express is 38 times more popular than Hapi.
- Express has much more supporting documentation and guides making it easier to learn and use (A simple Google search for "Express.js" returned 78,900,000 results vs 369,000 results in a search for 'Hapi.js': ratio of more than 200:1).
- Having prior knowledge of by far the most popular framework makes F&C graduates more employable.
- We appreciate that there are valid reasons to use Hapi vs Express in certain circumstances (as listed in [this document](https://github.com/dwyl/learn-hapi)), however there is a general consensus of the cohort that this alone doesn't justify teaching F&C graduates Hapi sacrificing Express.

**HOW**

- We propose that at the beginning of the relevant week, the Cohort is presented with a comprehensive and balanced overview of pros/cons of learning different server-side frameworks.
- We propose that the curriculum is updated to teach Express.js instead of Hapi.js. The change will be made for the next curriculum at the discretion of the mentors who are assigned to weeks implemented using Hapi.js

**Comment by ronanyeah** [comment]
We've been having debriefs with the Gaza students this week and it turns out they've been referring to Hapi as 'Sad'.

I'd like to add another reason that Express is a better option. Hapi is configuration based. This means that until you know the entire API your essentially have to solve every single issue in a different way by Googling or or reading documentation. Whereas with Express you essentially just have to learn how it's middleware works and you are done. This is much easier for beginner productivity.

As part of [this](https://github.com/foundersandcoders/master-reference/issues/242) issue I will be making some Node.js glitches. A JSON + static file server in vanilla node, hapi and express. This will highlight the advantages and disadvantages of each option.

**Comment by ronanyeah** [comment]
OK so the three server examples can be found [here](https://github.com/ronanyeah/nodejs-server-examples).

**Comment by eliascodes** [comment]
Might this issue be extended to discuss dropping backend frameworks altogether? If we're already talking about not doing authentication in a framework (#263), templating really doesn't seem like a reason to keep them around. Or does this belong in a different issue?

**Comment by des-des** [comment]
@eliascodes I am on the fence about that. Mostly I agree, but I do think there is value in going through the pain of fighting through (bad) documentation, as it is a very relevant / valuable skill, right now we only do that once on the course. Not teaching a node framework also leaves us in the difficult situation where students will all have to learn express / hapi either for the long project, or for their first commercial project / work..

That said, I agree that we should teach auth vanilla, as there are some conceptual gaps left unfilled by teaching it with Hapi.

Could we do auth in week 7, vanilla, then have a final express / hapi week with templates?

@ronanyeah I strongly agree on the point of hapi being configuration based.

**Comment by eliascodes** [comment]
Re-posting from gitter:

https://twitter.com/eranhammer/status/868568699107540992

**Comment by ronanyeah** [comment]
@des-des 'OK this week we are doing templating. You can choose the framework yourself, and we recommend Hapi because the documentation and API discoverability is crap and we all have Stockholm Syndrome.' :smile:

**Comment by ronanyeah** [comment]
'And apparently we will have to start paying to keep the code secure and feature rich.'
'Can't we make pull requests?'
'No, the maintainer takes the the 'D' in BDFL very seriously.'

**Comment by eliascodes** [comment]
Proposal passed & implemented
