### ISSUE TITLE
Lightning Talks from your Cohort 

### ISSUE THREAD

**Issue by lucyrose93** [foundersandcoders/master-reference#254]
**What?**
Talks of 5, 10, 15 minutes given by members of Founders and Coders on extra-curricular topics that they are passionate about

**Why?** 
- Bonding <3
- Get to know your cohort 
- Draw attention to the fact that we all have access to an invaluable network of bright individuals with unique skill sets
- It's fascinating
- Broaden horizons

**When?**
During a slot when an external speaker might come in, i.e. 5-6 pm on Thursday and Friday evenings
OR
After 6pm  

**Who?**
It wouldn't be enforced but everyone should be warmly invited to have their say

**How?** 
A little prior thought would be necessary, perhaps some props, visual aids, or interactive exercises too

**Example topics (from the group):**

- Adult learning. How you can destigmatise lack of knowledge
- Art and technology
- Social media: running campaigns
- How to walk on a catwalk
- How to dress for a casting
- How to get into events for free
- What to do if you get arrested / how to sue the police
- Running a startup
- Psychobiology 
- Hardware
- Linux
- Progressive web apps 
- Travelling and learning Spanish 
- Living in Russia 
- Customer development
- Launching a startup in a new market 
- Manufacturing in China
- Tech repair
- Working in a startup 
- Raising funds/ crowdfunding
- Body language
- Colour theory 
- Human trafficking
- Working in/for the third sector (could be a joint effort)
- Romania: politics, immigration, and public perception in the UK
- Breathing techniques for concentration, anxiety, confidence, endurance
- Issues with Western spirituality

**Comment by lucyrose93** [comment]
When? 
15 minutes per week at the end of the day perhaps

**Comment by eliascodes** [comment]
Proposal not taken to vote, and no movement since, so closing for now.
