### ISSUE TITLE
Best Learning Resources 

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/master-reference#255]
## WHY

As students of Founders & Coders, we come across many resources (articles, online courses, video tutorials) that we found particularly useful in understanding a specific topic. There is a consensus that we should compile this knowledge in an accessible location so everyone can benefit from them and not having to waste time sieving through the bad ones (although contributions welcomed). 

Currently: https://github.com/foundersandcoders/resource-sharing

## WHAT
PLAN A: We intend to build a web app that enables students and mentors alike to add, review and up-vote the best community curated resources. 

The resources can be filtered by:
1. Week - When they are covered in the 8 week curriculum. AKA weekend reading? 
2. Topic - E.g. javascript-promises, html-event listeneres, css-flexbox etc. 

PLAN B: Trello? Github readme? 

## HOW 

- A link to this app will need to be on the master reference as it's usefulness will only be apparent when fully utilized and contributed towards. 
- We should also be sharing all log-ins for external resources (e.g. Egghead.io). 
- An additional feature to encourage participation could be a top contributors list.

**Comment by Jbarget** [comment]
@jsms90 @SavageWilliam isnt this already half done with:

https://github.com/foundersandcoders/resource-sharing

**Comment by Jbarget** [comment]
@yvonne-liu is the plan to build on top of https://github.com/foundersandcoders/resource-sharing?

**Comment by jsms90** [comment]
During FAC11, we introduced a "FAC Library" biz dev task group. This task group began collating resources in [this google spreadsheet](https://docs.google.com/spreadsheets/d/1cF2UHFBRt-6FMrsu6XJrGZYVRBxb6QR82ezKsz3YGPc/edit#gid=0) & then made [this app - "the FAC Library"](https://thefaclibrary.herokuapp.com/) during postgres week.

Finally, members of this biz dev task group pitched the idea to their cohort during week 10 (as a potential 3-week internal project).

Although this idea wasn't initially chosen, @azayneeva & @AbdullahChaudhry eventually moved from their original idea (a progress tracker) to the FAC Library team's suggestion.

Welcome....drum roll....
### FAC Share [(github repo)](https://github.com/azayneeva/FAC-Share)
Download [this chrome extension](https://chrome.google.com/webstore/detail/fac-share/knnjpbefodpffppbnafpnlopdghenepn/related) to start adding resources to [the FAC Share website](https://fac-share.herokuapp.com/).

@yvonne-liu happy to close this issue?
