### ISSUE TITLE
Change week 2 project from stopwatch to todo app

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/master-reference#256]
# Change week 2 project from stopwatch to todo app

## What?
A lot of people on FAC10 found that they did not have an overall positive understanding of testing after week 2. we have narrowed part of this down to the fact that we were using TDD to build a stopwatch, which does not necessarily lend itself very well to TDD. <br>It also means we have to deal with async stuff when it comes to our testing, which some of us found quite confusing. We ended up testing the wrong things and not really learning the value or practical application of TDD, or the way to write good unit tests.

Thus, we suggest that we change from the stopwatch project to the [todo app](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/fragments/projects/tdd-todo). This seemed to get better reception than the stopwatch app, and we hope we can hone in ang get peole understand the value of TDD.

We don't want to remove the async aspect from week 2 and would also propose that we have a workshop on callbacks on the Monday, followed by the waterfall morning challenge on the Tueday. Then during week 3 show about how to fit testing around async stuff re: api calls. 
## Why?

I've sort of delved into this in the what, but in essence:
We (I) velieve that the todo app (or generally something not async) is a better way to learn the value of TDD/testing than the stopwatch project is.

## How?

The mentors taking ownership over week 2 would go over the structure of the week, create a workshop on callbacks for the Monday, and go over FAC-N1's tdd-todo repo and make any refinements they want, and move it over to the master reference.

**Comment by des-des** [comment]
Yay! Here is the todo project: https://github.com/foundersandcoders/master-reference/tree/master/coursebook/fragments/projects/tdd-todo (needs some work).

**Comment by oliverjam** [comment]
@jsms90 @finnhodgkin 

### Problem

On practically every FAC10 project after week 3 we were told to write front-end tests, but ended up with empty folders where the tests were supposed to be. One reason for this was that once CLI tests, Travis and Istanbul were introduced QUnit became super easy to ignore.

>Why bother to write front-end tests that are completely ignored by continuous integration?
- most of FAC10

As far as we know QUnit only works with Travis and Istanbul when it's run in a browser-less environment. So unless we teach JSDOM (or PhantomJS, etc) whenever QUnit is used to test browser functionality (the DOM) it won't work with Travis.

Even before we started Node QUnit was encouraging bad testing. A number of stopwatch projects contained tests like "`document.getElementById` returns an element" or "`setTimeout` delays the call of a function by 1 second" (and even "tests that `h1` has correct title").

Although this was mostly down to confusion about what and how to test, it wasn't helped by QUnit making this kind of test possible.

In our opinion it's as important to teach people to write testable code as it is to write tests. Switching to Tape could help enforce this by making sure that DOM manipulation and side-effect heavy code is both kept separate and to a minimum.

#### Evidence

FAC10's [ Testing Week stop-go-continue](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-2.md) included:

> Stop the stopwatch project

> Have a code-along demonstration of people doing TDD (this could be the romaniser challenge)

and from FAC10's [Node Week 1 stop-go-continue](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-4.md):

> There needs to be a strong direction for tests

### Solution

Encourage testable code and remove QUnit from the curriculum:

+ Give an overview of npm at the start of the week so they understand how to install and run Tape
+ Swap the "Learn TDD" Dwyl workshop for "Learn Tape"
+ Rewrite the Roman Numerals challenge as a codealong to demonstrate best-practice TDD
+ Swap the stopwatch project for something more testing-friendly (a to-do app)
+ Provide some pure functions as boilerplate in the project to encourage writing more testable code

### Hypothesis

Keeping testing consistent throughout the course should encourage students to write front-end tests even in the later weeks. Hopefully it will also give them a head start on writing more testable code in general.

Ideally we'll see FAC11 writing more pure functions, more modular code and more tests in general.

**Comment by eliascodes** [comment]
Proposal passed & implemented.
