### ISSUE TITLE
redistribute content of oauth/auth week

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#263]
## Change "OAuth week" / "auth week"
Original idea raised in [this issue](https://github.com/foundersandcoders/london-curriculum/issues/47) in `london-curriculum` 

### Why
1. Implementing 3rd party log in is really cool to learn about but we are sacrificing some much more fundamental topics!

2. In order to implement OAuth, you need to know **a lot** that we haven't taught students yet. The only way to power through the OAuth flow is by telling students "we're just going to skim over this" for _way_ too many fundamental topics
    + **Authentication** left to a research topic - this is NOT enough. All teams should have a _thorough_ introduction to schemes & strategies, if they're supposedly learning hapi.  
    + **Authentication** (in general) is only introduced as part of oauth - some teams haven't implemeted a normal username & password login before (essential for future projects) logging in with a 3rd party (not essential).
    + **Validation** is essentially a stretch goal during hapi week. Password validation is never practiced during OAuth week (because login is done through a 3rd party)
    + **Session management** & authentication are each introduced & implemented for the first time in the same flow - causes confusion about which problem is being solved by which thing. Using cookies as the only form of session management, even though they have just been introduced to databases...
    + Glossing over local storage and caching.
    + _Horrendous_ introduction to **security concerns** i.e. a research topic

### What
We have the scope to completely revamp the introduction to backend, and give students a better understanding of the following core development concepts:  
+ Validation
+ Session management
+ Authentication, authorisation & the difference between them

### How
Spread these fundamental topics through the course. They don't need to be covered in a backend framework week. 4 weeks in node core, 1 with a framework.
+ week 5 (currently: 2nd workshop on testing in node, error handling, node shell) include server-side validation
+ week 6 UNCHANGED - still on introducing databases
+ week 7 on session management (databases & cookies) & authentication including hashing & signing
+ week 8 on server-side framework & templating

**Comment by ronanyeah** [comment]
@jsms90 Could those weeks be swapped around and Hapi/Express are the second week? Implementing OAuth without a plugin could be a away of ensuring better understanding.

**Comment by oliverjam** [comment]
I agree. Hapi plugins abstracted so much of this away that I have no idea how I would do this with another framework/vanilla Node. I'm still not sure why we used Hapi here — is it overly complicated to do this without a framework?

**Comment by ronanyeah** [comment]
All implementing OAuth requires is reading documentation and providing a callback URL on your server. There is no reason for beginners to be using a plugin to achieve that in my opinion.

**Comment by emilyb7** [comment]
@oliverjam @ronanyeah  I don't think we used any plugins for oauth flow itself, right? Cookies and JWTs though, yes, plugins everywhere. And I would have no idea how to do either of those without hapi, so that could be interesting...

**Comment by ronanyeah** [comment]
@emilyb7 I'm currently writing three servers with identical frontends on [Glitch](https://glitch.com/) for vanilla, Hapi and Express that will provide cookie auth, JSON and static file serving. I'm hoping it can be a core resource for Node week(s), and demonstrate the value and differences of the two frameworks.

**Comment by oliverjam** [comment]
@emilyb7 You're right, I was thinking of cookies/JWTs. Maybe the fact that we have no idea how to do those without Hapi means we're not teaching it right. I don't want to have to fundamentally relearn the concepts every time I use a different server technology.

**Comment by jsms90** [comment]
Mentioning plugins was probably a little misleading. My point was that understanding more about how hapi deals with authentication would enable you to understand how hapi uses plugins. Because you have to gloss over authentication really really quickly, maybe it seems like it's hapi's fault for abstracting too much. But it's not. It's just that you are completely fast forwarded through learning all of these giant topics.

> All implementing OAuth requires is reading documentation and providing a callback URL on your server. 

OAuth itself may not be too complex to understand. It is about its position in the course & what else the course is missing. We teach OAuth but we leave crucial concepts to 3 hours of research afternooon!
+ This is often the first time students are implementing _any_ kind of log in. It is confusing to learn the OAuth flow, before you learn how to authenticate your user and validate their details with something simpler e.g. a regular username / email input box.
+ This is the first time students learn anything about authorisation i.e. a user's permission to access a route, or see particular content on a page
+ Before I introduced something practical on hapi's strategies & schemes, these were left to a research topic (?????)
+ This is the first time they are introduced to persistence of state. We teach nothing about the options available to them e.g. Local Storage (also left to a research topic)
+ They know nothing about session management prior to this. Presenting cookies as the only option means that they are not equipped to make a proper choice in the future.

OAuth week is not just about putting a github button on the page. We also ask them to do a tonne in their project. It's just not realistic. And when you look at it like this, it begs the question, is learning to add a facebook button to your website important enough to justify a week on it? Especially when we could be teaching them any of the topics above in more depth?

**Comment by ronanyeah** [comment]
@jsms90 Yeah that does sound pretty heavy. I like OAuth but it't not that 'essential'. Perhaps just cookie auth and routing is enough for the base curriculum and the students could be expected to learn it on a 'if the client needs it' basis.

> Because you have to gloss over authentication really really quickly, maybe it seems like it's hapi's fault for abstracting too much.

As a config based ecosystem, abstraction is literally it's _selling point_.

**Comment by jsms90** [comment]
Yeah, I know. I'm just saying that _this_ isn't a good example of what hapi is abstracting away.

This is a good example of us as mentors and deliverers of the curriculum saying "don't worry about knowing what this does, just type `server.strategy` :+1: now just require in cookieAuth, now just...."

**Comment by ronanyeah** [comment]
It looks like the last two weeks are going to be getting a shake up. How does that process start?

**Comment by ronanyeah** [comment]
@emilyb7 Glitches are done, as part of this [issue](https://github.com/foundersandcoders/master-reference/issues/242).

**Comment by ronanyeah** [comment]
How's this for an idea?

__Week 4 + 5__: Node, as usual
__Week 6__: Authentication, still vanilla Node.js and comprised of:
- Managing cookies using headers
- Managing cookies using [this](https://www.npmjs.com/package/cookie) (12 million downloads a month!)
- JSON web tokens using this [this](https://www.npmjs.com/package/jsonwebtoken) (2 million downloads a month!), and perhaps localStorage
- OAuth
- Secure routing

__Week 7__: PostgreSQL as usual
__Week 8__: ??? (Templating, Webpack, UX, React, whatever)

**Comment by oliverjam** [comment]
@ronanyeah That looks great. I'm not sure about Week 8 there. As much as I'd like to see Webpack/React etc there it might be a bit weird to do 4 weeks of backend and then jump to something completely different. Maybe templating + a Node server framework still works as a natural finale to the backend?

**Comment by ronanyeah** [comment]
@oliverjam Yeah that was just a handwave, I don't have any suggestions for week 8 at the moment (and this probably isn't the best place to discuss it anyway).

Templating is great, but its heavily tied to your backend framework of choice, on which point I think the curriculum [needs](https://github.com/foundersandcoders/master-reference/issues/251) to be more agnostic. But we could have resources for Hapi/Vision AND Express/Pug if it comes to that.

**Comment by jsms90** [comment]
@ronanyeah Sounds like you're just moving the same week 8 content into week 6, and doing it in node core instead of hapi? I'm talking about removing OAuth and covering other things more thoroughly (see the "How" above)

Also, some content might be better to cover during/after postgres week.

How about
Week 1: Toolkit week (git, github, HTML & CSS)
Week 2: Testing
Week 3: Front end JS
Week 4: APIs
Week 5: Node 1
Week 6: Node 2
Week 7: postgres
Week 8: back end framework

During week 3, introduce client-side storage & client-side validation.
During week 6, introduce server-side validation
During week 7, introduce server-side storage (session management)

**Comment by ronanyeah** [comment]
@jsms90 I think one of the reasons we are getting poor learning outcomes for authentication is because it is being taught using a bunch of very abstract plugins and it would be better to teach authentication by itself before we move to a backend framework. What do you think?

**Comment by eliascodes** [comment]
@jsms90 could this proposal be simplified by just saying that we get rid of OAuth and teach core authentication/authorisation concepts in Node? Then you wouldn't need any of the hapi/express specifics in what/how. 

If a cohort really wanted OAuth it could be a second-half of the course thing.

**Comment by jsms90** [comment]
Good point :thinking: To be fair, I guess it has nothing to do with hapi vs express, and everything to do with how much work people are willing to take on. And I just have no idea whether people feel capable of / are willing to write so many weeks from scratch. 

Option 1 is less work, because they have already been introduced to all these things. It's just that everything is glossed over for the sake of ploughing through to OAuth, so I doubt everyone has a solid understanding of what they're writing or why.

Option 2 is much more work, and it impacts so many of the weeks. I believe it's the better choice for our curriculum, but these proposals are suggesting many huge revamps. I wouldn't want people to underestimate how much time it takes to do well and get stressed out.

They key thing for me is that this week has never been a success with anyone that I've spoken to in our community. It's difficult to figure out people's feelings on the proposal without physically being in FAC to speak to people about it. So I'm just hoping that I will get a better sense after the discussion has started tomorrow or we take a straw poll on the 2 options. It's far from ideal, but there's no real time to do anything else :sweat: 

What do you think @eliascodes?

**Comment by eliascodes** [comment]
@jsms90 fair. I think in practise, only some of the proposals will be actioned for FAC11, even if they're "passed".

I think in future we it could be worth separating out proposals for sweeping changes that may take several FACs to implement properly from those that are incremental improvements that can be done immediately. Anyway, OT.

**Comment by jsms90** [comment]
@eliascodes I intend us to spend the next cohort raising issues as we think of them. This would give everyone enough of a chance to discuss a topic thoroughly. Then, by the time the curriculum planning session comes round, we would have more fully formed proposals, and a better idea of what the consensus was :+1:

**Comment by jsms90** [comment]
Feedback I just found on "Auth week" from the peer review:
> It’d be good for them to understand the pros and cons of a stateful (i.e. cookies with server managing sessions) session management vs a stateless (i.e. JWT) session management, and what each should and shouldn’t be used for. On our cohort the impression I got was that JWT was just the new way to do sessions and you could forget about stateful sessions, which was no doubt not the intent, but anyway.

If these were the intended learning outcomes, did any cohort feel like this was achieved in week 8 of their cohort? :sweat_smile: 

@eliascodes How do we actually teach this? Help?

**Comment by ronanyeah** [comment]
@jsms90 I am willing to take on the creation of any necessary resources for a vanilla Node.js auth week.

**Comment by jsms90** [comment]
@ronanyeah Would be happy to join you :grin: But I would say that it has to at least be some kind of joint effort with mentors, considering they're the ones that have to deliver it. Otherwise they will be delivering material that is just handed to them, that they don't feel familiar with or confident about, or have any ownership over.

**Comment by ronanyeah** [comment]
@jsms90 Well of course, it will be on github, there will be collaboration in as much as people are willing to put the time in. If there is an issue with lack of learning resources, those can be created. I don't want the learning outcomes of the first 8 weeks to be decided by inertia.

**Comment by ronanyeah** [comment]
What does mentors and 'ownership' mean? There are three campuses now with new mentors every few months. Either the resources satisfy the learning outcomes, or they do not.

**Comment by jsms90** [comment]
@ronanyeah
> What does mentors and 'ownership' mean

Very good question.

### Mentors
`mentors` = "members of the previous cohort"

What their _remit_ is? ...That's less clear.

Essentially the current curriculum planning days being given to FAC10, FACN1 & FACG1, as well as this afternoon's meeting are an attempt at answering that question.

But this is still coming up so frequently, that I think it deserves it's own issue. #277

### Ownership
See #205
which resulted in #271 (see the checkboxes in that issues, for how I intended to record it)
which has started being recorded in PR #272 

Owner = FAC or original author (defined by where the resource is kept i.e. under `foundersandcoders` or the individual's profile)
Maintainer = someone with [these responsibilites](https://opensource.guide/best-practices/)


But I think that a mentor's remit is still being defined.

**Comment by ronanyeah** [comment]
@jsms90 So how does that all relate to the creation and teaching of auth resources? Please try to be concise.

**Comment by ronanyeah** [comment]
1. It seems to be in agreement that auth should be taught in vanilla Node.js.
2. There are no/limited current resources.
3. Therefore they should be created.
4. They will then be used in the next cohort(s).

Am I missing something?

**Comment by jsms90** [comment]
I was purely answering the question that you asked :sweat_smile: You tell me how it's related :wink: 

Whether mentors (the previous cohort) have autonomy over the curriculum's content = directly related to 
> @jsms90 I am willing to take on the creation of any necessary resources for a vanilla Node.js auth week.

Ownership, or rather maintenance, of an existing repo = directly related to
> There are three campuses now with new mentors every few months. Either the resources satisfy the learning outcomes, or they do not.

**Comment by ronanyeah** [comment]
@jsms90 So the resources/week layout won't simply be in [the coursebook](https://github.com/foundersandcoders/master-reference/tree/master/coursebook) and be maintained by the organisation/mentors/whoever?

**Comment by jsms90** [comment]
Let's have this chat in #277?

**Comment by mcelearr** [comment]
I'm slightly biased because I had two good Oauth experiences, 1st when learning then 2nd when teaching. But I think you're right that important topics such as authentication, session management and security get brushed over. If we can find mentors that are willing to take on the task of making the changeover happen, I think there could be a lot of value. I mean, I've been working for 9 months and I'm sure I'd learn a lot if I sat in on that week!

Only thing in the back of my mind. Does not knowing Oauth make a difference to employability/ the ability to carry out cool projects at the end of the course?

**Comment by jsms90** [comment]
@mcelearr I was always told that you would never actually do all of the steps the we cover them in week 8, for yourself. Especially with hapi, you would just use [bell](https://github.com/hapijs/bell). But like anything, if you're going to implement it, you should understand how the process actually works. I

I'm sure I'm not the best person to answer whether OAuth is essential for employment. But I feel pretty confident that it can't be as essential as the other things on the list. Particularly the list in option 2.

**Comment by ronanyeah** [comment]
@mcelearr 
> Only thing in the back of my mind. Does not knowing Oauth make a difference to employability/ the ability to carry out cool projects at the end of the course?

I think it could comfortably be cut from an employment/essential skills perspective. It's just another form of auth. Not a 'core web development technology' or suchlike.

**Comment by ronanyeah** [comment]
Like if students know cookies, JWTs, route protection, password hashing and user storage solidly, they can figure out OAuth when/if they need it, and indeed, with the support of the wider alumni network.

**Comment by eliascodes** [comment]
Just FYI, the error handling workshop already has something that looks a bit like server-side validation. It's currently a stretch goal exercise, and is a bit de-emphasised.

**Comment by jsms90** [comment]
Proposal passed at the Summer Cohort Curriculum Planning meeting, and a new Authentication week being created in issue #305 :tada: 

See minutes for details
