### ISSUE TITLE
Ideal week structure

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#27]
A lot of issues were raised about the curriculum week structure by FAC9 in #18. It can be found inside https://github.com/foundersandcoders/master-reference/blob/master/curriculum.md

I think this is something we should treat as high priority to discuss and resolve prior to further curriculum planning as it effects the way mentors organise their weeks.

Points raised:

* Team retrospectives should be on Friday, after presentations.
* Show & Tell should be done through gitter channel, not scheduled into week.
* Whiteboard walkthrough should be before the start of projects.
* Weds morning challenge must prepare students for the project or be abandoned.
* Internal code reviews shouldn't be scheduled but expected as a good practice.
* Business development and community engagement need to be fit into one slot, potentially in alternation.

**Comment by bradreeder** [comment]
Related: https://github.com/foundersandcoders/business/issues/116

**Comment by jsms90** [comment]
I feel strongly about us putting some concrete timings down, especially as we are trying to fit more than ever before into each day. [This has been implemented by some mentors](https://foundersandcoders.gitbooks.io/fac9/content/week1/) and tends to make for a better student experience when communicated clearly.

The following is a first draft, based on what's in the curriculum file right now & the points raised by FAC9. @Cleop As our resident timings guru, I'd love you to weigh in with your thoughts!

Monday:
10:00-10.15 - Introduction to gitbook, learning outcomes **& project teams**. Start each week with a mission and a goal.
10.15-1:00 - Workshop 1
--LUNCH--
2:00-4:00 - Workshop 2
4:00-6:00 - Business Development / Community Engagement

Tuesday:
10:00-11:00 - Morning Challenge
11:00-12:45 - Workshop / Whiteboard walkthrough
12:45-1:00 - Introduce readme topics, assign names on whiteboard (jigsaw)
--LUNCH--
2:00-4:30 - Write readmes
4:30-5:30 - Present readmes
5:30-6:00 - Project introduction

Wednesday:
10:00-11:00 - Morning Challenge
11:00-1:00 - Group project
--LUNCH--
2:00-6:00 - Group project

Thursday:
10:00-1:00 - Group project
--LUNCH--
2:00-5:00 - Group project
5:00-6:00 - External speaker

Friday:
10:00-11:00 - Code Review
11:00-1:00 - Respond to issues  (Personal suggestion: finish responding to issues at 12:40, allow 12:40-1:00 for planning presentations)
--LUNCH--
1:00-2:00 - Group s-g-c
2:00-3:20 - Presentations (20 mins per group)
4:20-5:00 - Team s-g-c (punchier team s-g-c)
5:00-6:00 - Upstairs Project demo

**Comment by bradreeder** [comment]
@jsms90 Thanks for starting this 👍 

Few points:

* Was the consensus that whiteboard walkthrough should be on weds morning?
* It's still in discussion as to whether Business development and Community Engagement are one or two slots. See #38 and https://github.com/foundersandcoders/business/issues/116
* We need to resolve the readme issue #17 to know how much time will need to be set aside for it.
* My personal preference is one external speaker per week, but given we're shooting for two only run upstairs project demo's on weeks when one external speaker is arranged.

**Comment by Cleop** [comment]
@jsms90 Do you think it's realistic to get morning challenges done by 11am? I'm not against it but just going from previous experience...

**Comment by msachi** [comment]
@jsms90 @Cleop I think Weds morning challenges should indeed be kept to < 1 hour and be relevant for our projects, otherwise they shouldn't happen on Weds. Alternatively, if we're changing the structure of readmes then we might be able to cover the 'project prep' material there and wouldn't need them?

**Comment by Jwhiles** [comment]
@Cleop I think the morning challenges tended to overrun people often didn't start on time, because the explanations would tend to take quite a long time.

We could try this structure.

10:00 -> 10:40 - do the challenge
10:40 -> 11:00 - explanation

**Comment by sofer** [comment]
@bradreeder @jsms90 I am happy for now to stick with a single two-hour slot for business development.

I would suggest swapping the external speaker slot to a Wednesday, just because Thursday tends to be the time of the week when people are feeling under most pressure to get their code working.

I also agree that two slots (Wednesday and Friday) could be shared between graduate demos, alumni and employers. I will be amazed and delighted if we really manage to fill all of those.

**Comment by jsms90** [comment]
@bradreeder Do we have a final conclusion on the ideal week structure, that every team can then make sure they are following (as closely as possible)?

**Comment by bradreeder** [comment]
@jsms90 My understanding is we agreed upon what you outlined [here](https://github.com/foundersandcoders/master-reference/issues/27#issuecomment-267200575) at the start of last week? I haven't spotted any significant deviations so far, except in occasional possibly exempt situations, but will continue to catch them in review phase.

**Comment by jsms90** [comment]
What about this?
> Was the consensus that whiteboard walkthrough should be on weds morning?

Do we put @Cleop 's suggestion for the morning challenge into the timetable, so that it is followed by all mentors?
> 10:00 -> 10:40 - do the challenge
> 10:40 -> 11:00 - explanation

What about Dan's suggestion:
> I would suggest swapping the external speaker slot to a Wednesday, just because Thursday tends to be the time of the week when people are feeling under most pressure to get their code working.

We have been planning week 1 as though the external speaker (in our case, Mark's talk on F&C values) is on Thursday.

**Comment by bradreeder** [comment]
woo woo woo! :DDD

@jsms90 How about 

Tuesday:
10:00-11:00 - Morning Challenge
11:00-12:45 - Workshop
12:45-1:00 - Introduce readme topics, assign names on whiteboard (jigsaw)
--LUNCH--
2:00-4:30 - Write readmes
4:30-5:30 - Present readmes
5:30-6:00 - Whiteboard Walkthrough

Wednesday:
10:00-11:00 - Morning Challenge
11:00-11:30 - Introduce Group Project
11:30-13:00 - Project planning
--LUNCH--
14:00-17:00 - Group project
17:00-18:00 - External speaker

No external speaker Thurs

Rationale:

1. Whiteboard walkthrough makes more sense to be after readmes in case any subjects need clarifying + revisit learning outcomes before start of project.
2. Introducing the project then coming in to do a morning challenge is a bit odd as you probably are more keen to get started at that point? May as well introduce the project and then go straight into project planning.

**Comment by bradreeder** [comment]
Closed #76
