### ISSUE TITLE
how much autonomy do mentors have over the curriculum?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#277]
"**mentor**" is a term used throughout the `master-reference`. The one part that is unambiguous is that it means "member of the previous cohort"

But what their _remit_ is? ...That's less clear.

**It sounds like the degree of autonomy that mentors actually have over the curriculum's content, has never been properly defined.** Is that fair to say?

I don't _quite_ understand how much autonomy each cohort has actually been given in the past. But it sounds like it has varied, depending on how involved the wider community has decided to be.

Each cohort seems to always have been expected to create the gitbook. For example, [the FAC9 planning repo](https://github.com/FAC8/FAC9-planning/blob/master/gitbooktutorial.md) in the [`FAC8` organisation](https://github.com/FAC8). But were they given autonomy over deciding the content? Or is it simply their repsonsibility to write it down and then deliver it?

I can tell you that [this feedback process](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/curriculum-feedback-process.md) was used during the creation of the `master-reference`. @bradreeder helped us to review and incorporate [feedback from the wider community](https://github.com/foundersandcoders/master-reference/issues/10), but you can see from the [plan for the afternoon](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/curriculum-feedback-process.md#curriculum-feedback-day) that my cohort pretty much had autonomy after that.

We did actively ask for some oversight from alumni, but if I remember correctly, there weren't many volunteers. To be fair, it's obviously very time consuming. So I may be wrong, but I think that only 2 weeks actually had this? The 2 that I know about were both from @sohilpandya? You can see in the issues for week 2 #16 & week 6 #32, that they were very much asking for and using his help.

Essentially the format of the curriculum planning days being given to FAC10, FACN1 & FACG1, including this afternoon's meeting are an attempt at answering that question.

**Comment by ronanyeah** [comment]
How does the 'last cohort' having ownership over the curriculum reconcile with multiple campuses using SAME curriculum?

**Comment by jsms90** [comment]
From https://github.com/foundersandcoders/master-reference/issues/263#issuecomment-304826485:
> So the resources/week layout won't simply be in the coursebook and be maintained by the organisation/mentors/whoever?

When no one is accountable, either time gets wasted on things which aren't high priority or nothing gets done at all. [Case in point](https://github.com/foundersandcoders/our-site)

When people don't know what they are allowed to do, either nothing gets done, or worse - conflict can arise, feelings get hurt, and the sense of community is damaged.

Clarity of contributing process is key to [building a community](https://opensource.guide/building-community/) around any open source project.

**Comment by jsms90** [comment]
> How does the 'last cohort' having ownership over the curriculum reconcile with multiple campuses using SAME curriculum?

Maybe you would be interested in the conversation around [Nazareth's divergence](https://github.com/foundersandcoders/master-reference/issues/163)?

**Comment by ronanyeah** [comment]
I guess I'm just concerned it is replacing one form of inertia with another, but yes, the process sounds good.

As someone with a vested interest in the Gaza FACs progress, the divergence question is important to me but I am idealistically hoping that we can hammer out a high quality 8 week curriculum that is internationally relevant, one that (assuming all pre-requisites have been achieved beforehand) succeeds in achieving the desired learning outcomes. But that may be naive...

**Comment by eliascodes** [comment]
The new [curriculum planning process](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/curriculum-update-process.md) addresses this by bringing responsibility for making change recommendations under the master-reference maintainers. This is consistent with the recent preference to allowing students to spend more time preparing to be mentors and less time dealing with curriculum updates.

If anyone feels this doesn't fully address the issue, feel free to re-open.
