### ISSUE TITLE
Curriculum gitbook template

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#28]
If we are moving the curriculum to the master-reference we need to ask whether we need to create a gitbook for each iteration anymore and instead have one resource inside the master-reference. 

* Should it be a gitbook?
* If not, how should we structure it to be easily navigated and accessible?

If it's going to be in the master-reference, me and @des-des need to come up with a template including how each week should be structured in advance of curriculum planning. That way mentors will have a common guideline to follow.

**Comment by bradreeder** [comment]
Issues related to the gitbook were the highest priority issue for FAC9 #18. Main points:

* Gitbook should be well prepared in advance, to a similar standard across weeks.
* It should contain specific timelines for the days of the week, rather than lists of workshops. Gone over at start of each day.
* A clear context around the subject at the start of each week, alongside learning outcomes. e.g. What is a server? Why hapi vs. express?
* Revision keypoints you should be able to implement yourself in the learning outcomes.

**Comment by des-des** [comment]
@bradreeder Sounds good.

Also I would be happy to just have one (large) markdown file per week, not sure we need a gitbook? I have not used one before do not really have a valid opinion. (does a gitbook need its own repo?)

**Comment by jsms90** [comment]
Personally, I see no value in having a cohort-specific gitbook in addition to the master reference. Either the gitbook would be a copy of the master reference in a slightly different format - in which case, mentors would have to keep both up to date and identical in content - or the gitbook would deviate from the master reference for each cohort, making the master reference somewhat redundant.

Am I missing something?

**Comment by bradreeder** [comment]
@jsms90 Not at all, the only immediate nag I can think of is that if there is only a single gitbook/curriculum resource within the master-reference that gets updated each iteration to reflect the present curriculum then that means that the history of past curriculums will only be accessible through PR/issue histories. 

To me the curriculum must be contained here. What's on my mind more is the question of whether the curriculum should be a gitbook or simply a set of `md` files. I think it's important that it's presentation be clear, accessible, and easily navigated, which gitbook provides an interface for. 

On the other hand, gitbook is a pain in the $&@

**Comment by jsms90** [comment]
I imagine that the number of times you may want to consult a past curriculum (e.g. to refer to after graudation) will be relatively minimal. If the reference is worth having for alumni, then it may be worth retaining for future cohorts? In the event where it is worth looking back on, but not worth keeping in the curriculum, I think that github's history should suffice. This won't just be PR/issue history, but in the history of each file itself.

Whilst I completely agree that a gitbook is superior from a UX point of view ;), that doesn't matter if it doesn't get used or updated. If past experience is anything to go by, we need to reduce the burden on mentors of keeping documentation up-to-date :+1:

**Comment by bradreeder** [comment]
@des-des Let me know if you have any criticisms, otherwise I plan to do this over the next few days. Our consensus seems to be to not use gitbook, so we can use a folder structure of md files instead.

The general structure I have in mind is:

Curriculum folder:
* Can contain a md file for each general file unrelated to a specific week (curriculum overview, code reviewing, week structure template, etc.)
* Can contain a folder for each week. Each week will follow the same template containing a md file for learning outcomes, list of workshops, etc, like the gitbooks.

I have a feeling the archive of past workshops for each week should be separate from the curriculum folder, or the list of resources there could become overwhelming for current students. The curriculum folder could be updated each iteration by mentors to reflect what they will teach that iteration.

**Comment by des-des** [comment]
@bradreeder Yes, this sounds good.

Not sure about the necessity of a folder rather than a file per week but basically this sound fine.

**Comment by bradreeder** [comment]
Closed #51 .
