### ISSUE TITLE
Replace Natalia's git workshop with Piotr's git workflow workshop for two

### ISSUE THREAD

**Issue by Samatar26** [foundersandcoders/master-reference#286]
In week 1's SGC, FAC10 expressed an interest of the git flow workshop being more team-based. FACN1 also believes that the git workshop should have been done on a student's project, which I believe is solved by the git workflow workshop for two as you are editing a webpage.

**Comment by jsms90** [comment]
Just so anyone from Nazareth looking at this knows, this is the workshop https://github.com/foundersandcoders/git-workflow-workshop-for-two

**Comment by jsms90** [comment]
@Samatar26 @PiotrBerebecki Are you considering this workshop to be finished, or is there more work still to go into it?

**Comment by jsms90** [comment]
@Samatar26 @antoniotrkdz Still need to update the link in the week schedule :+1:
