### ISSUE TITLE
Week 6 - Refactor PostgreSQL installation instructions

### ISSUE THREAD

**Issue by macintoshhelper** [foundersandcoders/master-reference#288]
## Day 1

- Improve PostgreSQL installation instructions by adding command line Mac instructions (copy/paste using Brew).
- Test Linux instructions and maybe cover services and make instructions more copy/pasteable to save time.
- Windows instructions

**Comment by eliascodes** [comment]
Possibly worth thinking about whether to tell Linux users to change their `pg_hba.conf` file to allow them to run `psql` without `sudo`.

**Comment by jsms90** [comment]
https://gist.github.com/jsms90/edefc7cea007f71836c454e1893042d8

**Comment by pbywater** [comment]
https://github.com/dwyl/learn-postgresql/issues/41 - Attempted to update current instructions. No response so planning on updating the coursebook with this: https://github.com/macintoshhelper/learn-sql/blob/master/postgresql/setup.md

**Comment by jsms90** [comment]
@macintoshhelper @pbywater is this finished? Have you tested these setup instructions with anyone?

I assume that you need to make a PR to `master-reference` to link from the week schedule to these setup instructions?
