### ISSUE TITLE
Week 3: APIs

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#29]
This issue is intended for usage by mentor's who get assigned to API week and for discussion around the week. As a single source for S-G-C notes and FAC9 feedback, discussion, external feedback, and to commit their work against for review.

**Comment by bradreeder** [comment]
FAC9 feedback #18 :

* The project is too open-ended, add examples and ideas.
* Improve postman workshop with more context and instructions.
* Learning waterfall & parallel functions was useful, but Bes's approach was too heavy.

**Comment by Jbarget** [comment]
NB. CORS issues for this week

**Comment by bradreeder** [comment]
Week 3 S-G-C notes:

##### Stop

* Showing small code on screen
* Super open ended project, add examples and ideas.

##### Go

* Warn people against APIs that need backend in advance.
* Cover post request earlier.
* Have a mentor floating about downstairs during project.

##### Continue

* Bes's morning challenges, but make them shorter.
* Q&A whiteboard walkthroughs with Elias
* clearer instructions/time structuring
* more informative Gitbook
* discovering the difference between quality API through town projects

**Comment by eliascodes** [comment]
@emilyb7 @skibinska @lucymonie I don't know how far you've gotten with planning, just wanted to make you aware that I re-wrote the [reputation builder](https://github.com/eliascodes/Reputation-Builder) workshop you guys were given to focus on introducing some design and architecture principles in a client-side context (see [this repo](https://github.com/eliascodes/workshop-client-side-design)).

I wanted to trial it on FAC9, but apparently there's no time in the next few weeks, so if you think you'd like to include it in the curriculum for FAC10 (whether or not it's in week 3), let me know.

**Comment by emilyb7** [comment]
@eliascodes looks great 👍 we haven't done any planning at all yet!

**Comment by emilyb7** [comment]
Resources which we think will be useful:

- https://www.html5rocks.com/en/tutorials/cors/#toc-adding-cors-support-to-the-server
- eloquent JS chapter 11

**Comment by emilyb7** [comment]
Rough structure:

Monday:

- morning challenge (not too difficult, probably involving manipulating objects)
- intro workshop covering following topics:
-- json objects
-- different ways to query apis (browser, curl postman)
-- maybe the xhr workshop that we did?
- harder workshop, possibly implementing either waterfall or parallel function, depends what has been covered in week 2
- biz dev

Tuesday

morning challenge (harder than monday's, maybe parallel?)
hopefully workshop by @eliascodes ?
introduce projects

we don't want to do readmes this week, as we think the the workshops are really valuable

Wednesday - Thursday project

We will provide a shortlist of APIs that have been tried and tested by us. Students will be free to use other APIs if they want though...
We will also suggest a couple of defined ideas for the project so people can either pick one or come up with their own idea

Friday

normal stuff

@skibinska please feel free to make changes :)

**Comment by emilyb7** [comment]
We'll probably stick with the learning outcomes from our week 3 : https://foundersandcoders.gitbooks.io/fac9/content/week3/learning-outcomes.html

**Comment by lucymonie** [comment]
We'll go through the following resources and pick some to recommend as pre-reading for this week:

INTRO
- An introduction to APIs - https://zapier.com/learn/apis/
- What is an API? In English, please. - https://medium.freecodecamp.com/what-is-an-api-in-english-please-b880a3214a82#.8hjwc8zg1
- What is an API (Youtube video) - https://www.youtube.com/watch?v=s7wmiS2mSXY

REST
- REST and HTTP - http://restcookbook.com/Miscellaneous/rest-and-http/
- Concealing API keys when pushing to GitHub - https://gist.github.com/derzorngottes/3b57edc1f996dddcab25
- Best practices to build RESTful web services - https://www.infosys.com/digital/insights/Documents/restful-web-services.pdf

CORS
- https://www.w3.org/TR/cors/
- https://www.html5rocks.com/en/tutorials/cors/#toc-adding-cors-support-to-the-server
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by lucymonie** [comment]
For the object-based morning challenge, we thought we'd give them a massive JSON object to traverse and extract information to make a string or new object.

**Comment by bradreeder** [comment]
All looks fab.

* If you're wanting to not do readmes on Tuesday I believe the workshop @eliascodes created is designed to last morning and afternoon. It might be worth speaking with him to see if it fits your plans. The Tues morning challenge could always be moved to Weds.
* If they end up not being introduced earlier, I think this week could be a great opportunity to introduce user-stories, similar to how @nelsonic did with you. The open-ended nature of the project lends itself, as students can think about what kinds of problems they want to solve, get in the habit of breaking down into stories/features, etc.

**Comment by bradreeder** [comment]
Smashing! I don't think you have an assigned reviewer so just glancing over.

* If you're wanting to not do readmes on Tuesday I believe the workshop @eliascodes created is designed to last morning and afternoon. It might be worth speaking with him to see if it fits your plans. The Tues morning challenge could always be moved to Weds.
* If they end up not being introduced earlier, I think this week could be a great opportunity to introduce user-stories, similar to how @nelsonic did with you. The open-ended nature of the project lends itself, as students can think about what kinds of user problems they want to solve, get in the habit of breaking down projects into stories/features/components, etc. I think @eliascodes 's workshop talks briefly about user-stories so it could be adapted into that, and would be complementary.
* Not saying you have to cover these as you have a lot to cover, just to list things missing from curriculum overview: API standards, testing AJAX, chrome inspector, DOM api.

**Comment by emilyb7** [comment]
@bradreeder user stories might not be a bad idea, but we have soo much to fit in already. Not sure about the other stuff.

**Comment by emilyb7** [comment]
I just realised that if elias is taking over on tuesday we'll still need a plan for Nazareth...

**Comment by jsms90** [comment]
@lucymonie FYI the first the chapters of [Zapier's Intro](https://zapier.com/learn/apis/) is in their precourse material

**Comment by Jbarget** [comment]
@emilyb7 for those in Nazareth they can use @eliascodes's repo for the day

Also it looks like our weeks will be running Sunday to Thursday (to fit in with the local week) so Nazareth learning will be 1 day behind London. That means we can always ask @eliascodes for a brief of how things went in London and any topics of confusion to be aware of.

**Comment by emilyb7** [comment]
@Jbarget are you not one day ahead? or does the course start on a different day?

**Comment by Jbarget** [comment]
thats so funny, yes of course we're one day ahead 😆

**Comment by emilyb7** [comment]
:D then i look forward to your feedback on how our workshops went before i do them!

**Comment by eliascodes** [comment]
@Jbarget does that imply that you'll be running my workshop in Nazareth? Feel free to grab me if you want to chat about it.

**Comment by Jbarget** [comment]
@eliascodes not me specifically but one of us in Nazareth, nearer the time im sure someone will want to

**Comment by emilyb7** [comment]
Just for the record, APIs that I think are good:
- GitHub (getting publicly available information does not require oauth or an API key)
- Giphy
- AMDB (movie database)
- TFL

**Comment by lucymonie** [comment]
Here are the learning outcomes for someone to edit

## Core learning outcomes
### HTTP
- What is an HTTP request?
- What are HTTP methods and what does each one do?
- What is an HTTP status code and what are the most common ones?
- Do you understand the XMLHttpRequest object (at least in terms of the get method)?
### API
- What is an API? What is a REST API?
- How do you use xhr to query APIs?
- What is an API key?
- How would you conceal an API key?
- What is a JSON object? Why is this useful knowledge with regards to APIs and what does one look like?
### ASYNC
- Callbacks
- What is async?

**Comment by denesnori** [comment]
My version of the learning oucomes (I only made minor changes ):

## Core learning outcomes
### HTTP
- What is an HTTP request?
- What are HTTP methods and what does each one do?
- What is an HTTP status code and what are the most common ones?
- Do you understand the XMLHttpRequest object (at least in terms of the get method)?
### API
- What is an API? What is a REST API?
- How do you use xhr to query APIs?
- What is an API key?
- How would you conceal an API key?
- What is a JSON object? Why is this useful knowledge with regards to APIs and what does one look like?
### ASYNC
- Understand how and why we use callbacks
- What is async?
### PARALLEL
- How to write parallel functions?

**Comment by skibinska** [comment]
Maybe it is worth to add a resource about [Using XMLHttpRequest](https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest) ?

**Comment by skibinska** [comment]
My suggestion about resources:

**TOP RESOURCES**

1. XML HttpRequest - http://www.w3schools.com/xml/xml_http.asp,
2. What is an API? In English, please. - https://medium.freecodecamp.com/what-is-an-api-in-english-please-b880a3214a82#.8hjwc8zg1
3. What is an API (Youtube video) - https://www.youtube.com/watch?v=s7wmiS2mSXY
4. An introduction to APIs - https://zapier.com/learn/apis/
5. Concealing API keys when pushing to GitHub - https://gist.github.com/derzorngottes/3b57edc1f996dddcab25
6. An intro to CORS from Nicholas Zakas - https://www.nczonline.net/blog/2010/05/25/cross-domain-ajax-with-cross-origin-resource-sharing/ (this is short intro to CORS and I think it looks less complicated then the rest of our recommend CORS resources )

And the rest treat as additional.

**Comment by lucymonie** [comment]
## API week to-do list
**- Week intro: write intro to accompany learning outcomes**

**- Learning outcomes: edit and add to list**
Nori has finalised these
**- Workshops: Monday am (Ewelina/Lucy) & pm (Emily/Nori)**

**- Guardian talk: book Natalia et al for this one again**
Lucy contacted Natalia and she has pencilled in Friday 10 March for a talk and code review by Guardian people
**- Morning challenge: we need one for Wednesday**

**- Raise the issue of who will be conducting morning challenges for FAC10 (if Bes is not available)**
Emily
**- Project description: write up what we're expecting of them, and list of recommended APIs**

**- Someone to go through the resources list and check those are all really worthwhile, then add to resources page** 
Ewelina has gone through these and is happy with them.

**Comment by lucymonie** [comment]
### Outstanding API tasks
- Morning & afternoon workshops
- Week intro text
- Project description

**Comment by skibinska** [comment]
[list of open APIS](https://github.com/toddmotto/public-apis)

**Comment by jsms90** [comment]
@emilyb7 @lucymonie @denesnori Any reason for a morning challenge on Monday (and Tuesday):
> Monday:
> morning challenge (not too difficult, probably involving manipulating objects)

rather than Tuesday and Wednesday like the [ideal week structure](https://github.com/foundersandcoders/master-reference/blob/59ec9cb455d3a8520567c3ee62771af1a382e2ac/coursebook/general/week-schedule.md)?

**Comment by emilyb7** [comment]
@jsms90 that schedule is a bit out of date, please don't take it too seriously yet.

**Comment by lucymonie** [comment]
Monday:
10:00-10.15 - Introduction to gitbook, learning outcomes & project teams
Start each week with a mission and a goal.
10.15-13:00 - Workshop 1

--LUNCH--
14:00-16:00 - Workshop 2
16:00-18:00 - Business Development / Community Engagement

Tuesday:
10:00-11:00 - Morning Challenge
11:00-12:45 - Workshop 3
12:45-13:00 - Introduce research topics, assign names on whiteboard and jigsaw teams.
--LUNCH--
14:00-16:30 - Write research projects
16:30-17:15 - Present research projects
17:15-18:00 - Whiteboard Walkthrough + Introduce Group Project

Wednesday:
10:00-11:00 - Morning Challenge
11:00-13:00 - Project Planning
--LUNCH--
14:00-17:00 - Group Project
17:00-18:00 - External Speaker

Thursday:
10:00-13:00 - Group Project
--LUNCH--
14:00-18:00 - Group Project

Friday:
10:00-11:00 - Code Review
11:00-12:40 - Respond to issues
12:40-13:00 - Prepare Presentations
--LUNCH--
14:00-15:00 - Classroom S-G-C
15:00-16:20 - Presentations (20 mins per group)
16:20-17:00 - Team Retrospectives (Team S-G-C)
17:00-18:00 - External Speaker or Upstairs Project

**Comment by emilyb7** [comment]
Hey all,

Here's my first attempt at a workshop for Monday afternoon:

https://github.com/emilyb7/workshop-APIs/pull/1

I would love some feedback!

I've written a solution, which is currently on a different branch.

Two issues:

1. I would have liked to have included some tests in my solution, but I have no idea how to test API requests on the client side. If we learnt to do this, I've forgotten everything. I feel like I should find out how before teaching FAC10. Can anyone help?

2. When starting out with this I was convinced that GitHub had a relatively high rate limit. Today I found out it's only 60 requests per IP per hour. That's quite low. We could get 120 requests per hour if we spread students out across the available WiFi networks. If we reach the limit, we can work around the problem by getting people to create an access token. This is obviously not very safe, but for a locally-run application it should be fine, right? Does anyone have any serious misgivings about this?

**Comment by lucymonie** [comment]
Nice @emilyb7 ! I spent today converting a front-end API project to back end so I could use an API key so I am feeling pretty comfortable with API requests on the client side - I'd be happy to go through this with you. On the issue of the github rate limit, I think that is a slight issue but we can make it part of the learning. They can each make one call to the API, then save the dummy object they get back and use it to construct the rest of their code. 

I found an [API workshop](https://github.com/guardian/my-guardian-workshop) on the Guardian's Github - it might be possible to modify it for FAC10's morning workshop. I'm going to take a look at it and see whether it looks suitable. I think it uses bootstrap so it may be more work than it's worth!

**Comment by emilyb7** [comment]
@lucymonie the Guardian workshop also uses jQuery and doesn't really explain how to make a request, so yes it's probably a lot of work. But I like their simple idea and I'm sure it could be combined with the existing XHR workshop we have in the FAC9 gitbook!

**Comment by denesnori** [comment]
I will do the workshop tonight. :) and then post my comments.

**Comment by lucymonie** [comment]
Hey @emilyb7 you commented above that you thought Eloquent Javascript chapter 11 could be useful. Just wondering why? I was just flicking through EJS last night (light bedtime reading) and I was struck with the usefulness of chapter 17, which covers HTTP. I think we should add it - it's wonderful.

**Comment by emilyb7** [comment]
@lucymonie yeah, i meant the http chapter! Not sure where the mix up with the numbers came from 😃

**Comment by emilyb7** [comment]
Looking back at at: https://foundersandcoders.gitbooks.io/fac9/content/week3/project.html

I had forgotten that we were told we could set up a simple http server in order to get round problems with cross-origin. Did anyone actually use this on our cohort? 

Should we leave this info in?

Unless anyone has strong objections, I would suggest we take it out as it's a bit confusing and not really necessary.

@skibinska @denesnori @lucymonie what do you think?

**Comment by sohilpandya** [comment]
@emilyb7 couple of others that we've used in the past on top of what you've mentioned above:
- SoundCloud
- guardian
- [Gov Data](http://explore.data.parliament.uk/?learnmore=e-Petitions)
- [Game of Thrones](https://anapioficeandfire.com/) 😉 

I'm also going to be attending the Science Museum Hack this week and will let you know if it's usable by the current FAC. Could be a good one to interact with.

**Comment by msachi** [comment]
@emilyb7 the APIs that the teams I've been part of have used successfully:
- Random image generator ([Unsplash It](https://unsplash.it/))
- Image recognition ([Microsoft Computer Vision](https://www.microsoft.com/cognitive-services/en-us/computer-vision-api)) - and NOT Google's image recognition
- News ([Guardian](http://open-platform.theguardian.com/))
- Song database ([musixmatch](https://developer.musixmatch.com/)) - but only for titles, lyrics etc., not for actual media
- Recipe search ([Recipe puppy](http://www.recipepuppy.com/))
- Grocery search ([Tesco](https://devportal.tescolabs.com/))

**Comment by lucymonie** [comment]
- [Newsapi](newsapi.com) (multiple news sources)
- [Giphy](giphy.com) (gifs)
- [Fun translations](http://funtranslations.com/api) (pirate speak, yoda etc)
- [Wunderground](wunderground.com) (weather)

**Comment by lucymonie** [comment]
Hey @emilyb7 I just noticed that Postman has a testing feature - might be worth checking out. http://blog.getpostman.com/2014/03/07/writing-automated-tests-for-apis-using-postman/

**Comment by emilyb7** [comment]
@lucymonie not going to include fun translations as the rate limit is 5 calls per hour and i don't think that's enough, unless you know of a free plan or something?

**Comment by sohilpandya** [comment]
## This looks to be a winner in terms of testing AJAX calls using qunit and sinon

**Comment by eliascodes** [comment]
@sohilpandya is mocking going to be introduced to them as a concept by this time? I'm not covering it my workshop.

**Comment by sohilpandya** [comment]
I am not sure if this will be introduced at this point of the course.... just something to potentially look into.

**Comment by eliascodes** [comment]
Hey week 3 peeps, could I ask a favour of you (if you have the time).

Could you take another look through my workshop, try to put yourself in FAC10’s shoes, and have a think about the following questions:

1. After each exercise, I was going to do a review of their answers. There are also two sets of example solutions to the workshop. Would it be a good idea to compare their answers to the examples as we go along, or should I leave this for them to do after the workshop? I thought the former option might be overwhelming, but I’d like to hear what you think.

2. Do you think I should try to talk through each explanatory section (i.e. any section that isn’t an exercise), or should I just let them read it by themselves and then ask questions if they want?

If you have any other thoughts, it would be good to hear as well.

**Comment by skibinska** [comment]
@eliascodes I will have a look at it over the weekend.

**Comment by sohilpandya** [comment]
@skibinska do you still need me to do the morning challenge?

**Comment by emilyb7** [comment]
In the end we did this morning challenge instead of the one in the MR:

https://github.com/emilyb7/parallel-challenge-github

Will make PR regarding for this later...

**Comment by bradreeder** [comment]
Week delivered. Thanks everyone!
