### ISSUE TITLE
Week 6 - pg module workshop

### ISSUE THREAD

**Issue by pbywater** [foundersandcoders/master-reference#290]
Lots of people in our SGC said they'd prefer to have [this](https://github.com/foundersandcoders/pg-walkthrough) as a codealong so we plan to do that instead

**Comment by jsms90** [comment]
@macintoshhelper How far along are you with this? Have you made a video so that this can be replicated in other campuses?

**Comment by jsms90** [comment]
Sorry @m4v15 @mattlub I'll be speaking to the other mentors of this week today and trying to get something together. Perhaps over the weekend.
