### ISSUE TITLE
Week 6 - Replace pgexercises with another workshop in schedule

### ISSUE THREAD

**Issue by macintoshhelper** [foundersandcoders/master-reference#291]
## Day 1

- People found that the pgexercises weren't very helpful
- We want to replace this with a simple introduction workshop doing a similar job: https://github.com/foundersandcoders/sql-commands-intro

**Comment by jsms90** [comment]
@macintoshhelper The https://github.com/foundersandcoders/sql-commands-intro repo is empty and there are no comments in this issue. What's happening here?

**Comment by jsms90** [comment]
@macintoshhelper @ConchobarMacNessa @pbywater 
In [FAC10's week 6 SGC](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-6.md#stop), one of the comments was
> ### Stop
> + Workshops that focus on using SELECT on simple DBs
>   + Less of a jump between difficulty of workshops to difficulty of projects?

This  [SQL commands repo](https://github.com/foundersandcoders/sql-commands-intro) has a lot of crossover with the first challenges of the [the afternoon workshop](https://github.com/foundersandcoders/postgres-workshop).
