### ISSUE TITLE
Week 6 – refactor db morning challenge

### ISSUE THREAD

**Issue by ConchobarMacNessa** [foundersandcoders/master-reference#294]
We propose refactoring the [db morning challenge](https://github.com/foundersandcoders/db-morning-challenge)
Some of us misunderstood the questions, so these could be reworded for clarity. 
We should also make sure that questions have expected outputs.

**Comment by eliascodes** [comment]
Assuming this was done by foundersandcoders/db-morning-challenge#21 and foundersandcoders/db-morning-challenge#24
