### ISSUE TITLE
Week 5 - background reading

### ISSUE THREAD

**Issue by joeylouise** [foundersandcoders/master-reference#302]
We thought we should introduce the concept of streams before any workshops i.e. weekend reading, so that students are at least aware of the concept, and it will be covered in workshops as well

**Reading**
https://www.sitepoint.com/basics-node-js-streams/

**Video**
https://www.youtube.com/watch?v=WQ-LLAvFKqc&t=293s

**Comment by bradreeder** [comment]
@joeylouise I'd probably advise against weekend reading unless we get a chance to discuss it as a cohort. Only because I'm aware it has come up as a topic in your stop-go-continues, with mixed opinions for and against.

**Comment by joeylouise** [comment]
@bradreeder the idea is that they have a look at a short article and video if they have the time, so that the concept is introduced before the week - the material will be covered during the week so it doesn't matter if they don't have the time to go through it

**Comment by majakudlicka** [comment]
After comments from @bradreeder and @jsms90 we have decided against weekend reading and instead added extra resources to resources directory for this week. PR #497

**Comment by majakudlicka** [comment]
Let me know if we're comfortable closing this.
