### ISSUE TITLE
Week 1 - Change CSS gallery challenge to a challenge on responsive design 

### ISSUE THREAD

**Issue by Samatar26** [foundersandcoders/master-reference#309]
Since the students have been set the 'Learn layout' course/video in the pre-course material, it would make more sense to have a morning challenge where they can learn the basics of making a responsive website instead of a challenge on how to position things. Going through the student's websites and seeing that a lot of them don't display well on mobile, I believe this is something they could really do with.

**Comment by antoniotrkdz** [comment]
Issue raised on morning challenge
