### ISSUE TITLE
Week 5: Node 2

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#31]
This issue is intended for usage by mentor's who get assigned to Node core 2 week and for discussion around the week. As a single source for S-G-C notes and FAC9 feedback, discussion, external feedback, and to commit their work against for review.

**Comment by bradreeder** [comment]
Week 4 S-G-C notes:

##### Stop

* Readme presentations being so long + in depth
* Stop testing core functionality (don't test the obvious like HTTP module)
* lollipopping individuals (puts people on the spot)
* carefully targeted speakers (Make sure speaker is aware of the level of knowledge of the group)

##### Go

* presentation workshops, feedback on group presentations
* clarify what to test and not to test
* A more applied test workshop
* clarify callbacks in week 3 in advance of week 4.

##### Continue

* step by step workshops like Nodegirls
* explaining new things like you've never heard of them before
* well thought of projects
* node shell workshop!
* Adjusting timings based on our needs without sacrificing the content of the week
* resources few enough to feel manageable
* Present on Monday
* Make event loop video mandatory (maybe watch over weekend in advance?)

**Comment by njsfield** [comment]
@marisid @stevehopkinson @SavageWilliam would it be okay if we joined your issue thread for a bit just to decide on differentiating content between week 1 & 2, so we can then solidify what to explore in week 2?

**Comment by SavageWilliam** [comment]
@njsfield Absolutely. I was thinking about the best approach for deciding upon what workshops/readme topics/morning challenges to include across the two weeks... considering that we only had 1 week of 'core node'.

[backwards design](https://en.wikipedia.org/wiki/Backward_design) comes to mind. If we agreed on two solid projects (which build upon each other) and then consider all the tools and knowledge required to complete them? We can then focus on some really great 'learning events' and then fill in any gaps with background/supporting knowledge using exercises such as @bradreeder's wonderful nodeshell workshops etc.

**Comment by stevehopkinson** [comment]
@njsfield @SavageWilliam Backward design makes sense, although I think we should work backwards from the *learning outcomes* rather than the projects - after all, the projects are only there to help us achieve the learning outcomes, rather than the other way around.

**Comment by Jwhiles** [comment]
# Learning Outcomes

## NODE 1
- What is node
- Node / Core Modules / package.json
- Module Patterns
- Tape
- NPM
- Linting (????)
- Making a server
- Tape

## NODE 2
- Continuous Integration
- Node Debugger
- Error Handling / async Error Handling
- TDD server - introduce shot
- Securing the back end
- Stream / Buffers
- Make Requests from Node

# Projects

## NODE 1
Autocomplete

## NODE 2
a news feed project, 3 options

# Structure

## Node 1
- Weekend
  - Node installation (or come in early on monday)
  - Event loop video
  - ES6 resource
- Mon
  - 10:00 - 13:00
    - Intro to servers and Node
    - Code Along
  - 14:00 - 16:00
    - Tailored Node Girls workshop (without CMS)
- Tue
  - 10:00 - 11:00
    - Modularisation morning challenge)
  - 11:00 - 12:45
    - Tape Workshop
  - 12:45 - 13:00
    - Intro to readme topics + teams
  - 14:00 - 18:00
    - Readmes
      - npm modules (nodemon & linting)
      - Heroku & Env2
      - Core modules
      - module.exports & request/response objects
- Wed
  - 10:00 - 11:00
- Thu
- Fri

## Node 2
- Weekend
  - Event loop video
- Mon
  - 10:00 - 13:00
    - ES6 Morning Challenge
  - 14:00 - 16:00
    - Error handling workshop & testing for errors
- Tue
  - 10:00 - 13:00
    - Node shell work (streams, buffers, events)
  - 14:00 - 18:00
    - Readmes
      - Code Coverage
      - Continuous Integration
      - Securing the backend

- Wed
  - 10:00 - 11:00
    - Modularisation morning challenge
- Thu
- Fri

**Comment by SavageWilliam** [comment]
# Node Resources

[Learn Node](https://github.com/nikhilaravi/learn-node) **Week1-Mon-am**
- npm
- core modules
- server logic

[node-intro-workshop](https://github.com/bradreeder/Node-Intro-Workshop)**Week1-Mon-am**
- this is a version of 'Learn Node'.

[Node-Girls](https://github.com/node-girls/workshop-cms)**Week1-Mon-pm**
- we need to review this and fix the bug/come up with a similar yet alternative workshop.
Resources to use and build upon:

[Tape-testing](https://github.com/matthewglover/tape-testing)**Week1-Tue-am**
- include shot?

[modularise](https://github.com/sofer/sssk)**Week1-Wed-am**
- dans repo - can be used to make the web morning challenge

[node-shell](https://github.com/bradreeder/Node-Shell-Workshop/blob/master/LESSON1.md)**Week2-Tue-am**
- bradleys wonderful node shell workshop for week 2 tuesday!

**Comment by bradreeder** [comment]
See review here: https://github.com/foundersandcoders/master-reference/issues/30#issuecomment-271394880

**Comment by msachi** [comment]
** GitBook responsibilities ** 

Edit the files in [this repo](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/week-4))

- week schedule @msachi
- learning-outcomes @Jwhiles 
- project @RhodesPeter 
- research afternoon @njsfield 
- resources @msachi

** Workshop responsibilities ** 

Make your own repo / fork existing workshops, then add links to the [schedule](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-4/README.md).

- TDD Server & shot @njsfield 
- Error handling workshop & testing for errors @Jwhiles 
- Node shell work (streams, buffers, events) @msachi
- Build request module (morning challenge) @RhodesPeter

For all the above work, please fetch the branch `node2` and do all your commits there. We will then submit a single pull request to be reviewed by @bradreeder and others.

**Comment by njsfield** [comment]
To Clarify- 

We've been working on a seperate branch **week-4-node-2**, which should be week-5-node-2, but as it is seperate from the **week-4-node-1** branch we'll continue to work on the branch before reviewing, then for future revisions use a correctly named branch

**Comment by njsfield** [comment]
Also, updated Research Day point 4 to replace Event Emitter research with making server requests to another server. We felt that gaining a deeper understanding of the Event Emitter class in Node had little relevance to the project and was more optional knowledge than a required understanding.

We are instead requiring research into making requests from a server to another server with an **npm module**, so students will be exposed to modules that remove the heavy lifting of the task, before implementing a node-core-based solution in the following days morning challenge

**Comment by skibinska** [comment]
I don't know if you need this, but I  figured out how to make **code climate** to work.

1. Sign up to [code climate](https://codeclimate.com/)
2. Connect your repo with code climate
    * Settings -> Integrations and services -> Add service -> Add code climate token 
3. Add to .travis.yml
```
addons:
    code_climate:
        repo_token: TOKEN
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
```

**Comment by njsfield** [comment]
[Monday TDD Server with Tape/Shot Workshop Draft](https://github.com/njsfield/tdd-node-server-with-shot-and-tape)

**Comment by bradreeder** [comment]
Week delivered. Thanks @njsfield @Jwhiles @msachi @RhodesPeter !
