### ISSUE TITLE
Create architecture / planning workshop

### ISSUE THREAD

**Issue by edgarfinn** [foundersandcoders/master-reference#317]

**Comment by eliascodes** [comment]
Hey @edgarfinn @lucyrose93 @smarthutza 

How is this going? Do you need something from me while I'm still here? Where were you planning to put this workshop? I'm very open to having multiple versions of an architecture workshop in the existing in the current foundersandcoders/workshop-client-side-design

Please tell me if/how I can help 😃

**Comment by edgarfinn** [comment]
I think we're good for help thanks. @lucyrose93 can fill you in on the architecture workshop. Although it would be good to get you on the code review for these workshops since they're development / replacement for the stackexchange profile builder workshop. 

Timing-wise we planned to reduce this workshop down into two morning workshops, and keep them on Day 2 morning.

**Comment by jsms90** [comment]
@edgarfinn Could you provide a link to the workshop in this issue please?

**Comment by lucyrose93** [comment]
Almost finalised -- https://github.com/lucyrose93/Workshop-Software-Architecture-Design

**Comment by lucyrose93** [comment]
Approved and transferred to FAC: 

https://github.com/foundersandcoders/Workshop-Software-Architecture-Design
