### ISSUE TITLE
URGENT - Repo namespacing

### ISSUE THREAD

**Issue by ronanyeah** [foundersandcoders/master-reference#323]
I think if we're going to start cranking out resource repos into this organisation we need to start namespacing them. ie `ws-` for workshop, or `mc-` for morning challenges. It's already becoming messy.

**Comment by jsms90** [comment]
@ronanyeah If you would like to action this, I will happily support it

**Comment by ronanyeah** [comment]
`ws` and `mc` seem to be catching on so... done!

**Comment by jsms90** [comment]
@ronanyeah The vast majority of repos do not follow this pattern.

What problem does it solve?

**Comment by ronanyeah** [comment]
Its for workshops and morning challenges. Stops mess. It is a good idea.
