### ISSUE TITLE
Joint cross campus workshop[s]

### ISSUE THREAD

**Issue by shiryz** [foundersandcoders/master-reference#325]
Our 3 campuses currently teach, learn and modify the same curriculum, the expectation is they join forces and work together on the next version of it, but one problem is they haven't worked together before nor did anything remotely.
my suggestion is we have a workshop (could be a morning challenge) or multiple ones where the teams are a combination of students from different campuses (2 from Nazareth x 2 from London \ 2 from London x 2 from Gaza), the workshop can be given from one location and then people will split into pairs/ teams to work on it.
By the time they need to do curriculum planning they would've had some practice with working remotely.

**Comment by eliascodes** [comment]
Love this in principle, but keep in mind each campus' curriculum is offset by one week, which means this needs a bit of thought.

**Comment by jsms90** [comment]
@shiryz I would love to work out more ways to introduce the students of different campuses to one another, and build the feeling that there is a larger online FAC community that you can tap up for questions / advice / support, as well as your local one.

So this seems like a great point.

When would you suggest that students work on creating these morning challenges?

**Comment by shiryz** [comment]
@eliascodes was thinking more general concepts, for example we had this for fac9 https://github.com/otajor/regex-morning-challenge, it's more of a nice to have rather than you need to learn this in a certain week.
would you suggest projects instead of a workshop?, though I think it'll be harder to coordinate since students are still at a junior level.
I have worked on a mini project with a 6 people team remotely, we had some practice with small exercises before we dived into work on the project.

@jsms90, I know students are busy with the current planning so I'm not sure we can fit it in this time around, but I think we can manage to at least try it out, what do you think?

any suggestions are welcome :heart:, have been thinking about this for a while but couldn't figure out the specifics.

**Comment by rebeccaradding** [comment]
@shiryz I'm not sure we can pair our Nazareth and Gaza students just yet...still feeling out the politics of facilitating interactions between them. How would numbers work if we couldn't do that?

**Comment by shiryz** [comment]
I'm not sure about it either, for now it's better if we keep them separate so each can collaborate with London... at least till (and if) we get the green light to do it.

**Comment by jsms90** [comment]
Ohhhhh @shiryz you mean the "students" as in soon-to-mentors? I thought you were talking about FAC11 & FACN2 and I was thinking....
:thinking: I reckon being on the course is kind of enough, without organising your own morning challenges :sweat_smile: 

No, honestly, it does sound good. But as you say, it remains to be seen how much curriculum planning need to stay centralised next time, and how much local divergence we can enable.

Rather than replacing existing material, which has usually been designed with the coherence of the whole week in mind, perhaps we could open up a slot on Thursday mornings for an extra one?

**Comment by shiryz** [comment]
@jsms90 , Thursdays are full with code reviews and presentations, but if it's not going to be weekly then we can probably manage.
how about wednesdays where everyone is working on their projects, and we choose the weeks with one morning challenge?

**Comment by jsms90** [comment]
Sorry @shiryz, I meant Day 4

**Comment by jsms90** [comment]
What are you actually proposing here?

> By the time they need to do curriculum planning they would've had some practice with working remotely.

So are you talking about FACN2 & FAC11 collaborating on morning challenges, _while_ they are still on the course? It's a nice idea, but to be honest, I think that coming up with material while you're studying is a lot of pressure.

We definitely need a better solution for curriculum planning in multiple locations though!

**Comment by shiryz** [comment]
@jsms90 the idea is to team up remotely so they would solve something together remotely.
they'll be introduced to both remote working and the rest of the students (which they'll have to work with in order to make improvements to the curriculum).  
so fac11, facn2, facg2 or fac12, facn3, facg3 ...
I definitely don't expect them to come up with materials :stuck_out_tongue_winking_eye:

**Comment by jsms90** [comment]
But if they're not coming up with the materials, what are they working on remotely together? :confused:

**Comment by mattlub** [comment]
@jsms90 @shiryz @eliascodes how about all the cohorts create and maintain a resources repo with a simple markdown file containing links and brief descriptions. This would encourage resource sharing and collaboration between cohorts.

**Comment by jsms90** [comment]
@mattlub we could ask fac11 to move their existing one into `foundersandcoders` and encourage FACN2 to add to it? https://github.com/fac-11/notes

Do you think it's at all problematic that there's a week's gap between cohorts?

**Comment by shiryz** [comment]
@mattlub , yes that would be a good start :heart_eyes: .
@jsms90 do you think there might be repeatition or less of a contribution, since fac11 already wrote their notes?

**Comment by jsms90** [comment]
Tbh I'm not entirely convinced that this is the best place for students to be pouring their efforts, considering we haven't gotten collaboration on the curriculum itself right yet.

I would rather point people's collaborative efforts to the master reference, than dilute their attention by suggesting even more things they could / should collaborate to. I think `master-reference` and `<city>-curriculum` alone can easily become exhausting, so I'd love to ensure that whatever enthusiasm does exist gets pointed towards the curriculum itself.

But! What I _do_ love the idea of, is having mentors and/or older alumni writing extra morning challenges for delivery on Thursday mornings. Morning challenges, when treated as a fun hour in the morning, independent from the content of the week, are brilliant when delivered by alumni who have a little more experience & want to introduce an optional extra.

**Comment by shiryz** [comment]
closing this for now until we have more resources.
