### ISSUE TITLE
Week 2 - update resources file

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#326]
@oliverjam to find appropriate article(s) on callback to include in the week 2 [resources file](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-2/resources.md)

**Comment by oliverjam** [comment]
I may have been mistaken about there being another burger article for callbacks — I was probably just thinking of the promises one... I'll try to find another good callbacks resource.

**Comment by jsms90** [comment]
@oliverjam Where are we at with this issue?

Even if it's not this particular article, were you intending to add to / change the `resources.md` file https://github.com/foundersandcoders/master-reference/issues/364 before Monday?

**Comment by oliverjam** [comment]
@jsms90 I would like to add [this article on unit tests](https://medium.com/javascript-scene/what-every-unit-test-needs-f6cd34d9836d) and [this one on callbacks](https://www.sitepoint.com/callbacks-javascript/), but I don't want the resources to be so long that nobody reads them.

Is it okay to remove stuff that's already in there?

**Comment by jsms90** [comment]
@oliverjam nice
I don't think 5 articles is overkill, but I do hear what you're saying. This is currently one of the shorter resource files in the curriculum anyway :woman_shrugging:

**Comment by oliverjam** [comment]
I've made a PR that adds those two resources. If it doesn't get merged today I'll link them on Gitter too just so people have access to them
