### ISSUE TITLE
Week 2 - create readme on the TDD cycle

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#327]
DWYL's [`learn-tape`](https://github.com/dwyl/learn-tape) tutorial is replacing the [introduction with QUnit](https://github.com/dwyl/learn-tdd).

So there needs to be a replacement explanation of the TDD cycle

**Comment by oliverjam** [comment]
This is created. We needed to introduce the students to testing in general as well as TDD, as that was part of the QUnit workshop before.

https://github.com/foundersandcoders/testing-tdd-intro

This is a first draft so there are probably things that need to change. Probably best to raise content issues directly on that repo

**Comment by jsms90** [comment]
Agreed. I'm sorry, this was a bad way of dividing the issues if each explanatory readme is going to have its own repo.

It would have been better to link directly from the "epic" to the new repos, and added more bullet points to #346
