### ISSUE TITLE
Week 2 - add tasks for students to do in npm introduction

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#328]
+ add instructions that get students to install particular modules (test whether they have any `npm` problems

**Comment by oliverjam** [comment]
How does this look @jsms90 ?

https://github.com/foundersandcoders/npm-introduction

**Comment by oliverjam** [comment]
This can probably be closed. If there are any issues with the repo itself it would make sense to raise them over there

**Comment by jsms90** [comment]
removed the reference to submitting a PR, since this is going in #346 :+1:
