### ISSUE TITLE
Week 2 - create Roman Numerals code along

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#330]
In response to [this proposal](https://github.com/foundersandcoders/master-reference/issues/252)

Use [Roman Numerals workshop](https://github.com/foundersandcoders/romanizer) solutions branch for inspiration

+ [x] write learning outcomes
+ [x] add UI elements to combat confusion over DOM manipulation
+ [x] make screen-recording for future mentors to use in curriculum planning

**Comment by oliverjam** [comment]
I've got an initial solution done here: https://github.com/oliverjam/roman-numeral-tdd-codealong

I kept it separate from the original workshop for now as it feels like a different enough thing that it might be worth having a separate repo. @finnhodgkin is going to have a look at it and we'll see what tweaks need to be made.

Given that it's a code-along, would we still still link a repo to the students at the beginning?

**Comment by jsms90** [comment]
@oliverjam How about producing a screen recorded video of you completing the code-along? We could share this with other campuses, for mentors to use in order to practice?

**Comment by oliverjam** [comment]
@jsms90 Yeah I'll do a screen-recording at some point this week when I get a bit of time. My girlfriend is learning Python and has never done any testing so I'm planning on doing this as an actual code-along with her to practice before the real thing.

I've currently got the solution with every step of the TDD process in the file, with everything but the final version commented out. Is that a good way to present it or should I just have the final solution?

I tried to commit every step of the TDD process separately, so the repo's history is another way to see how TDD works.

**Comment by jsms90** [comment]
@oliverjam updated the top comment with checkboxes. Please fill in as you go :+1:

**Comment by oliverjam** [comment]
@jsms90 The screencast is done, but it's 2.5GB so processing and uploading is taking a long time. I'll post the YouTube link here and in the Readme of the repo once it's done.

**Comment by oliverjam** [comment]
It'll be live here within half an hour: https://youtu.be/7qEXPwG71RI

**Comment by jsms90** [comment]
@oliverjam I could kiss you for making this.

I've only watched the first 10 mins so far, but you explain every detail beautifully. This is going to be an excellent resource for future mentors to use when preparing :man_dancing:

Seriously, thank you for putting the time in! Code-alongs are time consuming to prepare in and of themselves, even when you don't have to worry about creating materials for other people to replicate it.

I'll watch the whole thing later :+1:

**Comment by m4v15** [comment]
Sorry for lack of input on this from Naz, been a very hectic month, and also only assigned weeks a few days ago...

Anyway, just did this, it is amazing, well done. I watched on 2x, didn't actually code along, but its really good and clear, a really nice introduction to workshops early on during FAC. Especially like the CSS focus at the end too!

Out of interest, how are you planning on delivering this next week? 

I imagine basically replicating this screen cast, except just you doing the initial set up, and then just following instructions from the cohort, prompting then if necessary?

I think FACN1 actually liked how it was delivered originally more than FAC10 did (i.e. pair programme workshop/morning challenge) but I think this is a really good way of introducing and cementing a lot of concepts (TDD, npm, CSS) in a thorough way, look forward to hearing the feed back from FAC11 next week.

**Comment by oliverjam** [comment]
@m4v15 I was planning doing it as a pure codealong, although asking the students to tell me what to do is a good idea. Might make it take too long though, as it's pretty much a solid hour already
