### ISSUE TITLE
Week 2 - write callback morning challenge

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#331]
The waterfall morning challenge implies that students already understand the concept of callbacks.

Create a morning challenge that instead introduces them to callbacks as a topic

**Comment by jsms90** [comment]
@des-des You had some helpful comments earlier. Do you have any useful tips?

**Comment by des-des** [comment]
To quote myself (roughly)

 > Its all about control flow. A normal function returns control to its caller. An async function gives control to a callback function.

**Comment by jsms90** [comment]
@finnhodgkin How are you getting on with this? Could you post a link to your repo?

**Comment by finnhodgkin** [comment]
Hey @jsms90 
Here's my first attempt. I don't think I've quite nailed the balance of difficulty but you can decide for yourself:

https://github.com/finnhodgkin/morning-challenge-traffic-lights

There are two solution branches, one deeply in callback hell and the other playing around with a simple waterfall and some functions. I'm absolutely knackered so it may be a bit of a mess... :man_shrugging:

**Comment by finnhodgkin** [comment]
I've got tomorrow completely free to tidy up things and sort all the other little things on my list for week 2 :+1:

**Comment by finnhodgkin** [comment]
Also I'm happy to transfer ownership to F&C as soon as it's in a usable state.

**Comment by jsms90** [comment]
Sure thing, if you could follow the pattern, and put your name at the top as an author (and maintainer if you want to), that would be great :+1:

**Comment by oliverjam** [comment]
This is done right?

**Comment by finnhodgkin** [comment]
Yeah I'm just doing one last tiny change right now

**Comment by finnhodgkin** [comment]
:+1: done
