### ISSUE TITLE
turn week 1 biz dev into a github "scavenger hunt" to introduce students to participation

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#334]
For FAC10, we tried to cover a lot of ground in the [11:30-13:00 introduction to FAC talks](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/week-1#day-1).

I don't think that FAC's large number of GitHub repos & the navigation between them all was particularly obvious to FAC10. Given that github is the main way to get involved in our co-operative, this is a sincere problem.

Instead of leaving this to the talks, perhaps the week 1 business development slot should be spent, allowing students to browse through the repos and become familiar with our contributing guidelines. I will think about a way 

**UPDATE:** [Mark's talk is staying on Wednesday](https://github.com/foundersandcoders/master-reference/issues/333)
If Mark's talk on community is going in the last half our of the first day, this would put github repo exploration into 16:00-17:30.

@Cleop @bradreeder @des-des @eliascodes @rebeccaradding @antoniotrkdz @Samatar26 Thoughts?

**Comment by bradreeder** [comment]
Only main thing I remember from when we talked about this is making this afternoon slot about how students contribute to the organisation. So rather than assign people to cleaning rota and C4E C4W in the morning you can use the first part of this to introduce student roles, then present them the main organisational repos and give them an hour to familiarise themselves.

**Comment by Cleop** [comment]
I agree @jsms90 that it's a lot to take in during a talk and probably washes over you. I feel like self-exploration is a bit haphazard and I'm sure there are repos out there that I still don't realise exist. Perhaps a sort of contents page style readme file would help? Like a written map, the names of the key repos and then one line on each summarising what you might use it for. Then perhaps using this, self-exploration might be a bit more fruitful?

**Comment by rebeccaradding** [comment]
@jsms90 ah, so many thoughts. One way of guiding self-exploration could be a scavenger hunt in pairs and teams, to get people digging and searching and answering targeted questions. Would be more than happy to collaborate on this.

@Cleop I've actually updated the `london-programme` and `nazareth-programme` repos so that they have a "table of contents" explaining which repos are connected to those home base repos.

**Comment by eliascodes** [comment]
@rebeccaradding to complete the set, there's now a similar thing for gaza in foundersandcoders/gaza-programme#3

**Comment by jsms90** [comment]
@rebeccaradding Do you have some time on Friday for this? Pick a time of day that works for you and we'll google calendar it :grin:

**Comment by rebeccaradding** [comment]
@jsms90 how's 5 PM your time Friday?

**Comment by jsms90** [comment]
@rebeccaradding made a [FAC calendar event](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=NGxyZHJ2MjFzMnFibDBsb2FpYzZidWdsMmQgaDczMjl2dTlxcGk2NGNsaTJzZGs1M2w5ZWNAZw&tmsrc=h7329vu9qpi64cli2sdk53l9ec%40group.calendar.google.com)

If anyone else is interested, you're welcome to join :smile:

**Comment by jsms90** [comment]
### Initial brainstorm

Things students should be aware of or know about

**master-reference**
+ Use search bar to see if anyone has raised an issue before on the topic you want to raise an issue on (in a workshop repo & in master-reference itself)
+ Who are the maintainers of the master-reference?
+ If you find someone has raised an issue on that topic before, how would you know whether to raise a separate issue? Potentially give them a few options. Which of these options would merit a separate issue and why?
+ Attaching the appropriate topic label (situation)
+ Attaching the appropriate campus label (situation)
 
**london-programme**

+ Where do I find out how to become a member of FAC London?
+ How many business meetings to attend before becoming a member?
+ When are business meetings held?
+ Where do I find the start and end dates for London?
+ Where do I find the FAC London calendar link?
+ If there’s something you want to talk about with other people in the community, what label do you apply to the issue?
+ Sample proposal: types of fruit for delivery (with a few intentional problems in the proposal) - ask each group to post a clarifying question/comment
+ What is the current mission of FAC London? 
+ What is the current vision of FAC London?
 
**international**
+ What is the charitable purpose of FAC international? 
 
**Committees:**
+ List of topics - identify where to raise an issue for discussion (different London repos)
Employers
  + Money
  + Outreach (maybe)
  + Membership
  + Marketing - if I wanted to write a blog post...

The following things are hard to find / vague / missing / etc. Raise an issue proposing a change - assign one to each group.
+ Who was on each cohort before mine?
+ Who is responsible for answering the phone?
+ What do I say if someone on the phone asks X? (we need a list of FAQs based on the kinds of things people call up and ask students)
+ How do I get my issue added to the next business meeting?
+ Who is on each committee and how do I join it? (note to selves - should committees have chairs? - need to define the role of chair - to get meeting on calendar and to identify a facilitator)
+ How often do committees meet?
+ Coding tutorial websites that we have a shared FAC account for & who to ask for the login details
+ What’s FAC’s selection process? How is a cohort chosen? (probably not necessary/helpful to ask students to look for that on their first day after being chosen)

**Comment by jsms90** [comment]
Haven't figure out a good way to do this, because a lot of the `master-reference`'s content might not mean much to them yet
> If you find someone has raised an issue on that topic before, how would you know whether to raise a separate issue? Potentially give them a few options. Which of these options would merit a separate issue and why?

Zooey will be raising an example issue in his talk on consensus. Not sure about creating a "fake" proposal that hasn't stemmed from a discussion & there are quite a few requests in `london-money` for budget approvals.
> Sample proposal: types of fruit for delivery (with a few intentional problems in the proposal) - ask each group to post a clarifying question/comment

With little experience of github, it seems likely that giving students examples of what isn't there, is only going to end up with them copy-pasting sentences like "How often do committees meet" into an issue title and then not knowing what to say in the body, because they didn't come up with the problem themselves.

Hopefully we can find lots of ways to improve this & include some of the above, after trialing it once :tada:

**Comment by eliascodes** [comment]
@jsms90 this is now a thing in each location, can we close?
