### ISSUE TITLE
Week 3 - write a Modular Design workshop

### ISSUE THREAD

**Issue by edgarfinn** [foundersandcoders/master-reference#336]
To replace the [Stackoverflow profile builder workshop](https://github.com/foundersandcoders/workshop-client-side-design)

Introducing IIFEs, closures and modular design patterns by providing students with a function (but non-modular) code base of a basic app, and asking them to break it out into modules.

**Comment by lucyrose93** [comment]
Action points for Modular Design Workshop:
+ [ ] Create new repo in Founders and Coders 
+ [ ] Add detailed Learning Outcomes to README
+ [ ] Use parts of @eliascodes day-long workshop on Software architecture

**Comment by eliascodes** [comment]
self-assigning, since this is on me.

**Comment by lucyrose93** [comment]
@eliascodes Thanks so much for stepping in, sorry it's a bit last minute. 🕐  🐇 
Here's the [Modular Pattern Workshop](https://github.com/foundersandcoders/Modular-Pattern-Workshop/blob/master/README.md) repo I've started, with learning outcomes. 
It could be 2-3 hours, depending on how you want to structure it. 
Let us know how you get on.

**Comment by lucyrose93** [comment]
Feel free to reuse any parts of your architecture workshop that are relevant.

**Comment by lucyrose93** [comment]
For reference, here's the [Software Architecture Design Workshop](https://github.com/lucyrose93/Workshop-Software-Architecture-Design) that I'm currently working on. I think it would be good to start them off with these higher level concepts before we do your modular patterns workshop.

**Comment by lucyrose93** [comment]
How is this going @eliascodes ?

**Comment by eliascodes** [comment]
@lucyrose93 @-et you guys in foundersandcoders/workshop-client-side-design#9 did you see?

**Comment by eliascodes** [comment]
Done: [foundersandcoders/ws-software-design-js](https://github.com/foundersandcoders/ws-software-design-js)
