### ISSUE TITLE
Week 3 - Updates to Parallel Functions workshop.

### ISSUE THREAD

**Issue by edgarfinn** [foundersandcoders/master-reference#337]
Add comments and clarity in the readme and code to ensure the challenge is totally clear and the codebase is as readable as possible.

**Comment by lucyrose93** [comment]
@edgarfinn how is this going?

**Comment by edgarfinn** [comment]
@lucyrose93 PR here
https://github.com/foundersandcoders/master-reference/pull/408

**Comment by jsms90** [comment]
@edgarfinn Please reference this issue within the body of your PR. That would remove the need for comments like the one above.

Excellent job on the granular commits & referencing issue numbers in there though!
