### ISSUE TITLE
Week 3 - Write a flexbox front-end skills workshop

### ISSUE THREAD

**Issue by edgarfinn** [foundersandcoders/master-reference#339]
### Problem:
- In the curriculum planning meeting it was decided that more HTML and CSS skills would be introduced.
- Flexbox compatibility [has improved](https://caniuse.com/#feat=flexbox), and is a great asset for layout and content arrangement that students are currently left to discover off their own back.

### Solution:
- As discussed in #300 ...  introducing students to the wonderful world of flexbox, and challenging them to design a simple responsive app using provided images / content.

### Hypothesis:
- Students will be better equipped:
  - with tools to quickly and effectively lay content out, particularly when prototyping in html & css.
  - and to design responsive layouts
  - to work on projects with flexbox

- Given that [Learn CSS Layout](http://learnlayout.com/) is part of the pre-course reading, and teaches alternative solutions to pretty much all of what flexbox offers, students should already have alternative solutions available to them to address compatibility issues.

**Comment by jsms90** [comment]
This issue follows [the format](https://github.com/foundersandcoders/a-pattern-language/issues/7) that @bradreeder is trialing in the pattern language repo with [the addition of a community lunch to week 1](https://github.com/foundersandcoders/a-pattern-language/issues/9)

**Comment by lucyrose93** [comment]
@smarthutza how is this coming along?

**Comment by smarthutza** [comment]
Workshop available here: https://github.com/smarthutza/flexbox-workshop

**Comment by jsms90** [comment]
@oliverjam @PiotrBerebecki @njsfield @mattlub All user tested this workshop

@oliverjam & @PiotrBerebecki both said it took them 15 minutes to complete.
@njsfield @mattlub Do you have any time estimates?

**Comment by mattlub** [comment]
@jsms90 I didn't finish the workshop but raised an issue.
