### ISSUE TITLE
 Detail the Learning outcomes for the accessibility morning challenge

### ISSUE THREAD

**Issue by Samatar26** [foundersandcoders/master-reference#342]
The learning outcomes for [this](https://github.com/foundersandcoders/accessibility-challenge) challenge should be written down somewhere in the master reference.

**Comment by jsms90** [comment]
@Samatar26 @antoniotrkdz How is this going?

**Comment by Samatar26** [comment]
@jsms90 I pushed a learning outcomes branch to the repo, so consider it done https://github.com/foundersandcoders/accessibility-challenge/tree/learning-outcomes

**Comment by jsms90** [comment]
Nice. Happy to close this issue?

**Comment by Samatar26** [comment]
Yep
