### ISSUE TITLE
Teach the students about the command line in a talk and/or point them to a resource

### ISSUE THREAD

**Issue by Samatar26** [foundersandcoders/master-reference#344]
Since the command-line research topic isn't in the curriculum anymore in preference for a 'how to research afternoon' See #307. We would still like to familiarize them about the command-line/terminal and this can be done by either pointing them to a centralized resource and moving/updating this readme (https://github.com/FAC10/research/blob/master/week-1/customizing-command-line.md). It could also be done by @antoniotrkdz giving a talk.

**Comment by jsms90** [comment]
Given that you guys are reverting to the old research topics https://github.com/foundersandcoders/master-reference/issues/307#issuecomment-310906656, are you happy to close this issue?

**Comment by Samatar26** [comment]
@jsms90 Yes
