### ISSUE TITLE
define learning outcomes for authentication week

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#348]
![image](https://user-images.githubusercontent.com/15656538/27411236-62eaca50-56e4-11e7-801d-16bcae044586.png)
![image](https://user-images.githubusercontent.com/15656538/27411289-9f0bf40a-56e4-11e7-97e4-fcc09ed1a0c5.png)

**Comment by jsms90** [comment]
@ronanyeah @des-des Can I request that we define these as soon as possible? In my experience, a week tends to have much more coherence when designed with these in mind first.

This would also enable @bo-bok and @alexis-l8 to start reading around the subject matter

**Comment by alexis-l8** [comment]
@ronanyeah please could you chuck those learning outcomes in here :)

**Comment by des-des** [comment]
@jsms90 me and @ronanyeah will have do this by the end of da week

**Comment by des-des** [comment]
@jsms90 me and @ronanyeah will have do this by the end of da week

**Comment by bo-bok** [comment]
hey @des-des @ronanyeah - could you give us an update on the current status on the learning outcomes and when we can expect them by? They'll be really helpful in guiding mine and @alexis-l8's research in preparation of the week

**Comment by ronanyeah** [comment]
@alexis-l8 Where's that list you had from ages ago? That was pretty accurate.
Off the top of my head:

- Password management (hashing, bcrypt)
- Cookie management (setting them, deleting them)
- Session management (encrypted cookies, JWTs)
- Secure routing

So therefore the project should be a web app that has users, and protected routes.

**Comment by jsms90** [comment]
@alexis-l8 @bo-bok @ronanyeah @des-des I merged a file with the outcomes that are written in the comment above, just so the week was complete for day 1 with the students.

Are you happy with these, or do you think this needs any more work before we can close this issue?

**Comment by ronanyeah** [comment]
It says 'encrypted cookies' instead of signed. That has now become a lie!
