### ISSUE TITLE
create password security workshop [workshop 1]

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#349]
### Learning outcomes
![image](https://user-images.githubusercontent.com/15656538/27413237-f0c6a508-56f1-11e7-8179-1cf67a34883d.png)

### Planning on gitter
![image](https://user-images.githubusercontent.com/15656538/27411566-5058eeb0-56e6-11e7-9666-a0a3e027e201.png)
![image](https://user-images.githubusercontent.com/15656538/27412239-368bbe9a-56eb-11e7-81ea-619a7f2fa436.png)
![image](https://user-images.githubusercontent.com/15656538/27412251-4cdc60be-56eb-11e7-956b-8bd3950a1b80.png)
![image](https://user-images.githubusercontent.com/15656538/27412269-6c89337e-56eb-11e7-856a-c9ad368e8073.png)
![image](https://user-images.githubusercontent.com/15656538/27412310-a783faae-56eb-11e7-8d2f-1a4f4342bbb9.png)

**Comment by ronanyeah** [comment]
Done: https://github.com/foundersandcoders/ws-password-management

**Comment by eliascodes** [comment]
@jsms90 can we delete the foundersandcoders/password-security-workshop repo?

Also is this ready to close?

**Comment by jsms90** [comment]
@alexis-l8 @bo-bok Hopefully these articles should help you to read around the topic to prepare:
+ [about secure password hashing](http://security.blogoverflow.com/2013/09/about-secure-password-hashing/)
+ [salted password hashing - doing it right](https://www.codeproject.com/Articles/704865/Salted-Password-Hashing-Doing-it-Right)
+ [how to store your users passwords safely](https://nakedsecurity.sophos.com/2013/11/20/serious-security-how-to-store-your-users-passwords-safely/)

**Comment by alexis-l8** [comment]
Presentation to accompany workshop readme and exercise: https://drive.google.com/open?id=0BxXF_LZcFnS5amt6U3BCejd0cGc

**Comment by jsms90** [comment]
The presentation covers the same material as the readme in this workshop, but needs to be given its own slot in the timetable #550 

The workshop has been added to the week schedule, so I'm closing this issue :+1:
