### ISSUE TITLE
authentication week project

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#350]
### Initial suggestion
> @jsms90
> Some kind of CMS whose users have different sets of permissions that affect route access

### Planning on gitter
![image](https://user-images.githubusercontent.com/15656538/27412382-18772d76-56ec-11e7-92f3-259733d92b99.png)
![image](https://user-images.githubusercontent.com/15656538/27412397-2dcfa7fc-56ec-11e7-8269-c244358c37bb.png)

**Comment by jsms90** [comment]
@alexis-l8 @bo-bok what do you think of these requirements:
+ Log in form with username and password fields
+ Log out button
+ At least 1 route uses an INSERT query on the database
+ At least 3 different roles (e.g. admin, author, reader)
+ At least 3 different permissions levels (e.g. create new content, edit own content, edit any content, move content, delete content)
+ Client-side _and_ server-side validation (on at least the login page, if not the content posting form), including error handling that provides feedback to users

**Comment by jsms90** [comment]
After speaking with @des-des the idea is to pair this back and focus on just authentication, rather than adding roles & permissions. (We don't have any workshops on this anyway.)

So something more like
+ Username visible on the page after login
+ Name of the author should be visible against each post
+ An authenticated, logged in user can perform CRUD operations on their own posts but not on other people's
+ An unauthenticated user can still read / view the website!

Possible stretch goals:
+ Add comment functionality to posts
+ Add like functionality to posts
+ Have an "admin" level user who can perform CRUD operations on anyone's posts

**Comment by ronanyeah** [comment]
> (We don't have any workshops on this anyway.)

[Workshop 3 - Session management](https://github.com/foundersandcoders/ws-session-management) has all the roles you need.

**Comment by jsms90** [comment]
@ronanyeah That shows them how to add another key value pair to the cookie :+1: but they will never have implemented roles & permissions within their server logic and this will automatically make their schema more complex.

Not necessarily a problem. But a stretch goal is probably more realistic for this week, on top of pure authentication itself.

**Comment by ronanyeah** [comment]
I see what you mean. I think they can manage though. A stretch goal is probably best.
