### ISSUE TITLE
morning challenge 1 (HTML & CSS)

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#351]
From our hangouts call, I seem to remember us talking about validation on the login screen? But perhaps node week 2 are covering this?

Any other ideas?

**Comment by jsms90** [comment]
@bo-bok @alexis-l8 have you made any headway on this?

**Comment by jsms90** [comment]
### Client-side validation + user feedback
@bo-bok I did an absolute ton of form validation stuff on my first post-FAC project with IP Cortex. So hit me up on gitter if you need any help, but here's a summary of what we've spoken about already & a few more bits for help.

#### Background - students' current awareness
Here are FAC11's postgres week projects (some people did some validation, others did none).

#### Explanatory paragraph
Would be nice to highlight [why you need client-side _and_ server-side validation](https://stackoverflow.com/questions/15855770/why-do-we-need-both-client-side-and-server-side-validation), and specify that we're focusing on client-side during this morning challenge?

Then focus on the importance of [good user feedback](https://medium.com/@andrew.burton/form-validation-best-practices-8e3bec7d0549)
> + Right time
> + Right place for validation output
> + Right color for the message
> + Clear language for your message

#### Choosing content - relate to project brief
Keep in mind what students will be implementing during their project i.e. 2 form submissions:
+ login (username and password) - having password validation is important
+ user posting something to the database - this could basically be _anything_

We could make this a little like the [ES6 morning challenge](https://github.com/stevehopkinson/es6-challenge), where lots of options are highlighted to students but then they get to pick which things they want to try? That would make casting solutions way more fun and interesting, because everyone will choose a different thing to focus on and take a different approach.

After all, there are so many types of field you might want to validate, approaches you could take to validation, ways you could provide feedback to the users, etc.

#### Approaches to validation
+ Validate each field one by one (e.g. on keyup / on blur)
+ Validate all fields at once (e.g. on submit)

Can also provide hints _before_ user attempts to input:
+ question mark next to input field, which user can click on for a pop up explanation
+ asterisk next to input fields to indicate "required" (although this doesn't mean much to non-digital-natives)
+ short one-liners next to / underneath input fields

#### Approaches to user feedback
+ Display actual sentences describing the type of error
+ Change background colour / border colour of input field

#### Tools
+ HTML5 attributes (`required`, `type="..."`, `pattern="..."`, etc)
  + use `title` for default HTML5 error message pop-ups
  + `novalidate` to stop the default pop-ups and make your own user feedback
  + **Note:** not all browsers support HTML5 validation!
+ CSS pseudo classes
+ Regex - could be a whole morning challenge by itself, but particularly good to highlight this for passwords
+ Highlight use of `e.preventDefault`

#### Helpful resources
+ https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation
+ http://webaim.org/techniques/forms/controls
+ https://medium.com/@andrew.burton/form-validation-best-practices-8e3bec7d0549
+ http://formvalidation.io/examples/

**Comment by ronanyeah** [comment]
> Note: not all browsers support HTML5 validation!

RE: support. I don't think warnings like like this are necessary (and are confusing) if the support is greater than 90%, especially when that ~10% is going to be enterprise computers that are not owned by the public.
http://caniuse.com/#feat=forms

**Comment by jsms90** [comment]
@ronanyeah totally agree.

Sorry, I should have been more specific. I wouldn't suggest that you put in exactly that sentence. But it might be worth encouraging students to use http://caniuse.com 

e.g. http://caniuse.com/#feat=input-datetime

**Comment by jsms90** [comment]
But yeah, to be fair, it's all actually way better supported than I realised! Obviously been reading old articles :fearful:

**Comment by ronanyeah** [comment]
I think FAC has always had this myth that there is a legion of IE8 users somewhere whose lives will be be wildly enriched by our next MVP.

**Comment by ronanyeah** [comment]
Now _accessibility_, on the other hand, is something we could probably do better on. This [tool](http://pa11y.org/) is GREAT.

**Comment by jsms90** [comment]
Oh wow!! I'd heard of [a11y](https://addyosmani.com/a11y/) before (kinda sucks), but `pa11y` seems awesome!!

**Comment by jsms90** [comment]
@bo-bok How's this going? Do you have a link to the repo?

**Comment by jsms90** [comment]
https://github.com/foundersandcoders/mc-client-side-validation is still a WIP but is definitely going ahead, so it has already been added to the week schedule. Further issues can be raised within the workshop repo itself, so I'm closing this issue
