### ISSUE TITLE
create morning challenge 2

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#352]
authentication-related challenge

**Comment by alexis-l8** [comment]
@des-des to glance over @ronanyeah workshops 1-3 and then to suggest morning challenge2 ideas... if not creating it :)

**Comment by des-des** [comment]
coolio

**Comment by des-des** [comment]
Will speak to @ronanyeah separately to scope this out

**Comment by jsms90** [comment]
@des-des Is [this](https://github.com/foundersandcoders/mc-do-this-then-do-that) the morning challenge you're making on callbacks?

**Comment by jsms90** [comment]
https://github.com/foundersandcoders/mc-do-this-then-do-that has been added to the week schedule. There are [outstanding issues](https://github.com/foundersandcoders/mc-do-this-then-do-that) that should be dealt with for this mc to fully explain the confusion with callbacks.

But such issues will be dealt with in the mc repo itself. So this issue can be closed
