### ISSUE TITLE
session management workshop [workshop 3]

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#353]
### Repo
https://github.com/foundersandcoders/session-management-with-cookies

### Planning on gitter
![image](https://user-images.githubusercontent.com/15656538/27412608-9d78f1c0-56ed-11e7-8196-6b8e85f0092e.png)
![image](https://user-images.githubusercontent.com/15656538/27412612-a9519894-56ed-11e7-9d32-82eb3d87f286.png)
![image](https://user-images.githubusercontent.com/15656538/27412617-b504451a-56ed-11e7-92f4-9c3a0052d2c7.png)

**Comment by ronanyeah** [comment]
a start: https://github.com/foundersandcoders/ws-session-management

**Comment by eliascodes** [comment]
@jsms90 can we delete foundersandcoders/session-management-with-cookies ?

**Comment by alexis-l8** [comment]
@ronanyeah to work on this week of July 17th

**Comment by bo-bok** [comment]
hey @ronanyeah - could you give us an update on the status of this workshop and when it will be ready for us to user test by? Thanks!

**Comment by ronanyeah** [comment]
This will be ready to user test Thursday/Friday.

**Comment by jsms90** [comment]
This workshop is still a WIP but issues can be dealt with within the workshop repo itself. It is definitely going ahead, so I'm closing this issue because it has been added to the week schedule.
