### ISSUE TITLE
create workshop on cookies & routing [workshop 2]

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#354]
### Planning on gitter - learning outcomes
![image](https://user-images.githubusercontent.com/15656538/27413123-50007bbc-56f1-11e7-9614-52d97c5c4aa3.png)

**Comment by alexis-l8** [comment]
Ronan to work on this week of July 17th

**Comment by bo-bok** [comment]
hey @ronanyeah - could you give us an update on the status of this workshop and when it will be ready for us to user test by? Thanks!

**Comment by ronanyeah** [comment]
Workshop 2 is now cookies only. Will be ready for user testing tonight.

**Comment by jsms90** [comment]
@ronanyeah's workshop (https://github.com/foundersandcoders/ws-cookies) has been added to the week schedule :+1:
