### ISSUE TITLE
authentication week research topics

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#355]
### Background - previous research topics
[FAC9 hapi Research topics](https://foundersandcoders.gitbooks.io/fac9/content/week5/readme_topics.html)
+ [Authentication](https://github.com/FAC9/READMES/blob/master/hapi/authentication.md)

[FAC9 - OAuth research day topics](https://foundersandcoders.gitbooks.io/fac9/content/week8/readme_topics.html)
+ [Authentication](https://github.com/FAC9/READMES/blob/master/oauth/authentication.md)
+ [Authorisation](https://github.com/FAC9/READMES/blob/master/oauth/authorisation.md)
+ [Cookies & local storage](https://github.com/FAC9/READMES/blob/master/oauth/cookies-and-local-storage.md)
+ [JWTs](https://github.com/FAC9/READMES/blob/master/oauth/jwts.md)

[FAC10 / FACN1 Research topics](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-7/research-afternoon.md) - 
  + Authentication (not in the FAC10's research repo) | [FACN1](https://github.com/FACN1/research/blob/master/week-7/authentication/authentication.md)
  + Cookies & caching - [FAC10](https://github.com/FAC10/research/blob/master/week-7/Cookies-and-Caching.md) | [FACN1](https://github.com/FACN1/research/blob/master/week-7/cookies/cookiesAndCaching.md)

[FACN1's week 8 research on JWTs](https://github.com/FACN1/research/blob/master/week-8/whatIsAJWT.md)

### Planning on gitter
![image](https://user-images.githubusercontent.com/15656538/27412475-d0e45168-56ec-11e7-8ae7-83c6043a6d0e.png)
Note: "second article" = https://ponyfoo.com/articles/json-web-tokens-vs-session-cookies

**Comment by jsms90** [comment]
From @des-des 
> @jsms90 Do you think scope / granular permission might be too much? Just focusing on authenticating a user might be better ..
>
> Ie only 2 sets, unauthenticated, and authenticated
>
> Not sure

**Comment by alexis-l8** [comment]
Once workshops have been completed and reviewed, @bo-bok and I to think about what students should research based on what we needed to research. Open to suggestions from the rest of the team :)

**Comment by jsms90** [comment]
@des-des @ronanyeah What do you think of the following?
+ HTTP vs HTTPS
  + how does HTTPS work? what is a certificate?
  + demo how to add TLS certificates to a project - point students to ["how to use the tls module" article](https://docs.nodejitsu.com/articles/cryptography/how-to-use-the-tls-module/)
+ Stateless vs stateful authentication
  + what are they? - draw flow diagrams
  + pros and cons of each
+ Where to store your JWT
  + cookies vs web storage (local or session)
  + vulnerability to attacks - Cross Site Request Forgery (CSRF) & XSS attacks

Need one more

**Comment by ronanyeah** [comment]
Ah the dreaded reading day...

@jsms90 Those suggestions are awesome.

**Comment by ronanyeah** [comment]
i actually think 'Cross Site Request Forgery (CSRF) & XSS attacks' could be it's own one.

**Comment by jsms90** [comment]
@ronanyeah I know, right? :wink: 

Yeah I was kinda thinking the same!

How about:
+ Using localStorage and sessionStorage
  + Create an example of saving information in web storage (think of a better wording that will encourage them to do something like [this](https://toddmotto.com/storing-data-in-the-browser-with-the-html5-local-storage-api/))
  + Why would you store your JWT in a cookies rather than web storage (local or session)?
+ Vulnerability to attacks
  + What are the following types of attack and what methods are there for defending against them?
     + Cross Site Request Forgery
     + XSS
     + MITM
  + Create an example

**Comment by ronanyeah** [comment]
The storage one is forgetting `IndexedDb`. This is tricky, because it is promise based, but you are kidding yourself if you think you have researched and don't know what it can do.

(Also has anyone ever used `sessionStorage`??)

**Comment by jsms90** [comment]
> you are kidding yourself if you think you have researched and don't know what it can do

I genuinely don't understand what you mean here. Are you saying that I haven't done my research because IndexedDb isn't in this list? :confused: I just wasn't sure that IndexedDb was a bitesized enough for topic them for them to be able to cover adequately within an afternoon.

> Also has anyone ever used sessionStorage??

Hahahah! I haven't. I only put it in there because I kept finding articles online asking things like "should JWTs be stored in a cookie or in session storage?"

**Comment by ronanyeah** [comment]
Excuse me, I wasn't referring to you, I meant if the research group is looking into web storage,and only come back learning about local storage.

**Comment by jsms90** [comment]
Ah right. I was only going to suggest they look into local and session storage. What do you think?

**Comment by des-des** [comment]
local storage + session storage + cookies (indexeddb i think depreciated?)

**Comment by ronanyeah** [comment]
I think you are thinking of Web SQL or something.

Cookies?? I don't think that's necessary considering the nature of the week. I suggest localtstorage and indexeddb.

**Comment by ronanyeah** [comment]
Session storage is one line 'same as LS but it gets removed when the session ends'. But as I keep saying, that is misleading as browsers entend sessions forever these days so you _cannot rely on that_.

**Comment by des-des** [comment]
@ronanyeah prob right about db, mostly I was just sayin words. Poss session storage is in memory (faster)

**Comment by ronanyeah** [comment]
Source?

**Comment by des-des** [comment]
no

**Comment by ronanyeah** [comment]
KNOWLEDGE HOARDER
