### ISSUE TITLE
create week schedule

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#356]
## Week Schedule and Responsibilities

See [general week structure](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/week-schedule.md#general-week-schedule) for us to follow.

Create this file and then update the wording and the links later, via the separate issues on each "part"

#### Day 1

- 10:00 - 10:15 - Introduction to learning outcomes

- 10:15 - 13:00 - Workshop 1

— LUNCH —

- 14:00 - 16:00 - Workshop 2

- 16:00 - 18:00 - Business development

#### Day 2

- 10:00-11:00 - Morning Challenge 1

- 11:00-12:45 - Workshop 3

- 12:45 - 13:00 - Introduce [research topics](./research-afternoon.md)

— LUNCH —

- 14:00 - 16:30 - Research

- 16:30 - 17:30 - Review and present topics

- 17:30 - 18:00 - Introduce [project](./project.md)

#### Day 3

- 10:00 - 11:00 - Morning Challenge 2

- 11:00 - 13:00 - Projects (planning)

— LUNCH —

- 14:00 - 17:00 - Projects

- 17:00 - 18:00 - Project Demo from alumni / External speaker

#### Day 4

- 10:00 - 13:00 - Projects

— LUNCH —

- 14:00 - 18:00 - Projects

#### Day 5

- 10:00 - 11:00 - Code review

- 11:00 - 12:45 - Respond to issues

- 12:45 - 13:00 - Plan presentations

— LUNCH —

- 14:00-15:00 - Cohort Stop Go Continue (retrospective)

- 15:00-15:40 - Team retrospectives

- 15:40-17:00 - Presentations (20 mins per group)

- 17:00-18:00 - External Speaker or Alumni Project Presentation

**Comment by alexis-l8** [comment]
@bo-bok 

Acceptance Criteria:

- Create new folder called week 7 in coursebook
- Put this file into the readme.md
- Update the coursebook readme to link to that file
- Update the master reference with morning challenges and workshop materials

**Comment by bo-bok** [comment]
@alexis-l8 I've done the above, but we'll need to update it at the end of the week once we have all the links to workshops ✨

**Comment by bo-bok** [comment]
@jsms90 @alexis-l8 are the learning outcomes defined somewhere on gh? I can't find them to add them to the week schedule
