### ISSUE TITLE
Update resources page

### ISSUE THREAD

**Issue by edgarfinn** [foundersandcoders/master-reference#358]
- Remove "Recommended" and "Optional" headers, its misleading
- Flexbox (flexbox froggy, css tricks) @edgarfinn
- Modular design and software architecture to compliment @lucyrose93's workshops. @lucyrose93  are you able to add any relevant resources here please?

**Comment by lucyrose93** [comment]
@edgarfinn @smarthutza please close this issue once the PR is merged :)

**Comment by jsms90** [comment]
@lucyrose93 You could use the "fixes" keyword to save you time in going back to clean up your own issues (not recommended when you're committing against an issue that someone else has raised).

But please don't merge your own PRs
