### ISSUE TITLE
Week 3 - Add flexbox requirement to project

### ISSUE THREAD

**Issue by edgarfinn** [foundersandcoders/master-reference#360]
So as to reflect the added flexbox workshop and skills that students are introduced to, the project on week 3 should require students to use flex box to lay out their projects. I'd value @smarthutza 's input here, but I would say a good spec would be to use flexbox to lay out the content retrieved from the project's respective API call

**Comment by lucyrose93** [comment]
As discussed @edgarfinn @smarthutza , I am closing this issue.
Flexbox is a more controversial part of the curriculum. So it would be good for people to have the freedom to either use Flexbox, or come up with an alternative that is just as effective (and supported across all browsers). Keeps the debate alive. 🔥

**Comment by edgarfinn** [comment]
👍 🔥

**Comment by jsms90** [comment]
@lucyrose93 :+1: 

Please update the top comment in your ["epic" issue](https://github.com/foundersandcoders/master-reference/issues/300) accordingly e.g. by ~~striking through~~ this bullet point
