### ISSUE TITLE
document what is expected from a mentor

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#365]
Originally raised [here](https://github.com/foundersandcoders/master-reference/issues/218#issuecomment-292712480)

All students get nervous before they are about to mentor their week. A lot of this would be helped by better understanding exactly what FAC expects from this role. Guidance from those who have mentored in the past would be invaluable.

+ [x] convert this into a markdown file, to be stored in `master-reference` or `london-programme` @rebeccaradding @sofer ?
+ [x] create a doodle poll for FAC11 to sign up as code reviewers
+ [ ] convert this doodle poll into a markdown file in `london-programme` on Monday 2nd, once students have signed up

#### When do I need to be present?
+ Full-time for your week. This is your way of paying it forward, for receipt of a free 16 week course.
+ Code reviewing one additional project during weeks 1-8

#### How many mentors are required at any one time?
Both (2 per week) at all times. Either:
- one to "lead" & one to float
- one to introduce and then float & one to observe at take notes/raise issues (replacement for current CF role)

#### What do I do during each time slot?
Morning challenges & workshops:
- Encourage students to find the repo through the links within `master-reference` (rather than posting in their gitter channel), so they learn to navigate the repo by themselves
- Cast MC using projector & provide verbal introduction
  - Very brief for MCs, in order to allow maximum possible time for attempting the challenge (mostly to mark the start of the day at 10am & make sure everyone has found the repo)
  - Longer for WSs, particularly if there is a pre-existing codebase. Walk all students through the existing file structure.
- Allow students the space to attempt this themselves first, but listen out for signs that students are struggling unnecessarily.
- Check in at halfway mark to ensure that students are progressing at the expected rate & discover any major cohort-specifc problems (if applicable)
  - MC: 20 minute mark
  - WS: 1 hour
- Float and unblock any severe problems (using mentor techniques)
- Stop everyone at 40 minute mark
- Lollipop students who cast their solutions.  
Note: if students ask mentors questions on implementation, first pose the question to the rest of the cohort in case someone other than the mentor is able to provide the answer

Code-alongs:
- 1 mentor "leads" / "delivers" code-along. Preparation is key. This is similar to giving a talk. This mentor should practice delivering this code-along multiple times, so they are able to provide verbal explanations freely without flicking back and forth from their notes.
- 1 mentor floats throughout, unblocking students' problems & asking the mentor who is delivering to slow down or pause wherever necessary

Research afternoons:
- Verbally introduce the topics & ask students if they need any clarification before beginning
- Remind students to prepare questions to ask the rest of their cohort
- Preparation is key. Mentors should have a clear understanding of what students are supposed to gain from each of these research topics.
- This is largely self-directed time, but mentors may float occasionally in order to spot any severe problems that are likely to leave the students with nothing to present & then help to unblock (e.g. googling together).
- Be present during presentations & ask clarifying questions / correct any glaring errors
- Time keep for students (?) & prompt them to ask their questions at the end (more relevant in earlier weeks while they're getting used to the process)

Code reviews:
- Gather links to each of the repos _before_ 10am (they can easily be found within the cohort's github organisation & mentors shouldn't need to wait until students have posted their links in the gitter channel)
- Use the cohort's sign up sheet to assign 1 reviewer per project (2 mentors from that week, 2 mentors from other weeks)
- During "responding to issues" time, mentors discuss projects and whether there are any commonly occurring problems that may need to be relayed to the CF & mentors of the next week

SGC:
- Both mentors present
- One mentor is responsible for taking notes & uploading to `<city>-programme`

Presentation planning:
- Prompt students to cover all bullet points in the presentation guidelines (most relevant in earlier weeks as students are getting used to the process)
- Make suggestions about things seen during code review that the rest of the cohort might benefit from hearing about

Presentations:
- Time keep - provide 5 minute warnings
- Answer questions from students on best practices, topics they were unsure about, etc.

#### How to run my particular week:
- Follow `mentor-notes` guidance in `master-reference`
- Follow `mentor-notes` guidance within individual workshop repos #456 

Note: If these guidelines have not been written yet, create them yourselves during curriculum planning

#### Code reviewing one additional project during weeks 1-8
Sign up to the doodle poll

**Comment by jsms90** [comment]
@ZooeyMiller & @finnhodgkin would be great to have your feedback on this issue, as to whether you agree/disagree with any of it.

In terms of making this deliverable to future cohorts & available to the current cohort to look back at later, I'm happy to create a markdown file with whatever content we agree on. Or if you guys choose to make presentation slides, we can link to them?

@rebeccaradding @sofer @m4v15 @mantagen if we decide that this content is too London-specific, I'm happy to put this markdown file / link to slides into `london-programme` and link to it from the weeks-13-16 schedule?

**Comment by m4v15** [comment]
I haven't had a chance to fully read it actually but just scanning it in terms of guidelines it sounds totally appropriate to all campuses! I guess the only part that is different for Naz is just the feasibility of having people come out for sure, but I would say in general the idea is the same. So I think keep it here.

**Comment by jsms90** [comment]
Zooey and Finn's slides https://docs.google.com/presentation/d/1VG_-Pm5byZyzWrmZ0dH7r-0pUON1jxc_8W0OMn2sm5I/edit?usp=sharing
