### ISSUE TITLE
Proposed strategy for handling s-g-c notes + feedback

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#37]
@sofer @iteles @nelsonic @des-des This is a reflection of what I've done with FAC9's feedback from Monday's session:

* Created an issue to serve as a menu/ overview of issues ordered by priority until curriculum planning is complete: #18 
* Created an issue, with appropriate label tag, for each week and put a summary of that weeks s-g-c notes (coming shortly) and curriculum planning feedback there.
* Created an issue for each of the unresolved themes, unrelated to a specific week, that came up in the session.

-----------------------------

### Rationale

If the master-reference will become the gitbook, that means mentors will need to commit their plans here. I'd suggest mentors commit against the issue reserved for their week:

* Discussion and external review/comments can be done in that issue.
* Minutes of their meetings can be posted there, and their progress easily followed as commit history is in a single place. 
* Summaries of s-g-c notes and planning feedback are in one place at the head of the issue for the convenience of the mentors. 
* We only close the issue when we're satisfied they're finished and improvements are made.

If s-g-c notes are raised specific to a workshop or different repo, or warrant their own issue for discussion, we can raise them as issues there as well.

Any criticism is appreciated if you see a problem with this.

**Comment by iteles** [comment]
@bradreeder Are you proposing SGC notes are captured as issues rather than in an `md` file?

**Comment by bradreeder** [comment]
@iteles I don't see any reason we couldn't do both. But I think so. 

If the idea is that mentor's will improve the curriculum, largely based upon the feedback and issues they raise themselves, then to me s-g-c becomes more actionable if they are translated into issues that they or others can resolve when they become mentors.

**Comment by bradreeder** [comment]
Related #28. The proposal relates to whether this resource will become the equivalent of the gitbook for each cohort.

**Comment by jsms90** [comment]
@bradreeder I think that iteratively improving the contents of the curriculum means that the file history is enough of a reference - we don't need to store copies of the last FAC's curriculum (i.e. separate gitbooks)

But, we prob do need to document _how_ we got to the new iteration i.e. S-G-Cs in a less ephemeral way than issues. No one is going to trudge through closed issues to find that thought process.

But i'm not convinced that a markdown file, listing the entire history of S-G-Cs is the way to communicate that...

Does anyone know of any appropriate tools for documenting:

problem (highlighted in s-g-c) -> hypothesis (change of curriculum) -> review (s-g-c from next FAC)?

**Comment by shiryz** [comment]
We have a process which is similar to what's mentioned in this issue, will close but feel free to open if you think it's still relevant
