### ISSUE TITLE
week3 - provide waterfall-free solution to GithubAPI workshop

### ISSUE THREAD

**Issue by edgarfinn** [foundersandcoders/master-reference#372]
Since waterall functions are no longer being taught in week 2, [the github API workshop](https://github.com/emilyb7/workshop-APIs) needs to offer students a solution that does not make use of waterfall functions. 

In addition - since QUnit is no longer being taight - ideally students should at least be allowed some help using QUnit for this workshop, so they're able to write tests for their solutions.

**Comment by jsms90** [comment]
@edgarfinn Fixed by https://github.com/emilyb7/workshop-APIs/pull/9 ?

**Comment by edgarfinn** [comment]
Yes. If all good then this issue can be closed

**Comment by jsms90** [comment]
All yours @edgarfinn :+1:
