### ISSUE TITLE
intro to pair programming needs written instructions

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#385]
Currently, we just link to a document about the different pair programming methods.

It would be good to have written instructions on what the students are expected to do:
+ Find a partner and work from one computer together (close the other laptop)
+ Choose a kata on codewars, preferably one that neither of you have completed before
+ Read through the different pair programming methods & choose one that you want to try
+ Attempt the kata, using this type of pair programming. Don't worry if you don't finish the kata. The aim is to learn the process

10 mins before the end of the time slot, the students stop working on the kata. The group comes back to discuss which pair programming style they choose & how they found it.

Without this, mentors are required to remember how this worked on day 1 (4 months ago) or find our via word of mouth from the people who mentored them

**Comment by jsms90** [comment]
Priority 1 - this needs to be done before FACN2, so that FACN1 can use this to plan

**Comment by m4v15** [comment]
@mattlub @Suuuuha just to notify you off this before Sunday

I'm guessing none of us will have much time between now and then to write up the instructions but just so you both know what you're supposed to be doing for that workshop
