### ISSUE TITLE
go back to old running order of day 1? - environment talk before lunch

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#386]
students were asking where the toilets were, where they were supposed to put their things, what they're allowed to use in the kitchen, etc.

**Comment by oliverjam** [comment]
I agree — I had confused people asking me if they were allowed to use the milk etc before lunch.

**Comment by jsms90** [comment]
@rebeccaradding @m4v15 & @mattlub have switched this for FACN2

PR on the way
