### ISSUE TITLE
Curriculum Overview.md - schedule not obvious past reading week

### ISSUE THREAD

**Issue by astroash** [foundersandcoders/master-reference#387]
Page in question: master-reference/coursebook/general/curriculum-overview.md

It is not obvious from the Curriculum Overview.md what is being taught past reading week. It is mentioned briefly at the top of the page in **Outline**, however it is not mentioned in the detailed **Overview**. If you are scrolling through the page then it appears the course finishes on week 8.

**Comment by jsms90** [comment]
:thinking: Good point!

Would you solve this by
+ adding reading week & week 10-16 at the end of the list
+ removing the "Outline" section at the top (if people are likely to skip past it anyway?)

Or both of the above?

Also, do you think that [master-reference/coursebook/general/curriculum-overview.md](https://github.com/foundersandcoders/master-reference/general/curriculum-overview.md) is the right place for this breakdown? Or would it be more obvious somewhere else? e.g. [master-reference/coursebook/general/README.md](https://github.com/foundersandcoders/master-reference/general/README.md)?

**Comment by astroash** [comment]
I would keep the overview document separate as it isn't directly linked to the _General_ directory. It also allows people to search the repo for "Overview" and find the information they are after.

I think the **Outline** section is useful and hopefully others will be less likely to be skim reading and jump to the end. It may look more uniform if it has a h3 heading like the other sections or mark the detailed outline with another h2 title, but that might be personal preference. To make the curriculum-overview.md clearer to read I would:

- Add **Reading Week** at the end of the doc with a short description explaining expectations eg if there is a reading list or whether it is self guided
- Add **Week 10 - 16** with a short description explaining what this will entail
- Change Week titling from **Week One** to **Week 1** to make for easier scanning of the document

**Comment by jsms90** [comment]
The contents of the curriculum overview seems to be duplicated in [the coursebook readme](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/README.md).

@des-des perhaps you can clarify what you intended the distinction to be between the following files?
+ [`coursebook/README.md`](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/README.md)
+ [`coursebook/general/README.md`](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/README.md)
+ [`coursebook/general/curriculum-overview.md`](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/curriculum-overview.md)

**Comment by astroash** [comment]
Resolved in #530
