### ISSUE TITLE
better explanation of github flow - "please stop and merge my PR"

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#398]
Pattern across cohorts: "please stop what you're doing and merge my pull request"

We need a more thorough explanation of github flow and why we use it
https://lucamezzalira.com/2014/03/10/git-flow-vs-github-flow/
http://scottchacon.com/2011/08/31/github-flow.html

**Comment by zurda** [comment]
Is there an action needed on this issue? I can only speak for FAC-15, but for us, github workflow was something we became better at with time. It took a lot of practice, and as our communication skills improved - our github workflow improved as well. Personally, I feel the resources and workshops are sufficient, and I especially enjoyed the addition of working on a staging branch (thank you @onwordi ! ).

**Comment by astroash** [comment]
Outdated issue
