### ISSUE TITLE
Proposed Master Reference Structure

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#4]
@sofer @nelsonic @iteles @des-des I've been thinking about what the overall structure should be for this resource, and I'd like to propose we make this into a nested hierarchy of repos rather than one massive repo.

Imagine if, as an example, information related to the curriculum was structured like this:

* master-reference: contains an overview of curriculum with a link to each week's repo
* week repo: contains more detailed overview of that week with links to its workshop repos and the master reference
* workshop repo: contains the individual workshop and a link to its weeks repo

Proposed benefits:

* Makes the resource easier to navigate
* This could get tl;dr in one repo
* Maximum benefit of github issues (see my next comment).

**Comment by bradreeder** [comment]
Imagine if Stop-Go-Continue was as simple as this:

At the end of stop-go-continue the course facilitator and mentors (during end of week meeting) take the recorded stop-go-continue notes and break them down into the following categories:

* system-level: to do with overall structure of curriculum (e.g. we need a longer node week)
* integration-level: to do with overall structure of that week.
* unit-level: to do with a particular workshop.
* agent-level: to do with quality of mentoring.

We then raise their feedback's system-level issues in the master-repo, integration-level issues in that week's repo, unit-level issues in that workshop's repo, and agent-level issues in something akin to a "mentor's handbook" repo linked in the master-ref.

During curriculum planning all mentors then have to do is respond to the issues their group created in the weeks they're assigned to. Simples!

**Comment by bradreeder** [comment]
If people agree, I can start creating a skeleton structure and raise issues in each section based on current feedback of FAC9.

**Comment by des-des** [comment]
@bradreeder I think splitting this content over many repos will make navigation harder, we can use folder structure to break things down?

I think the purpose of this repo is to bring everything _together_..

**Comment by iteles** [comment]
One to discuss when we meet next week?

**Comment by bradreeder** [comment]
@iteles Sure thing!

@des-des To me, the main problem I want to tackle here is the process by which feedback from students gets fed back into our resources. If everything's in one repo it means everything shares the same github issues, and I wonder if one repo would accumulate too many issues over the course of a curriculum to be easily manageable.

**Comment by des-des** [comment]
Ok, pulling some things out of the doc, will leave them here for reference


* Week 11: Planning week. (MASTER REF UPDATE). We need day by day structured plan for this. stakeholders need to be involved in the decisions during discussion, not after.

* iterative update of master reference based on student feedback.
* creating of plan, dates, workshops for next FAC.
* get it out the way early, much easier to manage and students can focus on client-work without extra stress.
* Week 11/12 ? redis + sockets / d3 or something fun (not old)

**Comment by bradreeder** [comment]
I think this is out of date now as we're following a single-repo structure for the master-reference and raising all issues here. Closed. Can re-open if it becomes relevant.
