### ISSUE TITLE
set time limit on updates to workshops / morning challenges?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#400]
Now that students are being actively encouraged to raise issues, and each workshop & morning challenge has a separate maintainer, we are seeing students' requests for changes being actioned immediately :tada: 

The only problem that this may cause, is that mentors of the week in other campuses don't know what version of the workshop they are going to have to deliver.

Should there be a cut off date, beyond which, maintainers should be requested to hold of on making /accepting PRs?

**Comment by des-des** [comment]
I think we should take no action unless this actually causes problems

**Comment by eliascodes** [comment]
If it does cause problems, consider the use of git tags, as discussed last week.

**Comment by sofer** [comment]
Another option might be to extend the gap between the London and Nazareth campus starts to two weeks.

**Comment by jsms90** [comment]
@sofer Every week is being updated right at the last minute again, which I think is totally avoidable in future. I think that most of the current problems would be solved by having a stronger curriculum planning week and setting clearer expectations for mentors e.g. exactly what their remit is. So maybe staggering the campuses even further won't be necessary?

@des-des I would agree. But when the curriculum gets changed, merged and delivered in London without sufficient time for "user testing" the material, we are _bound_ to find things which will cause problems for Naz. In that situation, I don't want us to be afraid of making the necessary changes.

[This](https://github.com/foundersandcoders/master-reference/issues/394#issuecomment-312501911) was broadly what was decided for the time being. For now, I think we're going with communication between CFs & mentors of that week + tags, like @eliascodes said So opening this issue separately was probably a bit premature.

**Comment by jsms90** [comment]
We now have deadlines in the curriculum planning process: https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/curriculum-update-process.md#deadlines
