### ISSUE TITLE
include a dedicated slot in week 1 to reading "how to code review"

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#402]
FAC11 were pointed to this file but still asked us for a brief summary of how to step through a project.

We said:
+ readme
+ user stories - click through the website and compare its performance to the spec
+ code itself

But there's a lot of good info in the [code review doc itself](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/code-reviews.md#how-we-conduct-code-reviews) e.g. ettiquette on raising issues.

+ [ ] add 10 minute slot to week 1 schedule to allow students to read through this doc

Thoughts / comments @des-des @eliascodes @antoniotrkdz @Samatar26 @m4v15 @mattlub ?

**Comment by mattlub** [comment]
agree they need some instruction- though maybe in week 1 the doc is a bit too complicated- what I think happened for us was more like "an introduction to code review"

**Comment by jsms90** [comment]
@mattlub Something as basic as the bullet pointed list above?

**Comment by mattlub** [comment]
@jsms90 yes, and I would add (as you said) the point on etiquette, e.g. using links to specific lines of code etc.

**Comment by jsms90** [comment]
@mattlub Well you are essentially describing what's in the doc :sweat_smile: 

Are you suggesting that we just make the doc shorter?

**Comment by des-des** [comment]
@jsms90 good idea

**Comment by eliascodes** [comment]
Done via the linked commits and also with [this](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/code-review.md)
