### ISSUE TITLE
move presentation prep right before presentation (after SGC)

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#403]
Comment from FAC11 about forgetting what you had just planned if there was an entire SGC between planning and delivering the presentation.

Might also be nice to introduce SGC and what it is (in week 1) _before_ lunch & beginning SGC so explaining SGC doesn't eat into SGC time.

**Comment by zurda** [comment]
Pretty sure this is outdated, but if it isn't happy to help with a PR if needed
