### ISSUE TITLE
video Mark's community talk during FAC12

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#426]
@markwilliamfirth your talk keeps actively getting put on the "Continue" list at SGC:
+ [FAC10](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-1.md#continue-1)
+ [FAC11](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-11/cohort-week-1.md#continue)

Do you have any notes or a video of your talk that we could use to help mentors replicate the goodness in other locations? :grin:

**Comment by rebeccaradding** [comment]
@markwilliamfirth any notes would be great, @sofer and I are presenting this afternoon.

**Comment by markwilliamfirth** [comment]
I don't actually have any notes on this 😬 I think the slides are pretty self-explanatory though - if there are any slides that you think need more explanation could you let me know which ones?

**Comment by jsms90** [comment]
@sohilpandya @iteles @nelsonic Who has the video of @markwilliamfirth's talk during FAC10?

**Comment by sohilpandya** [comment]
I don't even think I took a video of him. 😟 

FAC should get a camera in the space which is ready to go so that events like these and any future talks don't go missing and are recorded.

**Comment by jsms90** [comment]
Mark's talk on the "Continue" in curriculum overview SGC for the 3rd cohort in a row.

We really need to video this next time

**Comment by katpas** [comment]
Can we video this!

**Comment by yvonne-liu** [comment]
Was this recorded for FAC12 @astroash?

**Comment by astroash** [comment]
Ah, I'm afraid not :(

**Comment by zurda** [comment]
Is this something that we can somehow recreate? I'm curious what was the talk about (links to sgc are broken).

**Comment by iteles** [comment]
@zurda This talk started with the history of Founders & Coders and moved into the community aspect of what it means to be part of the course and the wider community. It underlined that we're all a team and this is not a competition and set up some of the core values at the very beginning of the course, like if you get to the finish line alone (without your team), you've failed.

We can pretty easily recreate and update it! I haven't been in the classroom for a few cohorts so I don't know if it evolved into another talk, but happy to help review whatever is put together if not :)

**Comment by astroash** [comment]
The talk continues. @zurda I think I helped run it for your cohort 🙃. 

As this is cohort specific i think it can closed.
