### ISSUE TITLE
List of past workshops used in F&C

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#43]
We need to get together a list of the workshops, morning challenges and projects that have been created or used by past mentors before we come back in January so that the current set of mentors will have an opportunity to use & contribute to them.

I'll likely do a few callouts in the gitter channel for people to link resources here over the holidays as given my limited history here I doubt I can find them all.

**Comment by bradreeder** [comment]
@iteles @nelsonic I'm unsure how you want dwyl repo's to relate to this resource. If we categorised the workshops by week, can [learn-tdd](https://github.com/dwyl/learn-tdd), for example, be listed under the workshops used for testing week?

**Comment by sofer** [comment]
@bradreeder if we don't link to our favourite resources in the master reference, then every FAC will need to re-discover them. The master-reference will be most useful if it is also a meta-resource that links to a curated selection of excellent material elsewhere. 

@besarthoxhaj should be a good resource for morning challenges. He's done some great ones.

**Comment by nelsonic** [comment]
@bradreeder [`learn-tdd`](https://github.com/dwyl/learn-tdd) was _born_ out of @NataliaLKB and I wanting to do a ***TDD workshop*** for @LadiesOfCode and it was "_dog-fooded_" by F&C 5+6 ... it has since become one of the _most popular_ testing tutorials on the `internet`. (_thanks to everyone who contributed!_) I don't mind if someone makes a _better_ tutorial with a ***simpler step-by-step example*** and F&C switches away from using the @dwyl one, in fact I'd _love_ to see if it's _possible_... 🤔 

to answer your _second_ question:

_firstly_, `while` I did not get the change to be _on_ one of the F&C cohorts 😢  
I still feel like I've _contributed_ and hence consider myself to be a "_member_". 
(_also having paid a membership `fee` to be part of the **CIC** I think I qualify ... 
see: https://github.com/foundersandcoders/charter/issues/14#issuecomment-147254751 ..._) 

_secondly_, while I think people who are _attending_ the F&C course are certainly _capable_ of creating great learning resources, there are _substantial_ amounts of _fantastic_ learning resources available for ***Free*** online, so why waste the time re-creating them when you can just link to them? 

> also, @dwyl has been pretty _systematic_ about sharing our knowledge on _specific topics_ since _long_ before F&C so we have a _decent_ "_bank_" of tutorials which get improved by _both_ F&C/DWYL people and _complete_ strangers: https://github.com/dwyl?utf8=%E2%9C%93&q=learn ❤️  ✅ 

> in _some_ cases the @dwyl `learn-...` resources have been _mostly_ written by F&C alumni 
e.g: https://github.com/dwyl/learn-aws-lambda/graphs/contributors which is not _necessarily_ relevant to F&C's "core" curriculum but will be _useful_ when doing client projects involving the "serverless" architecture. the F&C people were _paid_ to write them as part of DWYL projects ... and the learning was very targeted+guided by a [_reasonably experienced_ developer](https://www.linkedin.com/in/nelsonic) ... 😉 

_finally_ @dwyl we will be _significantly_ increasing our learning pace/momentum in 2017 to the point that the materials will be _consistently_ "world class", which requires **years** of industry experience which will only be available to F&C graduates further down the line.

So, _excluding_ learning resources from the F&C `master-reference` based on `who` created them might be "self-harm"... unless of course the Org/Person who created the resources is someone F&C fundamentally does not want to support... (_I cannot think of any examples..._)

**Comment by bradreeder** [comment]
@nelsonic thanks for the background in your post. I only wanted to say I didn't intend to question who is or isn't a contributor or whether dwyl are a part of fac. I didn't phrase my meaning well, I'm all for open source.

I asked more out of concern that if we're trying to eventually create an online version of the curriculum through this resource that it may appear branded to outsiders as a f&c curriculum Where many other parties are involved in making it what it is.

In hindsight it's probably an irrelevant point as long as enough context is provided.

Happy holidays!

**Comment by des-des** [comment]
Not sure if dwyl has something better:

https://github.com/des-des/oauth-example

**Comment by eliascodes** [comment]
There's also this: https://github.com/eliascodes/Reputation-Builder, but I'd be keen to retire it in favour of this: https://github.com/eliascodes/workshop-client-side-design (issues/reviews/PRs welcome)

**Comment by Jbarget** [comment]
https://github.com/Jbarget/handlebars-morning-challenge

**Comment by bradreeder** [comment]
For node week I know there's:

https://github.com/nikhilaravi/learn-node
https://github.com/node-girls/workshop-cms
https://github.com/bradreeder/Node-Shell-Workshop
https://github.com/matthewglover/tape-testing

**Comment by des-des** [comment]
https://github.com/des-des/morning-challenges

**Comment by msmichellegar** [comment]
https://github.com/msmichellegar/learn-sass-basics :)

**Comment by bradreeder** [comment]
as raised in F&C6 gitter chat: https://github.com/katkelemen/FuncProgMorninChallenge

**Comment by bradreeder** [comment]
Okay, so, ascended master amidst the mortal plane that I am, I've trawled the Founders & Coders & dwyl organisations (& this thread), and gone through every gitbook and the following is what we've got so far.

### Next steps:

1. Many of the workshops or challenges we've used have never been made into repo's but instead are recorded in md files across the gitbooks. Those assigned to weeks will need to go through these & convert those they use into github repo's.
2. The other workshops are all scattered across our various members github profiles. I will continue to harass the gitter channel to get people to post them here as I'm not going to trawl 120+ members profiles >_>

**Help me out please and post workshops you've crafted in this thread!!**

#### Week 1: Toolkit

https://github.com/NataliaLKB/learn-git-basics
https://github.com/foundersandcoders/workshop-html-css

https://github.com/dwyl/contributing (workflow)
https://github.com/dwyl/learn-html5
https://github.com/dwyl/learn-web-browser-tools

#### Week 2: Testing

https://github.com/JMurphyWeb/testing-morning-challenge
https://github.com/indykid/romanizer_js

https://github.com/dwyl/learn-tdd
https://github.com/dwyl/learn-qunit
https://github.com/dwyl/learn-nightwatch
https://github.com/dwyl/learn-karma
https://github.com/dwyl/learn-user-experience-testing
https://github.com/dwyl/learn-appveyor
https://github.com/dwyl/learn-testling
https://github.com/dwyl/learn-coveralls.io
https://github.com/dwyl/linter-js-goodparts
https://github.com/dwyl/learn-jshint
https://github.com/dwyl/goodparts

#### Week 3: APIs

https://github.com/eliascodes/Reputation-Builder
https://github.com/eliascodes/workshop-client-side-design
https://github.com/foundersandcoders/workshop-api

https://github.com/dwyl/learn-api-design
https://github.com/dwyl/api

#### Week 4/5: Node Core

https://github.com/bradreeder/Node-Shell-Workshop
https://nelsonic.gitbooks.io/node-js-by-example/content/
https://github.com/nikhilaravi/learn-node
https://github.com/workshopper/learnyounode
https://nodeschool.io/
https://github.com/matthewglover/tape-testing/
https://github.com/sofer/sssk
https://github.com/claireinez/learn-node-tdd
https://github.com/node-girls/workshop-cms
https://github.com/node-girls/express-workshop
https://github.com/FilWisher/node-books

https://github.com/dwyl/autocomplete
https://github.com/dwyl/learn-travis
https://github.com/dwyl/terminate
https://github.com/dwyl/esta
https://github.com/dwyl/learn-environment-variables
https://github.com/dwyl/learn-json-schema
https://github.com/dwyl/learn-tape
https://github.com/dwyl/tape-parallel
https://github.com/dwyl/learn-istanbul
https://github.com/dwyl/env2
https://github.com/dwyl/learn-circleci
https://github.com/dwyl/learn-pre-commit
https://github.com/dwyl/autocomplete
https://github.com/dwyl/learn-node-js-by-example
https://github.com/dwyl/learn-codeclimate

#### Week 6: PostgreSQL

https://github.com/dwyl/hapi-postgres-connection
https://github.com/dwyl/postgres-schema-migration-checker
https://github.com/dwyl/joi-postgresql
https://github.com/dwyl/learn-postgresql
https://github.com/dwyl/hapi-login-example-postgres
https://github.com/dwyl/postgres-connection-pool-test
https://github.com/dwyl/how-to-chose-a-database

#### Week 7: Hapi

https://github.com/hapijs/makemehapi
https://github.com/Jbarget/handlebars-morning-challenge
https://github.com/rub1e/beam-me-up-hapi
https://github.com/minaorangina/good

https://github.com/dwyl/learn-hapi
https://github.com/dwyl/hapi-error
https://github.com/dwyl/hapi-auth-jwt2-cookie-example
https://github.com/dwyl/abase-validate
https://github.com/dwyl/hapi-riot
https://github.com/dwyl/hapi-typescript-example
https://github.com/dwyl/hapi-login
https://github.com/dwyl/hapi-register
https://github.com/dwyl/hapi-reset-password
https://github.com/dwyl/hapi-register-example
https://github.com/dwyl/hapi-login-example
 
#### Week 8: Auth/ oAuth

https://github.com/des-des/oauth-example
https://developer.github.com/v3/oauth/
https://github.com/foundersandcoders/oauth-workshop

https://github.com/dwyl/learn-json-web-tokens
https://github.com/dwyl/hapi-auth-jwt2
https://github.com/dwyl/hapi-auth-google
https://github.com/dwyl/hapi-auth-github
https://github.com/dwyl/hapi-auth-twitter
https://github.com/dwyl/hapi-auth-facebook
https://github.com/dwyl/hapi-auth-jwt2-example
https://github.com/dwyl/hapi-auth-github-example
https://github.com/dwyl/hapi-auth-linkedin
https://github.com/dwyl/hapi-auth
https://github.com/dwyl/hapi-auth-iron

#### Week 9: Redis + sockets

https://github.com/msmichellegar/redis-node-workshop

https://github.com/dwyl/hapi-socketio-redis-chat-example
https://github.com/dwyl/hapi-redis-connection
https://github.com/dwyl/learn-redis
https://github.com/dwyl/redis-connection
https://github.com/dwyl/hapi-socketio-redis-riot-chat-example
https://github.com/dwyl/learn-websockets

### Other 

#### AWS

https://github.com/dwyl/aws-sdk-mock
https://github.com/dwyl/learn-amazon-web-services
https://github.com/dwyl/learn-aws-lambda
https://github.com/dwyl/learn-aws-iot
https://github.com/dwyl/aws-lambda-deploy
https://github.com/dwyl/aws-lambda-test-utils
https://github.com/dwyl/stream-to-s3

#### Front-end

https://github.com/msmichellegar/learn-sass-basics
https://github.com/foundersandcoders/workshop-materialize-css
https://github.com/foundersandcoders/begin_react_workshop

https://github.com/dwyl/learn-tachyons
https://github.com/dwyl/learn-riot
https://github.com/dwyl/learn-react
https://github.com/dwyl/elm-workshop
https://github.com/dwyl/learn-elm
https://github.com/dwyl/learn-redux
https://github.com/dwyl/learn-elixir
https://github.com/dwyl/learn-react-native

#### Best practices/ Tooling/ Setup, etc.

https://github.com/shouston3/My-Config

https://github.com/dwyl/goodparts
https://github.com/dwyl/repo-badges
https://github.com/dwyl/javascript-best-practice
https://github.com/dwyl/learn-google-analytics
https://github.com/dwyl/time
https://github.com/dwyl/github-reference
https://github.com/dwyl/interview-prep
https://github.com/dwyl/product-owner-guide
https://github.com/dwyl/best-practices
https://github.com/dwyl/UK-HMRC-FAQs
https://github.com/dwyl/style-guide
https://github.com/dwyl/dev-setup
https://github.com/dwyl/remote-working
https://github.com/dwyl/learn-jsdoc

#### Security

https://github.com/dwyl/learn-security
https://github.com/dwyl/ISO-27001-2013-information-technology-security
https://github.com/dwyl/learn-cryptography

#### Morning challenges

https://github.com/katkelemen/FuncProgMorninChallenge
https://github.com/des-des/morning-challenges
https://github.com/foundersandcoders/old-morning-challenges/tree/master/2015-10-13
https://github.com/FAC9/notes

#### Readme's  

https://www.gitbook.com/book/foundersandcoders/codingforeveryone/details

#### Workshops/ Projects/ Research topics/ Talks

All course books

https://www.gitbook.com/book/foundersandcoders/fac9/details
https://www.gitbook.com/book/foundersandcoders/fac8/details
https://github.com/foundersandcoders/old-coursebook/tree/master/workshops
https://github.com/foundersandcoders/old-fac5-coursebook
https://github.com/foundersandcoders/old-fac4-coursebook

**Comment by jsms90** [comment]
@bradreeder This must have taken a f*** tonne of time. I'm so grateful. This has saved us so much time :heart:

**Comment by bradreeder** [comment]
In time we should also create some kind of organisation for our mentor-built workshops and morning challenges and move the existing ones to it. We can make them accessible through hyper-links here as well, but I think this would be a better form of organising them, similar to how all the dwyl repos exist under one organisation.

**Comment by msmichellegar** [comment]
@bradreeder Would be nice to have resources organised somewhere centrally, but a lot of people who have written workshops which aren't FAC-specific (like morning challenges) might like to keep them on their own GitHub profiles (unless they're forked).

**Comment by bradreeder** [comment]
https://github.com/mantagen/DOM-manipulation-Challenge

**Comment by Jbarget** [comment]
@bradreeder are we asking that all morning challenges conform to having 2 branches: `master` and `solution`?

I've updated the handlebars one after seeing the newer challenges from FAC9 including them and think it could be good to standardise

**Comment by bradreeder** [comment]
@Jbarget The morning challenges haven't been standardised as far as I'm aware. If you have a suggestion for a standard morning-challenge format I'd open another issue for it. 👍

**Comment by skibinska** [comment]
week 2 testing:

- https://github.com/skibinska/learn-qunit
- https://github.com/skibinska/fizzbuzz
- https://github.com/skibinska/romanizer

**Comment by SavageWilliam** [comment]
### Week 7 - Hapi Templating

Wed morning workshop
[hapi-auth-cookie](https://github.com/SavageWilliam/hapi-auth-cookie-ws) 

__needs review__

**Comment by emilyb7** [comment]
for week 3:

https://github.com/emilyb7/parallel-challenge-github
https://github.com/emilyb7/workshop-APIs

**Comment by bradreeder** [comment]
@Jwhiles 's [error handling workshop](https://github.com/Jwhiles/error-handling)

**Comment by eliascodes** [comment]
We have the [resource index](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/resource-index.md) so retiring this.
