### ISSUE TITLE
Remove linuxbrew

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/master-reference#430]
I overheard FAC11's first SGC and someone was basically talking about how it was unnecessary. Maybe it should go. I think it was me who (semi-randomly) added it to the install list as an optional thing a while back, and it seems to have just stuck around.

**Comment by oliverjam** [comment]
@ZooeyMiller What do you think? Did you end up using Brew much on Linux?

I guess most Linux users already have and are comfortable using a package manager

**Comment by ZooeyMiller** [comment]
I have never used brew for anything, it was a big faff to install and has never been needed.
I think we can comfortably remove it, it can be added back in if the curriculum changes to the point that there is something during the course that will need to be installed with it.
