### ISSUE TITLE
formally state "no es6 before node week"

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#439]
As far as I know, this isn't written anywhere?

It's good to mention the lack of browser support, especially if/when any pre-week-4 workshops have ES6 in them

**Comment by oliverjam** [comment]
I don't think any workshops use ES6, but we are definitely seeing some people use it in morning challenges etc.

It's probably confusing for people who haven't seen ES6 before when we go through solutions, so best to clarify that they shouldn't use it.

**Comment by jsms90** [comment]
@oliverjam https://github.com/Jwhiles/pure-functions-easy-testing/issues/4

**Comment by oliverjam** [comment]
@jsms90 I think that issue was fixed a long time ago. I can't even find the commit where it was changed, but the readme doesn't have an arrow function in

**Comment by eliascodes** [comment]
This is no longer a requirement that we're enforcing.
