### ISSUE TITLE
Update the learning outcomes for week 4

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/master-reference#441]
We need to update the learning outcomes for the week to inform our decisions about changes to the curriculum for the week.

It needs to include the reason we are including the HTML and CSS workshop and update our understanding of the purpose of the week in general.

**Comment by yvonne-liu** [comment]
@ZooeyMiller @jsms90 can someone review my edit? It's not ready to be PR'd yet. Thanks.
