### ISSUE TITLE
explain object identity & pass-by-reference

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/master-reference#447]
In week 2 as the todo app project uses a lot of objects and arrays I answered a few questions about actual copies of objects and references to objects, I ended up giving a brief overview as a talk to the cohort on the morning of the Thursday (using @stevehopkinson's awesome example of a clone of myself to explain it). 

I then made a code example to explain it as well in a repl:
https://repl.it/JQBB/9

If it was thought that this is a worthwhile thing to be in the mater-reference I will make a PR with a version of this removing references to myself (just used me as it continued the metaphor I used in the verbal explanation).

(the code is in a comment below just in case you're reluctant to open repl for some reason)

**Comment by ZooeyMiller** [comment]
```js
//initialise an object
var zooey = {
  height: 186,
  glasses: true,
  hair: "long"
};
// assign that variable to another variable
var zooey2 = zooey;

console.log("original: ", zooey);
console.log("zooey2: ", zooey2);
console.log("are zooey and zooey2 the same?", zooey === zooey2, '\n');

//I change the original object
zooey.hair = "short";

//if you look at the output to the console, both zooey and zooey2 have been changed, as they refer to the same object. 
console.log("original: ", zooey);
console.log("zooey2: ", zooey2, '\n');

//so how can we copy the object without referring to the same object?

//Object.keys gives us an array of strings of the keys in the object passed in as an argument
var zooeyKeysArray = Object.keys(zooey);

console.log("array of keys: ", zooeyKeysArray, "\n");

//initialise an empty object
var zooeyCopy = {};


//loop through the array of keys from zooey, and for each key in zooey add that key value pair to zooeyCopy, just as it is in our original zooey object
zooeyKeysArray.forEach(function(key) {
  //we have to use square bracket notation for objects when using a variable to refer to a key (rather than the literal name of the key)
  //check out this link for more info if you need
  //https://stackoverflow.com/questions/4968406/javascript-property-access-dot-notation-vs-brackets
  zooeyCopy[key] = zooey[key];
});

console.log("original: ", zooey);
console.log("zooey2: ", zooeyCopy);
console.log("are zooey and zooeyCopy the same?", zooey === zooeyCopy, '\n');

//from the console output we can see that even though zooey and zooeyCopy have the same keys, with the same values, the objects are **not** the same

// the zooey copy shaves their head, but this doesn't effect the original zooey object as the are not the same
zooeyCopy.hair = "none";

console.log("original: ", zooey);
console.log("zooeyCopy: ", zooeyCopy);


// nb / advanced. 
// This will not work for objects nested inside objects. Have a think about why, but don't worry about it until your code starts dealing with nested objects.
```

**Comment by eliascodes** [comment]
@ZooeyMiller updated your title 😉 

Also agree, this tends to come up a lot.

**Comment by ZooeyMiller** [comment]
@eliascodes are you a maintainer of this repo? Shall I consider your go ahead as this being okay for me to work on?

**Comment by eliascodes** [comment]
Sure, go for it, I would say maybe stick it in fragments for now.

**Comment by jsms90** [comment]
I've just added the `week-testing` label since this is the week when it came up for FAC11. We may choose to introduce it elsewhere e.g. earlier, so `fragments` is a good shout for now.

**Comment by m4v15** [comment]
Yeah I think its definitely worthwhile to be in MR, it came up in Nazareth yesterday when doing the pure functions workshop and I explained with whiteboard and console logs (not quite as well as this though!) and I guess it will come up over the project days - in which case I will definitely use this repl.

**Comment by m4v15** [comment]
Although I'm totally against you removing any reference to yourself, live forever in the master-reference!

**Comment by jsms90** [comment]
@m4v15 would you suggest putting it in testing week somewhere? Like `resources.md`? Or fragments for now?

**Comment by m4v15** [comment]
Yeah I would say it's more likely to be found and used if it were in testing week 2, a link to it in resources.md would work yeah

**Comment by ZooeyMiller** [comment]
I would argue against it being directly in `week 2`. It doesn't directly relate to week 2. I'd say it makes more sense in `fragments` and then linked in one of the week 2 .md files.

I really don't mind where it goes if something else is decided by community at large.

**Comment by jsms90** [comment]
@ZooeyMiller Yeah, agreed! It doesn't necessarily need to go in testing week.

But `fragments` is just a temporary place for things which don't currently have a place in the curriculum e.g. the old testing week project (stopwatch). Perhaps it belongs here for now, while we haven't figured out where it should go.

But once it does have a place, and is getting delivered in the curriculum, it should go in the relevant week.

**Comment by m4v15** [comment]
Yeah tbh @ZooeyMiller I just meant as long as it doesn't get put in fragments and forgotten about, if it's there and then there is a link to it in week 2 that sounds great.

**Comment by ZooeyMiller** [comment]
Happy to defer to the opinion of the maintainers. I'll make the file, just tell me where to put it :+1:

**Comment by jsms90** [comment]
I reckon `fragments` is fine, while we haven't decided where it should go in the curriculum. Let's just keep this issue open until it has found a place in the actual curriculum?

Thoughts @eliascodes @des-des ?

**Comment by des-des** [comment]
@jsms90 :+1:

**Comment by eliascodes** [comment]
@ZooeyMiller a question on the example: is there a reason you construct a copy using `forEach`?

**Comment by ZooeyMiller** [comment]
@eliascodes do you mean as opposed to just doing:
```
zooeyCopy.height = zooey.height;
zooeyCopy.glasses = zooey.glasses;
zooeyCopy.hair = zooey.hair;
```
?

If so, my reasoning was that doing the `forEach` on `Object.keys` means that the method for copying is reusable on any object with any keys, so give the students an example of something that can be used whenever they need to copy an object using just ES5.

**Comment by ZooeyMiller** [comment]
I have some time now to make a PR with this so if you want me to change anything @eliascodes then let me know and I'll change it.

**Comment by eliascodes** [comment]
I was thinking of `Object.assign`, but this
> using just ES5

clears things up for me. Only alternative is `reduce` but that's conceptually more complicated that `forEach`.

**Comment by ZooeyMiller** [comment]
@eliascodes I :heart: reduce and think it would be good to teach early in the course, but worry it may be a lot to get your head around for people, especially in the context of this little tutorial.

**Comment by eliascodes** [comment]
> it may be a lot to get your head around for people

yeah I just lost an afternoon learning this lesson.

**Comment by ZooeyMiller** [comment]
@eliascodes did you do it during the object pass by reference walk through thing? I don't think that's the best place for it, but I've been thinking maybe in week 1 or two a morning challenge on array methods could be good. Reduce is so good, it would be nice to dedicate some time to it.

**Comment by eliascodes** [comment]
No, we had a morning challenge on array methods that was relatively heavy on `reduce`, but was complicated by ideas about object identity. This was after the mentors took them through your example. 

Anyway, MC's are good; I think we should start with `map` and `filter` since they're simpler to understand. Then `reduce` later.
