### ISSUE TITLE
Add research afternoon to API week 

### ISSUE THREAD

**Issue by lucyrose93** [foundersandcoders/master-reference#450]
I am proposing that we add a research afternoon, based on @eliascodes' [workshop](https://github.com/foundersandcoders/ws-software-design-js) on software design.

The idea is to cover the 4 main topics of this workshop. There will be links to Elias' materials and exercises as a recommended resource for research. 

We think this would be a good way to use the existing resource, but to make the learning experience more interactive. The cohort has already done two research afternoons, so they are already used to how it works. This week originally had a research afternoon, but it was removed to make way for Elias' day-long workshop. Now that we are chunking the topics, we would like to re-introduce research afternoon to API week. 

@jsms90 @eliascodes 

What do you think? If we are happy to go ahead with the research afternoon, I will add the research.md tonight. 

Please see the below: 

***

# Research Topics

Please come up with as many of your own examples as you can!

## Functions as First Class Objects
- What is a first class object?
- How are functions first class?
- How can you store references to functions in variables?
- How can you store references to functions in other data structures?
- Why would you pass functions as arguments to functions?
- What is the data type of a function? Why is this useful?
- Conclusion: Why are first class functions useful?

A [resource](https://github.com/foundersandcoders/ws-software-design-js/tree/master/stage-1/first-class-functions) if you get stuck!

## Closure and Scope
- What is meant by scope (global and local)?
- How does scope work?
- What are the differences between ES5 JavaScript and ES6 JavaScript in relation to scope?
- What is block scoping?
- What is closure?
- Why are closures useful?
- *If you have time*, attempt this [exercise](https://github.com/foundersandcoders/ws-software-design-js/blob/master/stage-1/closures-and-scope/exercise.js) and let us know how you get on!

A [resource](https://github.com/foundersandcoders/ws-software-design-js/tree/master/stage-1/closures-and-scope) if you get stuck!

## Abstraction with Functions
- What is abstraction (in relation to code)?
- How can abstraction be useful?
- Attempt this [exercise](https://github.com/foundersandcoders/ws-software-design-js/blob/master/stage-1/abstraction-with-functions/exercise.js) and let us know how you get on!

A [resource](https://github.com/foundersandcoders/ws-software-design-js/tree/master/stage-1/abstraction-with-functions) if you get stuck.

##The Module pattern
- What is a module?
- How do you create a module?
- What is an IIFE?
- When should/shouldn't I use the module pattern?
- Attempt this exercise and let us know how you get on!

A [resource](https://github.com/foundersandcoders/ws-software-design-js/tree/master/stage-2/module-pattern) if you get stuck.

**Comment by lucyrose93** [comment]
@smarthutza and @JWLD Please could you check the topics and bullet points to see if they make sense?

**Comment by eliascodes** [comment]
@lucyrose93 I'm quite open to trying this out, since the resource is new, but I do have one concern: the topics are intended to build on each other; understanding functions as first class objects helps with understanding closures, and both help with understanding abstraction and the module pattern. 

So you may find that if you jigsaw this out, and one group does the module pattern, they may struggle if they don't already understand closures, for example. But you may decide to structure the research afternoon differently, I don't know.

Anyway, just something to watch out for.

**Comment by lucyrose93** [comment]
Hi @eliascodes That's a really good point I hadn't thought about. I guess we can bear it in mind in terms of how we order our presentations, and we can encourage the different groups to communicate throughout the research time. Personally I've managed to comprehend closures without knowing first that functions are first class objects. So I think it's doable.

**Comment by JWLD** [comment]
Hey @lucyrose93 - I think I'd be happy to give it a shot as a workshop. I think people would learn more from the exercises than research. I might give a few hints, like to use reduce() for the abstraction exercises. But yea, I think I can make it work!

**Comment by lucyrose93** [comment]
@JWLD If you want to do that, then I fully support it. 

I just wouldn't feel confident delivering it myself. But if you can stay on top of the theory and keep it engaging then we should do it. I'll be there to lend a hand as much as I can.

**Comment by JWLD** [comment]
Great, yea happy to give it a go. Thanks!

**Comment by jsms90** [comment]
@lucyrose93 This was a good idea! Especially given the timescale left for delivery and what you have at your disposal. But if you're happy to leave @eliascodes' workshop in & scrap the research afternoon idea, feel free to close this issue.

Really good collaborative effort guys! Thank you for offering your support @JWLD :tada: :+1:

**Comment by lucyrose93** [comment]
thanks @jsms90 will close this now
