### ISSUE TITLE
Mentor Notes Should Be Present in All Workshops

### ISSUE THREAD

**Issue by lucyrose93** [foundersandcoders/master-reference#456]
There is inconsistency here. Sometimes a workshop repo will have notes for mentors, in addition to a solution branch. This is generally incredibly helpful, because it indicates how the workshop was intended to be delivered. 
Can this be standard for all workshop repos? Either to have a separate folder/branch with materials for mentors, or just a mentors-notes markdown file. 
What do you think? 
@bradreeder @des-des @jsms90 @eliascodes @sofer @iteles

**Comment by lucyrose93** [comment]
For example: 
- https://github.com/foundersandcoders/api-workshop/tree/questions

**Comment by lucyrose93** [comment]
Another example I created based on the workshop I delivered this morning: https://github.com/foundersandcoders/Workshop-Software-Architecture-Design/blob/mentor-notes/mentor-notes/mentor-notes.md

**Comment by des-des** [comment]
@lucyrose93 :+1:

**Comment by eliascodes** [comment]
Yeah, I think this is a good idea, but generally against having things on branches. Means that as the workshop is iterated, you have to keep merging master into the notes/solutions branch. I like keeping that kind of stuff in a dotfile or dotfolder in the root, like how I did for foundersandcoders/ws-software-design-js

**Comment by lucyrose93** [comment]
@eliascodes good point about branches. Your approach sounds good to me.

**Comment by eliascodes** [comment]
This is now recommended in the [style guide](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/style-guide.md)
