### ISSUE TITLE
errors in todo-project

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/master-reference#459]
When describing how to make addTodo function, a couple of confusing typos:

```js
var todos = [{ description: 'make tea' }];
var makeEggs = { description: 'make eggs' };
var updatedTodos = todo.todoFunctions.addTodo(todos, makeEggs);
console.log(updatedTodos)
//  [
//    {
//      description: 'make tea',
//    },
//    {
//      id: 0,
//      description: 'make eggs',
//      done: false,
//     }
//  ]
console.log(todos) // [{ description: 'make eggs' }]
```
The line ```var updatedTodos = todo.todoFunctions.addTodo(todos, makeEggs);``` is weird, I think it should just be ```var updatedTodos = todoFunctions.addTodo(todos, makeEggs);``` because the object in logic.js is just called todoFunctions.

Also (and actually the main one) the line:
```console.log(todos) // [{ description: 'make eggs' }]```
Is presumably to show how the original todo array hasn't changed/been mutated. However the original todo array had ```make tea``` so this is very confusing for students.

Finally, and this may not be a problem, but testing with tape means that the logic.js file needs to be exported, which is catching a few people. It comes up in the Roman Numerals code along a bit, but I don't know if maybe it's worth including:

```js

if (typeof module !== 'undefined') {
  module.exports = todoFunctions;
}
```

at the bottom of the logic.js file, with comments to explain it.

**Comment by eliascodes** [comment]
@des-des if you don't have time I can look at this on Friday or Saturday. Unassign yourself if you like.

**Comment by m4v15** [comment]
Cheers, it's not a huge issue, but for difficult concepts annoying typos can definitely make things worse!

**Comment by oliverjam** [comment]
@m4v15 Sorry, we pulled lots of stuff out/moved things around and comments must have been missed here or there.

I did figure that having them catch the `logic.js` having no export issue themselves would be a good learning experience though. The rest are definitely mistakes.

I assume that event listener comment is for if they wanted the entire `li` to be clickable to mark as done? Either way it probably doesn't need to be there.

**Comment by m4v15** [comment]
@oliverjam cool, yeah no worries, it's really well restructured, there's always gonna be a few stuffed missed! 

Yeah I think tbh the module.exports thing is probably a good thing, guess it was just worth pointing out to whoever is delivering it
