### ISSUE TITLE
build challenge 1 - Accessible animated app drawer

### ISSUE THREAD

**Issue by PiotrBerebecki** [foundersandcoders/master-reference#469]
**Link to workshop: https://github.com/Akin909/morning-challenge-animated-app-drawer**

@oliverjam we would like to introduce an animated app drawer as a commonly used feature of front end design and make sure that it is accessible. Have you got any examples that may help us? How about this one: http://www.material-ui.com/#/components/drawer

**Comment by oliverjam** [comment]
@PiotrBerebecki The Material UI doesn't seem to work super well with a keyboard: it moves the focus inside correctly but seems to have no way to close the menu.

I'd say the important things to consider:

- **Keyboard accessibility**: move focus into the menu and trap it there, allow arrow keys up and down, escape to close, return focus to button once closed.

- **Screenreader accessibility**: ensure everything has correct aria labels/attributes so blind users know when the menu is open/closed, what menu item is selected etc. If you're moving focus correctly and using semantic markup a lot of this will work automatically.

This covers everything for a dropdown menu, which is pretty much the same thing (the menu just appears in a different place): https://inclusive-components.design/menus-menu-buttons/

Also this is a great resource to use as a checklist of accessibility features: https://bitsofco.de/the-accessibility-cheatsheet/

**Comment by jsms90** [comment]
@oliverjam Great stuff!! Would you mind popping these links into the "[FAC library](https://github.com/foundersandcoders/london-programme/issues/315)"? :grin:

**Comment by oliverjam** [comment]
@jsms90 Done 😄

**Comment by Akin909** [comment]
@PiotrBerebecki can you please have a look at my [**Initial** draft](https://github.com/Akin909/morning-challenge-animated-app-drawer) of this workshop I'm not sure how much help to provide or how much to add to the drawer itself since that itself isn't really the objective although what I have so far is arguable a little too simple

**Comment by PiotrBerebecki** [comment]
Hey @Akin909, I've just gone through the workshop. It's super fun 💯  

How about the adding the following:

- moving the top navigation links to the right so that they are not hidden by the drawer. Alternatively, we could move the drawer so that it slides in just below the nav bar. At the moment you can still tab through the nav links when the drawer is open.

- creating a `.gitignore` file with `node_modules` etc.

Also, how about making the button stay in one location to limit the animation? This should make it even more accessible.

Would you like me to add these changes?

**Comment by Akin909** [comment]
Hey @PiotrBerebecki for looking at that the top nav definitely needs fixing and I completely forgot about a local gitignore I think I relied on the global one I have without realising. Gonna work on finalising it and the others tomorrow so can do it then but if you wanna have a got at fixing the top nav I can make you a collaborator no pressure as Im doing it tomorrow either way also I quite like the button animation 😆 not sure I wanna remove its a little extra exercise for the cohort re animation

**Comment by PiotrBerebecki** [comment]
@Akin909 Cool, have a go at it and I will review tomorrow
