### ISSUE TITLE
Mentor notes available for the software architecture workshop 

### ISSUE THREAD

**Issue by smarthutza** [foundersandcoders/master-reference#479]
@hibaakel @MohamedOmarii 

There's a [mentor notes branch with a file that should help](https://github.com/foundersandcoders/Workshop-Software-Architecture-Design/blob/mentor-notes/mentor-notes/mentor-notes.md) to deliver the [Software architecture workshop](https://github.com/foundersandcoders/Workshop-Software-Architecture-Design)

**Comment by eliascodes** [comment]
Transient mentor handover notes. Closing.
