### ISSUE TITLE
 Contextualize when you would use a parallel function in the context of API week project

### ISSUE THREAD

**Issue by smarthutza** [foundersandcoders/master-reference#481]
@hibaakel @MohamedOmarii

 FAC11 were given 1 hour to work on this: [Parallel function morning challenge](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-3/morning-challenge.md)

 Sohil and Jack spent an extra half an hour walking through the steps so FAC11 understood how parallel functions work and what they are used for.

**Comment by m4v15** [comment]
Any chance @JWLD or @sohilpandya can give a quick type up of what they used as examples?
