### ISSUE TITLE
Software design workshop - difficult to complete 

### ISSUE THREAD

**Issue by smarthutza** [foundersandcoders/master-reference#483]
@hibaakel @MohamedOmarii 

- [Elias' software design workshop](https://github.com/foundersandcoders/ws-software-design-js) has 2 stages. Only the first two topics in stage 1 are feasible at the moment. 

- Abstraction exercises were too complicated. Students needed a lot of support. 

- Nobody really got to stage 2.

**Comment by eliascodes** [comment]
Superseded by #665
