### ISSUE TITLE
A pattern language for teaching F&C

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#49]
I've just finished an initial write-up proposal in this repo https://github.com/foundersandcoders/A-Pattern-Language/issues/2. My thought is that it could eventually become the mentor's handbook #23 in this repo, used to guide curriculum planning, if there was consensus that it's a good idea.

It's a 5 minute read, if anyone has time to read it and share thoughts here please do so. It's definitely incomplete in terms of the exactness of what the methodology might look like, but I think it conveys the general idea.

**Comment by bradreeder** [comment]
Happy new year -- my gift to the community. 👍

**Comment by njsfield** [comment]
:thumbsup:

If a set of patterns were created for one problem, e.g. code reviewing-

**Large-Scale** - Students will learn to be objective and unopinionated when code reviewing, they will learn to respond quickly/efficiently to issues, and learn to prioritise tasks.
**Middle-Scale** - Time code reviewing sessions at the end of the week to allow adequate time for code reviewing/responding before completing the rest of the days tasks.
**Low-Scale** - Students should code review in pairs, they should fork the other groups repo when reviewing, they should assign issues at the start of code reviewing sessions etc.

(probably needs a lot of editing there…  )

And they were tested in two cohorts simultaneously, if the feedback wasn’t overly positive during the first couple of weeks- when would they be modified/improved? Before the following cohort(s)?

**Comment by bradreeder** [comment]
@njsfield ❤️ . I think it's a balance of wanting to fairly test the hypothesis in multiple contexts before binning it, and adapting to the student's needs. It may depend on the pattern, and how urgent it is.

### Example for science!

A pattern I used when arranging a few days of the weeks was the one mentioned:

> "Every time you run a code-along ensure it is followed with an opportunity for students to practice what was learnt in pairs"

Both first day of node and first day of hapi had a similar structure: intro talk giving context, code-along building a basic server, workshop in the afternoon that covered same material at student's pace.

The consensus of 'user-testing' was that the first day of node was good, and the first day of hapi was bad. We might jump to the conclusion that the hypothesis is wrong, where the problem was that node girl's was a more suitably placed workshop than make me hapi. We now know that the hypothetical pattern above is dependent on the support of other patterns, to do with suitability of workshops. Next curriculum we'd trial the same pattern again with a modified hypothesis.

If hapi day had come first and we'd dropped the pattern because that day was bad, we might not have known that it works in a different context, to refine the hypothesis and test it further.

**Comment by njsfield** [comment]
For this example, how would you refine this pattern? Knowing the suitability/impact of workshops can be hard to predict, could a new hypothesis be-
> "Every time you run a code-along ensure it is followed with an opportunity for students to practice what was learnt in pairs. Factor in free time between the two to answer questions and plan for the pair programming to run over time"

**Comment by shiryz** [comment]
@bradreeder is this something you're still interested in developing?

**Comment by bradreeder** [comment]
Re-open if anyone feels the need to pick this up!
