### ISSUE TITLE
FACN2 feedback on Week 2 for FACG2

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/master-reference#496]
@eliascodes compiled this from Nazareth's SGC and also what we felt as mentors. TLDR at the bottom if you cba to read it all.
### Day 1

[Intro to NPM](https://github.com/foundersandcoders/npm-introduction) 
went well, difference between --save and --save-dev confused some.

[Introduction to testing and TDD](https://github.com/foundersandcoders/testing-tdd-intro) 
Good, no real issues, maybe people would rather just get straight into trying to test rather than talking about it, could add Fizzbuzz here potentially.

[DWYL Tape (TDD) workshop](https://github.com/dwyl/learn-tape) 
Similar to London, a few people got through this quite quickly, those who didn't focussed more on solving it themselves rather than just copy and pasting.

[Roman numerals TDD code-along](https://github.com/foundersandcoders/roman-numeral-tdd-codealong)
Was allocated 2 hours - we did an hour code-along which went quite slowly (having to wait a couple minutes after every line to avoid typos etc), only wrote two tests, so then we let the students pair up and try to do it themselves - think this went a lot better and feedback from the students said they thought it was good. Also gave them a link to the video afterwards.

### Day 2

[traffic light callbacks](https://github.com/foundersandcoders/morning-challenge-traffic-lights) 
went pretty well, I wandered around just poking people in the right direction if they were a bit stuck - only one group finished but I think everyone got a good intro to understanding about callbacks. [Also this from Ollie really helped](https://github.com/foundersandcoders/master-reference/issues/433#issuecomment-312950119)

[Pure functions workshop](https://github.com/Jwhiles/pure-functions-easy-testing)
Not great feedback from this - students wanted a more clear explanation of what exactly they were supposed to do and more resources on what pure functions are. I think the examples are possibly unnecessarily complex which confused a lot of people. Also an explanation of QUnit before they start is necessary.

[Research](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-2/research-afternoon.md) 
Yep, everyone pretty much universally didn't enjoy this research afternoon: 
>topics this week not great, good in theory, some topics are essential, presentations too long

It was probably a lot worse this week anyway as we didn't have an external speaker, and due to the lack of time pressure I guess we let the presentations drag along too much.

We're gonna think about maybe shortening the time of the afternoon if people are really against it, I'm also pushing that if they have too long they could think about making a workshop around the topic - the topics for week 2 don't really lend themselves to this though.

### Day 3

[DOM manipulation](https://github.com/mantagen/DOM-manipulation-Challenge) 
From SGC:
>need more time on DOM workshop maybe do it a day before project as was big part of project

Might want to think about swapping this and callback functions workshop?

**Projects**
The typos in the project that I raised [https://github.com/foundersandcoders/master-reference/issues/459](here) confused a lot of people.
General feedback was that the skeleton code was hard to read and confusing - I actually don't think it is, I think the instructions are pretty clear if you read them carefully and do exactly what they say - I think it might be good practice for arriving onto a code base you haven't written.

People didn't like the fact there were functions they were told (in the instructions) that it didn't matter if they didn't understand. Again I think there's an element of getting used to not knowing how code works as long as you know the input and the output. I think if we were to do it again, I might have them dive right in on the first day of the project, and then at the end of the day for half an hour, just go through exactly how and why the skeleton code is laid out ("the updateState function does this", "the renderState is expecting this and does this"), could do this as a class and try to get some of the students who do understand how it works to answer these questions.

Alternatively this could be done with an overview paragraph or diagram inside the readme.

**Fizz Buzz**

Like in london, really think the students would have benefited from doing fizzbuzz, we should have found a better way to get it in - I think the change to Roman Numerals helped a lot, but because roman numerals was a more complicated problem to solve it meant the tests didn't get focussed on as much. With something as simple as fizzbuzz the tests can be front and centre. 

Could possibly fit it in during the much lamented research afternoon?

**Suggestions**
- Try and include FizzBuzz in anyway possible - we think it works really well as the very first intro to Testing so maybe Day 1 could go: 
    - 10-10:30 intro to npm, 10:30-11:30/45 into to TDD + FizzBuzz, 11:30/45-13:00 Learn Tape, 14:00-16:00 Roman numerals.
    - London said something similar, I should probably have taken it on board more, but was concerned re: the DWYL tape workshop only getting 1 hour - if it comes *after* Fizzbuzz I think 1 hour would be plenty.
- Possibly swap DOM manipulation and Traffic light callbacks to allow the students to digest and think about the DOM before using it a lot in the project
- Be a bit more hands on than usual with the Pure functions workshop, make sure everyone knows what's happening
- Make sure the typos are gone/students are aware of them before they start project.
- Give some sort of overview of how and when the different functions in the Skeleton Code are used

**Comment by eliascodes** [comment]
@m4v15 thanks, take a look @ibraghada and @Alaa-Khattab 😄

**Comment by jsms90** [comment]
@m4v15 I love the idea of capturing SGCs directly in issues!

Perhaps we should have an issue for each week called e.g. "Summer 2017 testing feedback", which contains London, Nazareth & Gaza feedback? Just so that it's all in one place?

**Comment by eliascodes** [comment]
Transient mentor handover notes. Closing.
