### ISSUE TITLE
Weeks 10-16

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#500]
There are several issues that relate to this one including #88 #89 and https://github.com/foundersandcoders/london-curriculum/issues/7. This issue is meant to reflect current practice across all campuses and propose a common approach (at least for now).

**Weeks 10-12 *Group project*** of the students' own choosing split into a directed one-week design sprint followed by a two-week build sprint. 

**Week 13 *Client engagement*** This will look different in different locations. In London, we are likely to have a serious of ideation workshops with different partners (Anna Freud, Yoti, CAST). In Nazareth, we will be running another digital tourism accelerator. In Gaza we are working with Gaza Sky Geeks to run a community accelerator.

**Weeks 14-16 *Client project*** to follow on from the ideation workshops. Again, we will be doing a design sprint followed by a two-week build sprint. This approach is different to what we have previously done in London, but it reflects recent practice in both Nazareth and Gaza.

In all locations, we will be aiming to do paid follow-on work with our clients after graduation, where possible.

**Comment by m4v15** [comment]
During FACN1 / FAC10 there was a week (? or less maybe) set aside for FAC10 to do curriculum planning - it seems like this worked really well for FAC10 but has possibly led to confusion in Nazareth - when FAC10 were doing dedicated and much needed curriculum planning, FACN1 were in the middle of developing projects, so it was difficult to get fully involved. I think has possibly led to some confusion in the change of some weeks for FAC11/N2 for mentors delivering weeks which they were not part of helping develop. It's not really anyones fault at all (possibly Israeli Border police for failing to give @des-des a new visa) but if we can somehow have all the campuses discussing curriculum changes in the same week then it might go someway to avoiding this in the future

**Comment by sofer** [comment]
@m4v15 see also #501

**Comment by des-des** [comment]
@sofer Yeah, jus to echo @m4v15, we do need some time for iterating the curriculum (hopefully we can find a more effective and less time intensive way going forward, that scales over campuses)....

**Comment by eliascodes** [comment]
@des-des @m4v15 foundersandcoders/international#79 may be relevant?

**Comment by rebeccaradding** [comment]
@sofer at what point would it make sense to convene a joint conversation around planning for this section of the course with @jsms90 @mantagen @shiryz and others?

**Comment by sofer** [comment]
@rebeccaradding Nazareth has already followed this model with some success in its first iteration. I agree with @m4v15 that curriculum planning*was not satisfactory in Nazareth and I agree with @des-des that we need to find a more effective, less time-consuming and scalable approach. My first attempt at addressing this is #501. Whatever solution we come up with, there is no reason that we cannot set aside some time during the second half of programme for it. Given our current lack of course resource on the ground in Nazareth, I don't recommend attempting to make any significant changes to the weeks 10-16 there and that we stick, more or less, with what we did last time. I intend to be out there for the workshop part of Week 13 (around the 24th). @nogainbar may also be available then.

In Gaza, the first cohort spent time working on React from Week 10, instead of an open-ended group project, before moving onto their final projects. My understanding is that it is up to @eliascodes @mantagen and the mentoring team in Gaza to decide if that is something that they want to do again, or if they want to follow the model from London and Nazareth for weeks 10-12. We are already deep in conversation with GSG about the "community accelerator" and the client projects, so we probably do not want to make any significant changes to what we are already planning in weeks 13-16, but we will want bring @mantagen up to speed with what we plan to do. I intend to be out there for the client engagement in Week 13 (around Oct 1st). 

In London, I am just about to open an issue in London programme about bringing the last 4 weeks of the programme into line with Nazareth and Gaza. Discussions with our usual partners (CAST, Yoti, Anna Freud) are already underway and I am pretty excited about Weeks 13-16 here.

As soon as course facilitators are ready, we should start discussing the second half of the course at our weekly catch ups. If we need a longer session, we can schedule it.

By the end of October, we will have run this version of Weeks 10-16 at all three campuses at least once (unless any of the campuses decide to diverge in the next few weeks) and we will be in a good place to review whether we are ready to commit this to master reference for future cohorts.
