### ISSUE TITLE
Solution to parallel function morning challenge

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/master-reference#503]
There currently doesn't appear to be one - for completeness should we not have one?

N.B. I might be being an idiot and unable to see it, watch this space.

**Comment by eliascodes** [comment]
@m4v15 you're not an idiot, there isn't one, see #408

**Comment by m4v15** [comment]
@eliascodes Wicked, thanks, see PR - I missed that whole discussion so have just gone ahead a created a file, figure we can just move it and the workshop to wherever when we decide where that is.
