### ISSUE TITLE
Course divergence in Gaza

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/master-reference#506]
So in the interest of transparency, I thought I would record any planned or potential divergence from the master-reference here. I will update this with later weeks if necessary.

I am only considering divergence if I feel it's in the interests of the students based on what I've seen so far, feedback from students and mentors, and given the variable level of preparation here.

Tagging people who might be interested: @foundersandcoders/facg1, @jsms90 @des-des @bradreeder @m4v15 @mattlub @sofer @rebeccaradding @saralk 

### Week 2
* Dropped traffic light morning challenge (to be moved to week 3)

### Week 3
* Drop parallel functions morning challenge (to be moved to later in the course)
* Drop software architecture workshop (too high level for now)
* Cover object identity and pass by reference explicitly (using @ZooeyMiller example in #447 ?)
* Cover array methods, synchronous callbacks in a morning challenge
* Cover async callbacks with traffic light morning challenge (moved from week two)

**Comment by jsms90** [comment]
duplicate #163

**Comment by eliascodes** [comment]
@jsms90 possibly. Would you like me to close this and comment on #163?

**Comment by des-des** [comment]
@jsms90 @eliascodes I think its nice to have your own issue to track divergence.

**Comment by des-des** [comment]
@eliascodes if you can, leave a one liner with some motivation (by dw if ya busy)
