### ISSUE TITLE
create screen recording of setting up es lint

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#508]
FAC11 requested that mentors show them how to set up ES Lint because they've been having problems over the past couple of weeks.

Let's create a screen recording of the necessary steps, so this is shareable across campuses and doesn't rely on word of mouth & get forgotten for future cohorts :+1: 

@ZooeyMiller's:
+ Install ES Lint globally
+ Use a popular styleguide e.g. AirBnB (also suggested by @oliverjam during FAC10)

@des-des tips:
+ Use "standard" for styleguide

**Comment by oliverjam** [comment]
You don't need to install it globally if you're using npm 5.2+. It comes with [npx](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b), which lets you run locally installed modules as if they were global!

Also I'm not sure that Standard is a good styleguide for beginners. It explicitly disallows semicolons, which may be a fine choice to make as an experienced developer but probably isn't something we want to encourage complete beginners to be doing.

**Comment by antoniotrkdz** [comment]
> Also I'm not sure that Standard is a good styleguide for beginners

Yeah, another option is that you can use [semistandard](https://github.com/Flet/semistandard), which has got semicolon, but NOT configuration to mess up with.

I think it one of the best options for beginners.
Also, it works in atom AND vim.

**Comment by jsms90** [comment]
@BartBucknill @maxgerber problems today with AirBnB?

Might just be an issue with setting the config options they actually want? @oliverjam 

@des-des also suggested standard / semi-standard

**Comment by oliverjam** [comment]
Happy to answer any questions. @BartBucknill @maxgerber were they actual problems with the set-up/config or more problems with it not letting you write code the way you wanted to?

**Comment by ZooeyMiller** [comment]
@jsms90 @oliverjam afaik it was problems with the fact we want es5 Front End and es6 back end, and airBnB uses `no-var` rule. So we had to disable that specifically. 

I did try to communicate that if you use airBnB it is very opinionated but I think I didn't go into what that really means enough.

**Comment by m4v15** [comment]
I think unless we want to dedicate a largish period of time to it, we should use standard/semistandard, it's really easy to set up, and then we can direct people to using eslint if they want to look into it more. Also to add to @antoniotrkdz, it's fairly easy to set up on Sublime also

**Comment by des-des** [comment]
:heart:
![image](https://user-images.githubusercontent.com/12845233/28678603-b2476048-72e8-11e7-8d40-bd2637ff099f.png)
:dancing_women: :tada: :taco: pls get everyone do this pls :sparkles:

**Comment by des-des** [comment]
or actually I think semistandard is better for students

**Comment by oliverjam** [comment]
Sorry I've been super busy all week. I'll get the screencast recorded this weekend. Semistandard looks like the way to go (except spaces after function names :nauseated_face:)

**Comment by antoniotrkdz** [comment]
@oliverjam 
>except spaces after function names :nauseated_face: 

Good point.
However, I think the tradeoffs of having semicolons, editor compatibility and ease of setup still outweight it for beginners.

**Comment by oliverjam** [comment]
We now have an ESLint intro that has students use the built-in `eslint --init` command to set up a basic config, so we can definitely close this
