### ISSUE TITLE
Todo project: `sortTodos` needs better explanation

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/master-reference#518]
Students were confused about _how_ they were meant to sort the todos (i.e. by id? by status? alphabetically? etc.)

Simply listing these as options in the comments might help clear up some of this confusion.

Assigning for comments, rather than actually doing the work.

**Comment by oliverjam** [comment]
I assumed this could be pretty open to interpretation. Different to-do apps let you sort in different ways, so there's not really a right answer. This was already quite a prescriptive project so I wouldn't want to be too specific, but maybe listing potential options is a good idea yeah.

**Comment by eliascodes** [comment]
@oliverjam yeah, you're right that they should be free to sort whatever way they want (hence the `sortFunction` input). I think it was probably just that since the other three functions were completely specified, having the last one with more open functionality threw some of them. I think this can probably be fixed with just a few extra words.

**Comment by finnhodgkin** [comment]
I agree with @oliverjam :+1: Without the sort function the project is a bit dull and copy-pastey. 

London had the same kind of questions so a more explicit 'have fun do what you want here' comment would be good.

**Comment by eliascodes** [comment]
@ZooeyMiller @astroash @shiryz could you please let me know if this was an issue at all when you ran the week 2 project? If not I'll close this without action.

**Comment by matthewdking** [comment]
@eliascodes this wasn't an issue in Nazareth as far as I was aware

**Comment by finnhodgkin** [comment]
It wasn't an issue for n3 but only one team ended up implementing sort (they assumed alphabetical)... 🤷‍♀️

**Comment by matthewdking** [comment]
@finnhodgkin I think one team did it by priority as well

**Comment by astroash** [comment]
@eliascodes I think two groups implemented sorting in London, and there wasn't any feedback about this being confusing.
