### ISSUE TITLE
F&C ethos

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/master-reference#52]
We need to have a section on the F&C ethos - it's the building block of what makes us 'us' and we've seen what happens when we fail to highlight it on week 1, day 1 of the course. 

The importance is huge, but it also needs to be *succint* enough to **guarantee that people will read it.**

We will/should pull from @markwilliamfirth much acclaimed talk on community and link to the video of it on youtube (will need to be filmed during FAC10).

**Comment by jsms90** [comment]
To be made based on the resolution of: https://github.com/foundersandcoders/business/issues/40 at the AGM?

**Comment by bradreeder** [comment]
@iteles do we have a link to the recording of @markwilliamfirth 's talk to store here for future reference?

**Comment by iteles** [comment]
@bradreeder We've now filmed it but haven't uploaded it yet, but when we do, I'll be sure to add it, it's invaluable 👍

**Comment by shiryz** [comment]
Will close this issue, as now Mark's talk has been added to the curriculum and the scavenger hunt includes questions that are about the mission/vision of fac.
If anyone feels like this still needs to be addressed please reopen
