### ISSUE TITLE
Operational/ temporal information for each school

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#53]
The following files used to be a part of our curriculum gitbooks:

* [The calendar](https://github.com/FAC8/fac9-gitbook/blob/master/General/calendar.md)
* [Facilities](https://github.com/FAC8/fac9-gitbook/blob/master/General/facilities.md)
* [List of people active in space](https://github.com/FAC8/fac9-gitbook/blob/master/General/mentors.md)
* [List of responsibilities for current mentors](https://github.com/FAC8/fac9-gitbook/blob/master/General/responsibilities.md)
* [The meetup rotas](https://github.com/FAC8/fac9-gitbook/blob/master/General/rotas.md)
* [Who's on each student project team](https://github.com/FAC8/fac9-gitbook/blob/master/week1/teams.md)

As @des-des has raised, information that is specific to the operation of a particular school should not be a part of the master-reference as it's a blue-print for the creation/running of F&C's schools, not the running of F&C, London. 

These files were formerly a part of our student induction. We need to discuss if we need to still have them and if so where they should be stored.

**Comment by rebeccaradding** [comment]
@bradreeder agreed. @sofer and I are discussing how to store location-specific information and will propose a structure by the end of the week.

**Comment by rebeccaradding** [comment]
See: https://github.com/foundersandcoders/london-programme/issues/142#issuecomment-272395374

**Comment by bradreeder** [comment]
Closed. See https://github.com/foundersandcoders/london-curriculum/issues/6
