### ISSUE TITLE
Curriculum overview inconsistent with week definitions

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/master-reference#530]
In the process of raising #529, I saw that the curriculum overview has become inconsistent with the contents of the new weeks. For example:

#### Week 2
* Talks about QUnit, which has been removed
* Talks about waterfall, which has been removed
* Talks about async testing, which has been removed

#### Week 3
* Talks about chrome inspector, which isn't part of the curriculum

#### Week 5
* Talks about commit hooks, which aren't part of the curriculum

#### Week 7/8
* Talk about hapi.js, which has been removed

Either updating the overview needs to be part of the tasks of updating a week, or we should just delete the overview, if its only purpose is to create a maintenance burden.

I favour the latter; I've never really looked at this file before today.

**Comment by jsms90** [comment]
I've been telling mentors to update [the coursebook readme](https://github.com/foundersandcoders/master-reference/tree/master/coursebook) as they go (see this authentication week PR: https://github.com/foundersandcoders/master-reference/pull/532)

Having the `curriculum-overview.md` file as well seems like overkill to me. But see #387

**Comment by eliascodes** [comment]
I think #387 can be addressed without this curriculum overview file. I don't think whatever marginal value this file brings is justified by the maintenance burden. Week topics are covered by the coursebook README, more detailed breakdowns of week contents/topics/learning outcomes can go in the week READMEs.
