### ISSUE TITLE
Guide to contributing

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/master-reference#54]
Going forward, we need to add a guide to contributing. I have mentioned my desire for a template for a proposal to change the syllabus (#8). But I think we need something more nuts and bolts to go along side.

I think we also need something more general purpose. I had a look here https://github.com/dwyl/contributing. But I think we want something *much* shorter (minimum barrier to entry).

I would propose the following rules, these are heavily influenced by my time at [dwyl](/dwyl).

1. check issues / create an issue
2. get the go ahead.
3. commit against the issue
4. make sure your pull request has a description
5. do not merge your own pull requests.

+ emojis ?!!! :smile:

**Comment by des-des** [comment]
I think I might add, since one of the things we want to do with the master reference is document / capture our decision making process, I feel referencing an issue with a discussion in commits is important. Since when looking at the history of a file, you get messages, so if a commit can be follow to a discussion it will always be clear why things were changed!

**Comment by bradreeder** [comment]
In time we'll probably also need a contents page, with instructions on how to update it every time you make a PR in the contributing guidelines.

**Comment by des-des** [comment]
@bradreeder If you are happy with this as a first step I can make a rough now and open a pr?

**Comment by bradreeder** [comment]
@des-des Yeah, sounds good then we can use it with curriculum planning tomorrow. Only thing I would add is something like 'assign to a reviewer once the PR is ready for review' between 4 & 5?

Still haven't worked out how to use the emoji's in commit names and would like to know how! 😄

**Comment by des-des** [comment]
@bradreeder to add emojis just add the text to the start of the commit message. ie bug: `:bug:`

**Comment by des-des** [comment]
@bradreeder mouse over my commit above to see the raw text

**Comment by bradreeder** [comment]
@des-des I will now be making extensive use of this feature. 😛

**Comment by bradreeder** [comment]
We have another discussion open here #155 . Closed #55
