### ISSUE TITLE
Agenda for Tuesday, August 8 standup: Curriculum planning process + Weeks 10-16 content 

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/master-reference#544]
@sofer and @rebeccaradding are meeting on Tuesday, August 8 at 14:30 London time with current and incoming course facilitators @jsms90 @eliascodes @mantagen and the Nazareth team (@shiryz @JWLD @m4v15 @mattlub) to revise the curriculum planning process and to plan for weeks 10-16 across campuses. 

If you are interested in attending the conversation, let me know and I'll add you to the calendar invite. Agenda for each topic is below.

---

**Curriculum planning:**

* Separating the preparation of students from planning of changes to content #501 
* Clearly articulating responsibility at each level - students, course mentors, alumni #558  
   * Discussing the concept of weekly "product owners" #600 
   * Determining who submits PR's for changes to weeks
   * Clarification of master-reference maintenance team
   * Deciding when people should submit PR’s for changes to weeks #601 
* Planning timeline #558 
  * Determining how to incorporate curriculum planning into the second half of the course in each location
  * Determining when and how to prepare mentors for weeks they will lead on the next course
* Defining expectations of lead mentors (assigned to weeks of the course) in each location #365 
* Discussing whether we plan to enable any curriculum divergence, and if so, how #511 

**Weeks 10-16**

* The shape of the curriculum during this section of the course #500 
  * Technology for prototyping #576 
  * Incorporating user-testing into each project #577 
  * Facilitating the creation of self-selected student groups #578 
  * Coordinating the format of week 13 across campuses (with different numbers of client engagement)
  * Incorporating curriculum planning into these weeks in a way that is coordinated across campuses
* Documenting/preparing resources that can be used across campuses #579 
* Determining appropriate resourcing during weeks 10-12 and 13-16 at each campus

**Comment by ZooeyMiller** [comment]
I'd like to be in on this as am hoping to help with LDN post week 8. Thanks.

**Comment by jsms90** [comment]
How about @yvonne-liu ?

**Comment by rebeccaradding** [comment]
@ZooeyMiller @yvonne-liu our next meeting is on Wednesday, will add both of you to the invite if you want to come. We will be discussing #558.,

**Comment by rebeccaradding** [comment]
@eliascodes have you uploaded the minutes from the first meeting?

**Comment by eliascodes** [comment]
@rebeccaradding no I gittered them to Eoin so he could create the proposal/discussion issue around curriculum planning. Want me to open a PR?

**Comment by rebeccaradding** [comment]
@eliascodes would you mind?
