### ISSUE TITLE
make Week Facilitators "code owners" of their week's repos?

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/master-reference#547]
Going through the workshops, the following don't have an obvious maintainer:

* [ ] [TDD Node Server w/ Shot & Tape](https://github.com/foundersandcoders/tdd-node-server-with-shot-and-tape)
* [ ] [Session Management](https://github.com/foundersandcoders/ws-session-management)
* [ ] [Password Management](https://github.com/foundersandcoders/ws-password-management)
* [ ] [Cookie Management](https://github.com/foundersandcoders/ws-cookies)
* [ ] [Intro to Databases](https://github.com/foundersandcoders/intro-to-databases)
* [ ] [Postgres workshop](https://github.com/foundersandcoders/postgres-workshop)
* [ ] [PG walkthrough](https://github.com/foundersandcoders/pg-walkthrough)
* [ ] [PG workshop](https://github.com/foundersandcoders/pg-workshop)
* [ ] [SQL commands intro](https://github.com/foundersandcoders/sql-commands-intro)
* [ ] [Handlebars-Hapi intro](https://github.com/foundersandcoders/handlebars-hapi-intro-workshop)
* [ ] [Modularisation MC](https://github.com/foundersandcoders/modules-challenge)
* [ ] [Node intro](https://github.com/foundersandcoders/Node-Intro-Workshop)
* [ ] [NPM intro](https://github.com/foundersandcoders/npm-introduction)
* [ ] [Roman numerals codealong](https://github.com/foundersandcoders/roman-numeral-tdd-codealong)
* [ ] [testing/tdd intro](https://github.com/foundersandcoders/testing-tdd-intro)
* [ ] [jwt workshop](https://github.com/foundersandcoders/jwt_workshop)
* [ ] [hapi cookie auth](https://github.com/foundersandcoders/hapi-auth-cookie-ws)
* [ ] [hapi auth MC](https://github.com/foundersandcoders/hapi-auth-morning-challenge)

We should fix that. Ideally we would use [code owners](https://github.com/blog/2392-introducing-code-owners) to do it, but at least it should have a `Maintainer: @blah` line in the README.

**Comment by jsms90** [comment]
@eliascodes I'm hoping we can fix this somewhat with "week maintainers" / "weekly product owners" #544

**Comment by oliverjam** [comment]
I should be the maintainer for the npm intro, tdd intro and Roman numerals codealong repos. I think I just forgot to add myself to the readmes when I moved them into the Master Reference.

Unless this process is changing (?) I'll do PRs to add myself

**Comment by eliascodes** [comment]
WF are no longer a formalised role, closing.
