### ISSUE TITLE
password management workshop is too short

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#550]
@eliascodes @mattlub please be aware of the timings used in London:
+ 10:15 - 11:00 presentation
+ 11:00 - 11:20 break + name game with students
+ 11:20 - 12:30 students complete workshop
+ 12:30 - 13:00 go through solutions

@alexis-l8 made a presentation to explain the concepts & answer questions, before students started on the workshop. It wouldn't have taken the students 45 mins to read through the readme
+ [ ] please add your presentation slides to week schedule

**Comment by eliascodes** [comment]
Is the presentation basically just the content of the README in the workshop?

**Comment by jsms90** [comment]
More in depth than the readme & includes a demo of `crypto` in the terminal.

So I guess students can then skip the readme or skim it quite quickly.

But without the presentation, the workshop would _definitely_ not take 3 hours. Even with the presentation, many students had finished early, but used the time before solutions to google things that interested them from the presentation.

**Comment by jsms90** [comment]
@eliascodes Perhaps it would be better to just add to the workshop itself, by [making it more interactive](https://github.com/foundersandcoders/ws-password-management/issues/7) and potentially adding sections to the workshop that were in the presentation but aren't covered in the workshop's readme?

**Comment by mattlub** [comment]
Nazareth:
- 10:10 - 10:40 passwords presentation
- 10:40 - 12:00 students complete workshop (took longer as we had them re-write the tests in tape as they weren't working with jest)
- 12:05 - 12:25 go through solutions
- 12:35 - 12:55 presentation/demo on script injections (SQL, javascript) as it wasn't fully covered last week

**Comment by astroash** [comment]
password management is never too short.

**Comment by ronanyeah** [comment]
Closing and will link to a new issue in the workshop.
