### ISSUE TITLE
self selected projects - can this be building on a project that already exists?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#553]
There has been a question from FAC11 about whether they can pitch a project that they've already created on in postgres week & are continuing to work on for biz dev time ([the FAC library](https://faclibrary.herokuapp.com)).

Pros:
+ Work on a project they're passionate about
+ Useful product for FAC
+ If people outside of their week 6 project team join them, they will get practice of jumping into an existing codebase
+ Those who created the week 6 codebase will get experience explaining their code to new devs on their team

Cons:
+ Potential makes design sprint (week 10) feel less useful
+ Don't get the experience of starting a greenfield project together from scratch, so this makes client projects (week 14) the first time when they experience this
+ Not an equal starting point for everyone on the team
+ Time spent on understanding/explaining the existing codebase that could be spent on designing & coding
+ Pre-existing website means they won't come in to week 10 with a black slate in terms of UX or have an equal opportunity to design the site (makes for a very different experience during week 10)

**Comment by sofer** [comment]
It's self-directed, so it is the students' call. We can offer recommendations, though. One is that they do not work alone. I will be curious to see how disruptive it is to people's enjoyment of week 10 to be applying what they are learning to an existing project.

**Comment by jsms90** [comment]
Yeah. I completely agree! So I guess I'm just saying, what's our recommendation? Perhaps the point is, does this positively / negatively impact on achieving the learning outcomes of the week(s)?

They probably wouldn't need to create a prototype, because they've essentially already built one. But since this was done as a 2 day project, they may want to look at the front end again from scratch anyway. Perhaps it would be best for us to advise this approach, so that they get the most out of week 10 together? @nogainbar @harrydry what do you think?

I'd say the _major_ bonus here is that it's something they're passionate about. Surely, you're always going to learn more if you're working on something you care about? Plus, that's almost certainly going to provide a useful simulation of having an engaged PO.

As part of the "consolidation of course material / exposure to new technologies", it also might be quite interesting for them to convert their code from node core into express (or whatever else they choose to use).

**Comment by des-des** [comment]
I think defo students should be able to pitch whatever they want. And we should advise them as best we can (specific to what they have / want to do) in terms of if we think its a good idea. The main thing I feel is that students should feel, for better or worse, that it is their decision.

There could be a possibility of them stepping back and going through design phase again, and building up their project from scratch, but I feel there should not be a yes / no answer to this and our aim should be to facilitate and advise, but not much more than that.

**Comment by nogainbar** [comment]
I very much agree with that approach in principal @des-des, however, it is important that ideas will be followed from scratch so that you can go through the design thinking flow with them and think about the user experience and solutions to problems. If they choose to take on a one of the small projects they started building then I would ask them to really start from scratch because it may be too disruptive and not in sync with the process that the rest of the classroom will go through with new, unbuilt ideas.

Also, last year we realised that some ideas were not as suitable and we discussed perhaps thinking more thoroughly about it and whether we should help them choose those projects, that for the sake of the exercise, would be more suitable so that they can get the most out of UX UI week. 

happy to discuss more in person

**Comment by jsms90** [comment]
Thanks for your input @nogainbar. The experiences in FAC10 were a large part of why I raised this issue, but I wasn't convinced that I knew the best course of action. Good to hear your take on it! Tbh I agree with everything that's been said above.

This week is really really important if we want to make sure that FAC produces thoughtful developers, who take user-centred design principles seriously in everything that they make. So, IMO, making sure that students really internalise the lessons from this week is incredibly important!

**Comment by jsms90** [comment]
Just been speaking to another team about a FAC app that they're creating for this week's project and would like to pitch after reading week.

Next week, when we intro the 2nd half, I'm sure there will be questions around this. @des-des @sofer @nogainbar it would be great if we could put our heads together before then?

**Comment by des-des** [comment]
@jsms90 yes

**Comment by zurda** [comment]
This may have already been resolved, but personally the design sprint was one of the main benefits of the self selected project IMO. It was a huge difference working for a week on design only without coding, and I feel continuing an existing project might harm the design week of the clients project to follow.

**Comment by m4v15** [comment]
I think this is pretty much outdated and can be closed
