### ISSUE TITLE
API week doesn't have research afternoon - students missing knowledge about REST (& structure of a URL?)

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#554]
In FAC10, it was 5 or 6 weeks before people knew the structure of a URL e.g. a query string. They were introduced to this concept after [this line in the database connection file](https://github.com/foundersandcoders/pg-walkthrough/blob/master/walkthroughSteps/step-5/database/db_connection.js#L7) caused many people some confusion.

FAC11 are still confused about when you should use GET and when to use POST.

"REST" seems like a meaningless buzzword.

These used to be research topics, but we don't seem to have successfully inserted them into the course elsewhere. It might be good to figure out which workshop / morning challenge / other location in the course we want to put this.

**Comment by zurda** [comment]
The [first workshop](https://github.com/foundersandcoders/api-workshop) of the week has this line at the bottom: 

```
REST (Representational State Transfer) is a best practice standard for web interactions. This video gives some background about REST.
```

Personally, I don't remember any specific confusion about this in FAC-15 but it would be helpful to hear feedback about this from @charlielafosse , @shiryz , @m4v15 , @astroash

**Comment by shiryz** [comment]
@zurda I don't think this is covered in detail in week 3 (2 now for Naz) but still, it is not confusing and students understand the concept pretty well
