### ISSUE TITLE
cookies workshop is short

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#557]
Timings used in London:
+ 14:00 - 14:40 Discussion about callbacks based on the content of the password workshop 
+ 14:40 - 16:00 Students completed workshop

@alexis-l8 @bo-bok I only came downstairs at 14:30 after a meeting. Do you have any more detail on what you used 14:00-14:40 for?

**Comment by mattlub** [comment]
In Nazareth:
- 14:00 - 15:30 workshop
- started biz dev early

(feel free to edit my comment @JWLD @Karyum if this was not quite right)

**Comment by jsms90** [comment]
Thanks @mattlub :+1: 

This workshop was by far the best of the 3 and I reckon the timing isn't an issue after all. After holding our mentor retrospective, it seems that only a couple of people in FAC11 got to the "auth check" exercise. So they would probably have benefitted from having the other 40 minutes to work on it.

I would be happy to close this issue now, but I guess we might as well leave it open until Gaza have tried the workshop.

**Comment by ronanyeah** [comment]
Closing, will link in new issue in workshop.
