### ISSUE TITLE
separate the explanatory readme about express from the code along repo

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#560]
@PiotrBerebecki @Akin909 

In the same way that @oliverjam and @finnhodgkin have done for testing week, it might be better to have the summary file about express sitting in a separate repo. (see: [separate repo](https://github.com/foundersandcoders/npm-introduction) for summary on npm).

Then we can timebox for these separately in the week schedule and it is clearer, given that people read at different rates, when the code along is actually supposed to start.

See the [testing week schedule](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/week-2#day-1):
> 10:00 - 10:30 
> Intro to NPM
>
> 10:30 - 11:00 
> Introduction to testing and TDD
> 
> 11:00 - 13:00 
> DWYL Tape (TDD) workshop
>
> — LUNCH —
>
> 14:00 - 16:00 
> Roman numerals TDD code-along - final solution

**Comment by Akin909** [comment]
@jsms90 I've separated out the introduction into a repository called [introduction-to-express](https://github.com/foundersandcoders/introduction-to-express) which i will link to in the time table
