### ISSUE TITLE
each resource should have its own "learning outcomes

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#561]
[As suggested by @des-des](https://github.com/foundersandcoders/master-reference/issues/163#issuecomment-284796719) way back at the beginning of the `master-reference`, each workshop, morning challenge, etc should have its own learning outcomes specified. We have started this, but don't yet have consistency across all resources.

When resources aren't as strong, it is very often because it is not clear exactly what students were supposed to have learned.

**Comment by eliascodes** [comment]
This is part of the instructions for creating new resources. Bringing old resources up to this standard should be done in new issues.
