### ISSUE TITLE
plan & document the prep course in master-reference 

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#562]
:pray: :pray: :pray: :pray: 

Given everything we've been discussing about cross-campus collaboration and the usefulness of having all the _curriculums_ in the same place (`master-reference`), please please can we start documenting the prep course here too?

Our retrospectives and our issues are just as much a part of the documentation as the files themselves, if not more important. Right now we have [these issues](https://github.com/foundersandcoders/nazareth-programme/issues?utf8=%E2%9C%93&q=prep%20course) in `nazareth-programme` and [this one](https://github.com/foundersandcoders/gaza-programme/issues/16) in `gaza-programme` (sort of about prep course)

It would be really good to get [this outline](https://github.com/foundersandcoders/nazareth-programme/issues/231#issuecomment-320684910) into a file, so that you can iterate on it.

Whatever prep course we deliver is bound to have an effect on the course itself. I imagine that further down the line, these will become inextricably linked. Please let's not have these happen in 3 separate locations.

Mentioning everyone in Nazareth who is in discussion on the issues: @Karyum @mattlub @JWLD @Suuuuha @RQ16 @esraajb @yvonne-liu @ZooeyMiller @rebeccaradding @sofer

**Comment by Karyum** [comment]
@jsms90 I'll be adding all the stuff about the Nazareth FACN3 prep-course to a folder inside the [HERE](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/precourse) as soon as possible. all the planning and all the feedback

**Comment by Karyum** [comment]
@jsms90 can we close this ?
