### ISSUE TITLE
Best times for student catch ups?

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#563]
When is the best time for us to be doing student catch ups?

Wednesday and Thursday (or Thursday and Friday in Nazareth and Gaza) afternoons, perhaps?

**Comment by freelancedad** [comment]
Is the feedback that student catch ups are prefered on project days? That works for me, although I do have talks booked in on Monday morning around lunch time. 

Would love to hear thoughts

**Comment by shiryz** [comment]
I believe it is best to stay away from days they are busy workshops, the feedback I got on doing the walks on day 4 was that it's nice to get out of the class to chat.
talking to a student when they're doing projects is the least distracting.

**Comment by jsms90** [comment]
@freelancedad @sofer I just raised this in `london-programme` https://github.com/foundersandcoders/london-programme/issues/353 because I assumed that this would be different, depending on the location.

Do you think I should close that one?

**Comment by jsms90** [comment]
This is the second week in a row that students have been taken away during the morning of day 3, missing the morning challenge & the project planning time with their team.

Please let's make sure this stops happening :pray:  The student who leaves during a morning challenge misses out on that learning opportunity. Then the team either plans the project without them, or those 3 people do nothing until the 4th person returns.

**Comment by sofer** [comment]
Closing this now. See https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/week-schedule.md

**Comment by jsms90** [comment]
I'm not sure that this has been resolved.

@freelancedad how many walks do you take people for during the curriculum?
