### ISSUE TITLE
direct students to use prototyping tools in week 10 instead of HTML & CSS

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#576]
This is directly in line with the Agile principle of getting your vision into the hands of your users as fast as possible, so that you learn at iterate based on feedback as quickly and efficiently as possible. 

I'm told that most groups in FAC10 (except 1) used prototyping tools, rather than coding in HTML & CSS. But the reverse was true in Nazareth.

### London
[FAC10 week 10 SGC]:
> #### Continue
> + Intro to invision and figma

### Nazareth
FACN1's [week 10 SGC](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/fac-n1/week11.md)
> #### Stop
> Using half the time on prototyping

and their [week 12](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/fac-n1/week12.md#use-a-prototyping-tool)
> #### Go
> Use a prototyping tool
> + Prototyping could be shorter, using a tool - doing it with HTML and CSS takes longer, and is often a bit hacky

and [week 13](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/fac-n1/week-13.md#user-testing-at-the-beginning-of-the-week)
> + Mavis: maybe we spent to long on the prototype and everything could have gone back one day & have this user testing day before presentations.
> + I feel like we did the user testing of our prototypes on a Thursday, but then we didn't really look at the issues.
> + We spent 2.5 days getting our HTML & CSS prototypes ready. They spent 2 hours on Adobe & had 15 pages. Just spending a bit of time on learning/using that software would have saved us so much time & then we could have had something with actual functionality to do some user testing with. As it was, we user tested each other's but they weren't finished, so it wasn't very useful

**Comment by jsms90** [comment]
@harrygfox introduced FAC11 to figma and invision today.

@mantagen @shiryz @m4v15 Harry created a screencast while he was delivering it & should be making this available soon :+1:

**Comment by eliascodes** [comment]
done by #616?
