### ISSUE TITLE
3-week project: more guidance on how to plan

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#581]
FAC11 are already asking for this

**Suggestion**
+ [ ] At the beginning of the build sprint - spend morning talking through workflow

Relates #21 

### History
During FAC9, we had a talk from @iteles on workflow e.g. communicating with your PO via github issues, time estimating your work, using DWYL labels effectively, epics & linking issues.

Then, having QA support from @des-des was where most of my cohort first heard of  referencing an issue in your commits & PRs.

[FAC9 week 16 SGC](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-9/cohort-week-16.md#stop)
> #### Stop
> + Committing without referencing issues

[FACN1 week 10 SGC](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/fac-n1/week-13.md#more-emphasis-on-planning---issues-into-joruneys-stories--technical-tasks)
> #### Go
> + Introduce user stories and journeys earlier in course
>    + We haven't been writing them in exactly the right format throughout - it'd be good to get into the habit earlier

FACN1 week 13 SGC
> #### Go
> + [More emphasis on planning - issues into joruneys, stories & technical tasks](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/fac-n1/week-13.md#more-emphasis-on-planning---issues-into-joruneys-stories--technical-tasks)

**Comment by jsms90** [comment]
From FAC11's SGC today:
> #### Continue
> Full planning/sprint mvp design
> + Was good to take timeout to properly plan a the project. Time pressure makes this difficult though.
> + Point was raised about time management as a cohort people feel pressured to stay if their teams feel like they'd like to continue. Important that the course teaches people how manage their time and scope their projects and potentially this should be baked into the course.

**Comment by jsms90** [comment]
### From meeting with Cleo
Action Points:
+ [ ] Produce slides / markdown file on introducing scoping meeting
Note to Cleo: use the house metaphor & get students to draw their versions
+ [ ] Produce slides / markdown file on intro-ing sprint planning (30 min)
@Cleop what do you think of the schedule below for the build sprint schedule?

#### Day 6
10:00 - 10:15 How to run scoping meeting with PO (@Cleop)
10:15 - 11:15 Dev teams run scoping meeting with POs
11:15 - 11:45 Talk on workflow (@Cleop) #581 
11:45 - 13:00 Sprint planning in dev teams
-- Lunch --
13:00 - 18:00 Build

#### Day 7-14
10:00 - 10:15 Stand up
10:15 - 13:00 Build
-- Lunch --
14:00 - 18:00 Build

#### Day 15
How should we timebox user testing & sprint review (including demo)?

**Comment by jsms90** [comment]
@Cleop Hmm, I'm just thinking that the introduction of a scoping meeting after the design sprint doesn't really make sense. We should prob just have the workflow talk & then directly into sprint planning?

@bradreeder are the students having any time after the user testing phase to feed back to their POs in the design sprint?

**Comment by jsms90** [comment]
#### From second hangouts call
@Cleop and I also spoke about a PO meeting that was more like the ones that we did during FAC9 (when we had Ines, Sohil, etc acting pretending to be clients).

Having now observed most of week 10, I'd say that a "scoping meeting" doesn't seem to applicable for the build sprint. Many of the workshops in the design sprint are geared towards honing a grand vision down into an MVP. But some further explanation of client interaction would be useful.

Topics to include in the workflow talk:
+ Writing nice issues
+ Acceptance criteria
+ User journey & user stories into issues
+ No missing details
   + got to be able to be picked up by anyone at any time
   + missing assets
+ Milestones - drag up and down in priority order
+ How to write well-described PRs & how to review effectively #418 
+ In-app notifications on github (#420) 
+ Labels - importing DWYL labels & how to use them
  + Priority, blocked, not using priority 1
+ Client interaction
  + technical labels
  + github as single source of truth

In terms of timeline:
10.00 - 10.15 Introduce the students to the build sprint schedule
10:15 - 10:45 Workflow talk
Then straight into the sprint planning meeting

**Comment by jsms90** [comment]
Having the "Today I Learned" on the last day of the first week doesn't really seem to work. Students are furiously building & it feels like an interruption to their flow.

I would suggest that moving this to the first day of the 2nd week in their sprint would feel more natural.
+ They will have had their first SGC on day 5 the week before & therefore had a chance to reflect on their progress so far.
+ They will also have had the weekend to digest & before doing a show and tell

**Comment by zurda** [comment]
@jsms90  I'm not sure how this is done in other programs, and I can only speak for FAC-15, but I know for us design week was an entire week of learning about the process, talking to DWYL, sprints, learning about different roles (scrum, devops, QA, UX), and practically no coding at all. I suspect this issue might have been resolved, but perhaps design week isn't the same for other programs? Feel free to correct me, I'd love to know how it's done on other programs.
