### ISSUE TITLE
3 week project - introduce students to agile ceremonies (and the Scrum Master role)?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#582]
Some of the [learning outcomes of these 3 weeks](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/weeks-10-12/learning-outcomes.md#agile-development-scrum) are about Agile practices & roles:
> + Awareness of the different roles in Agile Development.
> + Appreciation of what each role adds to a project.
> + Understanding of Agile principles & how they provide benefit to the software development cycle

In FAC9 we had stand ups every morning (during our client sprints). @bradreeder did this happen with FAC10 & @shiryz @esraajb @des-des did this happen with FACN1? But we don't seem to have brought it in to weeks 10-12.

The spring cohorts were requesting more guidance with planning their projects #581. It might help for us to introduce them to Agile ceremonies:
+ Sprint planning
+ Stand ups
+ Sprint review (inc. [project demo](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-12.md#project-demos-after-week-2--joey))
+ Sprint retrospective

Through the ideation sessions with clients, students often hear of the Product Owner role, but we never speak about the Scrum Master. Ceremonies might help to clarify these roles & demonstrate their usefulness to students who may choose to go into them post-course.

**Comment by des-des** [comment]
@jsms90 I think handing out the roles of PO and scrum master would be good. I do think having a scrum master without a PO is a bit weird

**Comment by jsms90** [comment]
### From meeting with Cleo
+ [ ] Cleo to give talk 5-6pm on day 5 of design sprint (Monday 4th September in London) on the Scrum Master role & how it fits into agile ceremonies

@Cleop what do you think of the schedule below for the first day of the build sprint?

#### Day 6
10:00 - 10:15 How to run scoping meeting with PO
10:15 - 11:15 Scoping
11:15 - 11:45 Talk on workflow (turning user journey/stories into issues, DWYL labels, time esimating)
11:45 - 13:00 Sprint planning in dev teams
-- Lunch --
13:00 - 18:00 Build

#### Day 7-14
10:00 - 10:15 Stand up
10:15 - 13:00 Build
-- Lunch --
14:00 - 18:00 Build

#### Day 15
How should we timebox user testing & sprint review (including demo)

Action Points:
+ [ ] Add ceremonies to schedule of weeks 11-12
+ [ ] Produce slides / markdown file on introducing scoping meeting
Note to Cleo: use the house metaphor & get students to draw their versions
+ [ ] Produce slides / markdown file on intro-ing sprint planning (30 min)

**Comment by jsms90** [comment]
@des-des It has been decided that students who pitch an idea will be the Product Owner, but that a different team will be the devs that are building the idea.

I'm not sure how this will work in practice, since POs can't be in both sprint planning sessions. If the PO can't be in the sprint planning session, should there be a Scrum Master?

Should the SM be internal to the team, or should this be alumni? I'm having a hangouts with @shiryz tomorrow to discuss how a mentor/alumnus PO worked in Nazareth pre-reading week.

**Comment by shiryz** [comment]
We have decided that we are going to have a sm for weeks 10-12, this decision was made for all the reasons Jen mentions in https://github.com/foundersandcoders/master-reference/issues/581, and all the outcomes we had from introducing sm in week 8 (https://github.com/foundersandcoders/master-reference/issues/603).

**Comment by Cleop** [comment]
Guide SM ceremonies: https://github.com/dwyl/process-handbook

**Comment by jsms90** [comment]
@mantagen @shiryz @m4v15 Similar to https://github.com/foundersandcoders/master-reference/issues/581#issuecomment-326408267, we will be filming @Cleop's talk & I will be taking notes, with the intention of immortalising this in the `master-reference` in some way, so that it doesn't rely exclusively on any one individual's expertise for future deliveries.

The talk will be based on the repo that @Cleop has linked to in the comment above.

**Comment by iteles** [comment]
I'm late to this party but I would suggest that the scrum master is internal to the team - not only is this the way it should be but will also give the students experience in scrum mastering and a greater knowledge of what they don't know (if that makes sense). 

I would suggest that the content of dwyl's process handbook is pretty comprehensive, constantly improved and not going anywhere; so rather than duplicating this in master-reference and creating a maintenance burden, it may be best to add a link.

**Comment by jsms90** [comment]
@iteles yeah I agree - see @shiryz's issue on "introducing QA and Scrum Master roles" #603
