### ISSUE TITLE
handlebars workshop needs work before it's ready for delivery in Nazareth & Gaza

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#585]
FAC11 experienced lots of problems with [the handlebars workshop](https://github.com/foundersandcoders/express-handlebars-workshop) on day 1.

We continued with this workshop until 6pm and skipped biz dev this week because no one had got anywhere by 4pm.

On day 1, an alumnus who user tested the workshop before the week began told me:
> It took 4 hours for me to complete it

This workshop needs significant work before next week with FACN1. [I've started capturing the problems in issues](https://github.com/foundersandcoders/express-handlebars-workshop/issues)

**Comment by jsms90** [comment]
There was a feeling that students wouldn't be able to complete the [handlebars morning challenge](https://github.com/foundersandcoders/express-handlebars-challenge) on day 3, given how [the handlebars workshop](https://github.com/foundersandcoders/express-handlebars-workshop) went on day 1. 

So on the morning of day 3, @PiotrBerebecki spent 30 minutes going through the handlebars workshop and explained line-by-line what was happening & how handlebars works.

**Comment by zurda** [comment]
Since this issue was opened there were [5 PR](https://github.com/foundersandcoders/express-handlebars-workshop/pulls?q=is%3Apr+is%3Aclosed)'s merged into this workshop (e.g: correcting errors, improving workshop). Can we assume this issue can now be closed, or are there any specific actions to be taken? Happy to help!

**Comment by astroash** [comment]
Outdated issue
