### ISSUE TITLE
express testing workshop needs work before it's ready for delivery in Nazareth & Gaza

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#586]
This workshop required a heavy amount of verbal instruction from @Akin909 and @PiotrBerebecki. FAC11 were ok because of this. But the workshop doesn't stand alone at the moment. This can easily be solved with clearer instructions in the readme, but should definitely be done before FACN2 & FACG2 come to it.

Students didn't begin the workshop itself (i.e. writing tests) until 11:45.

Most of this time was spent on verbal instruction of:
+ using postman (not mentioned in the repo itself)
+ explaining what supertest is and how it works

Then making sure that students were able to complete the setup:
+ questions about what `createdb fac-express` and `npm run build:db` are doing
+ problems with creating the database on at least one student's laptop
+ what students were supposed to put into `server.js`

There isn't much to the setup here. Students should realistically be able to go through this by themselves and then start the workshop without much intervention. But for that to work, the instructions need improvement.

After that, students had problems with running more than one test.

Aside from that, there were lots of questions about what tests students were supposed to be writing.

**Comment by zurda** [comment]
Is there any specific actions to be taken or was this already resolved? Happy to help with a PR if needed!

**Comment by astroash** [comment]
Outdated issue
