### ISSUE TITLE
3 week project - should we provide any guidance on the suitability of the projects they pitch?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#587]
Students generally enjoyed the self-directed element of the 3 week project a lot! So I wouldn't suggest that we curtail this too much. But particularly with respect to getting the most out of week 10, it seems like this may be something we should consider?

### London
[FAC10 week 10 SGC](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-10.md#stop):
> #### Stop
> + Sometimes felt contrived because of the nature of it
> + Should we be pushed in a different direction for this week i.e. not hardware?
> + Or facilitated different projects and find a better way of making it applied

This has also been [raised as a concern](https://github.com/foundersandcoders/master-reference/issues/553#issuecomment-320867643) for FAC11's week 10

### Nazareth
[FACN1 week 10 SGC](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/fac-n1/week11.md#go)
> #### Go
> + More mentor feedback on suitability of ideas for 2 week projects

@shiryz @esraajb @des-des what was the reason for this feedback in Naz?

**Comment by shiryz** [comment]
I believe they wanted to know whether it's worth spending 3 weeks developing the idea they have, or maybe polish it into something feasible.
@m4v15, @edgarfinn do you have anything to add? if I remember correctly you had some comments on this.

**Comment by edgarfinn** [comment]
Regarding the title question "should we provide any guidance on which projects they pitch?" - I'm guessing this is referring to pitching the project idea to the group, in looking for team mates to build it with? If so - I'd say there definitely needs to be guidance there.

Regarding the question of whether its worth spending 3 weeks on the project. Unless the final 6 weeks have changed drastically I would say having the extra time to work on something that could serve as a portfolio piece would be more valuable than a lot of the other course material in that phase of the course, and therefore worthwhile. 

Or have I misunderstood either of those questions? :)

**Comment by m4v15** [comment]
Yeah I mean basically what you said shireen, I think after the initial pitch maybe having an experienced developer talk about how feasible it is to do, or advice on how to shrink it to make it more feasible, is really useful, as I personally found it difficult to know whether or not an app was feasible - I feel like @des-des did this quite a lot for our 3 week projects and it helped

**Comment by des-des** [comment]
@jsms90 yeah I think three weeks was real good for projects in Naz.

There is a difficult balance between not telling people what to do, but also giving them good advise about both the utility, and feasibility of a project.

I agree with mavis I think its important to have an experience developer around to talk through tech stack feasibility etc

**Comment by jsms90** [comment]
@des-des I completely agree. This 3 week project, and the second half of the course in general is an interesting balancing act between providing too much and providing too little.

I think it's definitely worth asking around our alumni base now, because everyone upstairs in London has experience in scoping out projects.

And after we hear the project pitches, we're probably in a better position to figure out who might benefit from support, what form that might take and who might be best positioned to provide it. We'll also have a week between pitching & the start of the build sprint :smile:

**Comment by zurda** [comment]
Is this still under consideration, or was it resolved? 
Personally, I feel we did address wether or not the project is suitable since we could ask the person pitching it questions, and share our thoughts. Since the projects picked are usually the most popular ones, I can't imaging something not suitable being chosen. Is this still an issue/ concern that needs addressing?

**Comment by m4v15** [comment]
I think this can be closed, it seems like everyone was in agreement and it makes sense to me that yes, guidance should be provided. Maybe this needs to be documented somewhere, but also it just happens naturally.
