### ISSUE TITLE
Remove pre-course-materials repo?

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#59]
We may want to remove (or at least mark as deprected:"old-") the pre-course-materials repo after the content has been updated and added here.

https://github.com/foundersandcoders/pre-course-materials

**Comment by bradreeder** [comment]
@jsms90 @njsfield @Cleop is there anything from this resource you want to keep or are you okay for me to delete this?

I don't think we should deprecate it as we should aim to remove wasteful repo's. We also don't want students reading this repo, the precourse here, and getting confused which one is correct.

**Comment by bradreeder** [comment]
exercises.md & tools.md are obsolete.

Resources list has the following we don't have:

* [Internet Intro (Khan Academy)](https://www.khanacademy.org/computing/computer-science/internet-intro)
* [Algorithms (Khan Academy)](https://www.khanacademy.org/computing/computer-science/algorithms)
* [You don't know JS](https://github.com/getify/You-Dont-Know-JS)

Most of the other stuff is in our pre-reqs or mentioned elsewhere?

Potentially useful:

"Everything you will need to know can be researched on:

* [W3 Schools](http://www.w3schools.com/)
* [Mozilla Developer Network](https://developer.mozilla.org/en-US/)"

Will delete if you agree as these resources are still accessible from this comment.

**Comment by jsms90** [comment]
I'm fine with deleting it. You don't know JS looks interesting. If the Khan Academy tutorials are any good, maybe they could be pointed to during the course, if that's helpful? e.g. Internet intro for when people start looking at things like http requests for research day? (No idea what the Khan Academy tutorial has in it)

If we think it is worth pointing out W3 Schools and MDN to people, we could/should do this on www..foundersandcoders.com/apply?

We could include the command line stuff as hints for week 1 research day?

**Comment by jsms90** [comment]
@bradreeder Might be good to do soon, as their precourse has been sent out on gitter now. I'm not sure if I have the authority / access rights to delete it.

**Comment by bradreeder** [comment]
@jsms90 I was just waiting on @njsfield & @Cleop but sure can do.

**Comment by bradreeder** [comment]
Done. Closed
