### ISSUE TITLE
formally introduce pomodoro timer?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#592]
### Why
Many people consider stubborn doggedness when problem solving to be a positive trait in a programmer. When you're deep in code, it's tempting to continue struggling through for too long. For a lot of people, taking breaks isn't something that naturally occurs to them and it's not intuitively obvious that it will actually be beneficial.

Previously, we have always err-ed on the side of allowing students to figure out what works for themselves, because one of the principles of Agile is that teams should be self-organising. But time management is a skill & perhaps FAC could help students by suggesting techniques that could help them?

### What
Point students to a pomodoro timer app.

The mentors and I verbally suggested a pomodoro many times, when the issue came up in SGC. But taking yourself out of your workflow, in order to set a timer on your watch / phone / whatever, doesn't seems to actually happen much.

As far as I know, no one tried this until I actually showed them the app I use, which integrates with github,

### How

So yesterday, I showed FAC11 [toogl's chrome extension](https://chrome.google.com/webstore/detail/toggl-button-productivity/oejgccbfbmkkpaidnkphaiaecficdnfn?hl=en) and today, most teams are trying it.

It integrates nicely with github, by adding a "start timer" button to the issue page itself:
![image](https://user-images.githubusercontent.com/15656538/29407897-fbfc62fa-833d-11e7-9c29-831eab1ed101.png)

Then you can use the button in the URL bar to see how much time has elapsed, so you never even need to navigate away from the page you're on
![pomodoro](https://user-images.githubusercontent.com/15656538/29408382-e3c92fa4-833f-11e7-9b7e-aa82aa5129a1.png)

---

Acceptance criteria:
- [ ] create `pomodoro.md` markdown file which explains the benefits of using a pomodoro timer
- [ ] link to the chrome extension
- [ ] make a screencast of the extension in use i.e. starting the timer from within a github issue & the website in use - how your work is recorded in toogl.com
- [ ] add this as a gif in the markdown file

**Comment by jsms90** [comment]
@Jen-Harris Have you used anything other than toggl?

Do you have any specific advise for @veredrec on what needs to be in the screencast?

**Comment by veredrec** [comment]
@jsms90 sounds good! I'll do that.

**Comment by jsms90** [comment]
@Jen-Harris I think @veredrec needs your help on this one :pray:

**Comment by Jen-Harris** [comment]
__Tomato One__ on mac is excellent! You can download it in the app store:
![tomato one](https://files.gitter.im/Jen-Harris/BP7i/image.png)
and then it's available from your desktop and will alert you when the time is done:
![tomato one](
![image](https://user-images.githubusercontent.com/26116988/31340744-09df5f7c-acff-11e7-8faa-7ddff7d6779c.png)  
There's also __[Fohkuhs](http://www.fohkuhs.com/)__ which is again for mac only but gives full page alerts when you've finished the timer. It's super effective and much more visual ![fohkuhs end page](https://files.gitter.im/Jen-Harris/wKXX/image.png)


In terms of the screen cast I would just briefly show each of the tools? And then have it running throughout the first morning of project time.
