### ISSUE TITLE
Remove @iteles as official reviewer for master-reference

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/master-reference#596]
As someone who has not been able to attend recent Founders & Coders meetings
I suggest I am removed as an official maintainer for this repository
So that there is no dependency on me for reviewing and merging of PRs that I do not have the context to review.

## tl;dr
I knew in advance that from July - end October 2017 I wouldn't have the availability to attend meetings for Founders & Coders campuses and therefore, my reviewing of PRs that come out of these meetings, particularly those of minutes of meetings, is not helpful to the organisation.

Saliently, **I'm concerned that I will start a practice of not being able to attend meetings but then using these PR reviews to voice my insights after-the-fact** (i.e. after hours of discussion have been had and agreements have been made), for example with losing an afternoon a week to curriculum planning (https://github.com/foundersandcoders/master-reference/pull/593). This would be _entirely detrimental_ to the Founders & Coders team and would set a bad (chaotic) precedent for others.

I am **very happy** to be continue added as a reviewer/assignee to PRs and issues when someone feels my input would be valuable, but being the 'default' is unlikely to be good for Founders & Coders.

**Comment by jsms90** [comment]
This is a really good point
> I'm concerned that I will start a practice of not being able to attend meetings but then using these PR reviews to voice my insights after-the-fact

Aside from my "sprint planning" sessions with each set of London mentors, what you are describing is sort of how all of the maintainers operate.

The issue you have linked to is the only other curriculum-related meeting that has happened so far. Once the Curriculum Committee has formed, perhaps we can make clearer guidelines on the role of master-reference maintainer. For now, it isn't hugely clear.

I feel like your removal might be premature?
