### ISSUE TITLE
Agenda: working group for updates to the curriculum, September 5 at 18:30 

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#598]
From [this curriculum planning meeting](https://github.com/foundersandcoders/master-reference/blob/5e41769866e4b76d0a734439dded3fd8f52d55ab/curriculum-planning/minutes/overview/2017-summer-curriculum-process.md) about issue #558 , we have decided to form a working group around updates to the curriculum.

I reckon this meeting should be held outside our 10am-6pm working hours, so that it is open to members of FAC who have jobs outside our campus.

Therefore I suggest **Tuesday 5th September @ 6.30pm** London time - I've put this on the calendar

#### Agenda
1. Charter - remit & purpose #599 
1. Assign a "Product Owner" to each week of the curriculum #600 
1. Timeline for planning & updates #601 
1. Do we need another meeting to discuss concerns that are [`curriculum-wide`](https://github.com/foundersandcoders/master-reference/issues?q=is%3Aopen+is%3Aissue+label%3Acurriculum-wide)?   
i.e. things that have an effect on multiple weeks  

    A few examples:
    + scrapping research afternoon #261
    + mentor-led vs peer-led philosophy #591
    + expectations of mentors
    + how to introduce callbacks #433

**Comment by sofer** [comment]
@jsms90 let's put your proposed date on the FAC calendar.

**Comment by des-des** [comment]
@jsms90, what about people who work inside fac, but do not work outside working hours?

**Comment by des-des** [comment]
@sofer sorry I accidentally deleted your comment.
@jsms90 I think dan said go ahead with meeting

**Comment by des-des** [comment]
@jsms90 I am not convinced by this.
  1. Do we need to establish who is on the commitee before we work out product owners. Also I would call these people facilitators ..
  2. I feel there are some fairly meaty topics in there. I think we should remove point 2, 3 and 6. We should initially focus on moving ahead and getting the working groups off the ground. Or we should have 2 separate meetings
  3. I cannot do 630pm on Thursday, working hours are defo best for me as I try not to work outside working hours. Could we do lunch time so people who are not in FAC can remote in?

**Comment by jsms90** [comment]
1. Are you suggesting that we add another item to the agenda: "members of this committee"?  
There has been no shortage of facilitation in the past. But the real problem is the students being expected to define the direction of the curriculum, hence the "Product Owner" (especially if we're still intending for students to be the ones making the actual updates to the curriculum? I'm still not clear about the intention on this #501)
1. Fair point. Removed 2, 3 & 6.
1. Thursday was clearly too soon. I've suggested Tuesday above and that's the date I've put on the calendar.

**Comment by oliverjam** [comment]
I would be interested in this. After hours is definitely better, unless it's going to be remote.

**Comment by sofer** [comment]
A possible suggestion for de-scoping this meeting a bit further:

_**1. Charter**_ Just for now, let's just describe this as a _"working group"_, to side-step discussion of a charter #599 and instead have a single short remit that we can take 5 minutes to agree when we meet: 

> To support the integration of any changes suggested by each of the campuses into the curriculum.

(although if we can agree the full charter in less than 5 minutes, then 👍 )

_**2. Assign a "Product Owner"**_ Agree with @des-des about the term _facilitator_. Also, it is OK if we don't get 8 facilitators in total. As long as their responsibilities are kept light-weight, one facilitator could work across two or three weeks, if necessary. Also, if we get more than 8, then two facilitators on one week would work, too. I am not sure if we need to agree their exact role and tasks right now #600 (although if we can agree them in less than 5 minutes, then 🎉 ).   

_**3. Timeline for planning & updates #601**_. I agree that this needs some thought and discussion. I have made a proposal https://github.com/foundersandcoders/master-reference/issues/601#issuecomment-326738211

**Comment by rebeccaradding** [comment]
@jsms90 asked me to facilitate, so I have prepared a meeting agenda in a Google document: https://docs.google.com/document/d/115GjNQHJ6DB5a1pxH58c7g6zmN1jyN5BwfAAX2ybKzo/edit#

**Comment by bradreeder** [comment]
Sorry for not being able to attend this - I was in a client meeting. 

My only question is how the updating of the second half of the curriculum will fit into this framework. The mentoring aspects of weeks 11-12 can be picked up by the course facilitator but week 10 is a mentor-led week that is going to need periodic updates in response to student feedback like other weeks. Is it worth this week also having a PO?
