### ISSUE TITLE
Curriculum Committee - "Product Owner" for each week

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#600]
So far, the tasks below have defaulted to the Course Facilitator. But it is deeply problematic for the person unblocking mentors' problems (Scrum Master) to be the same as the person representing the needs of the students and enforcing deadlines (Product Owner).

Each week has a separate "dev team", separate curriculum planning meeting & separate review (SGC). So we might as well have a separate PO for each week. This also has the benefit of spreading responsibility through out alumni network, whilst ensuring that someone is accountable.

The Curriculum Committee should replace the Course Facilitator in terms of providing consistency across weeks.

#### Role
+ Represent the needs of our "users" i.e. students
+ Single point of contact for each set of students working on a week
+ Ensure curriculum updates are completed before next cohort arrives

#### Tasks
+ Work with Curriculum Committee to define learning outcomes of the week
+ Review previous SGCs to ascertain how well the material is helping students to achieve the learning outcomes
+ Prioritise backlog of issues relating to a particular week - should be a reflection of what patterns have/haven't worked for previous cohorts rather than personal opinion
+ Run "sprint planning" session with facilitator & rest of working group - should result in [an epic issue](https://github.com/foundersandcoders/master-reference/issues?q=is%3Aopen+is%3Aissue+label%3Aweek-epic) based on all issues raised previously
+ Review PRs & determine whether issue is satisfactorily addressed
+ Run "sprint review" session with facilitator i.e. mentor SGC

**Comment by rebeccaradding** [comment]
The "week facilitator" concept is happening, so I'm going to close this issue, if that's okay?
