### ISSUE TITLE
Suggested tech stacks in tech-choices.md

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/master-reference#621]
In the `Advised Tech Stacks` section of the [tech-choices.md](https://github.com/foundersandcoders/master-reference/blob/227cb20860ba1479687210f618976a3f46187842/coursebook/weeks-10-12/build-sprint/tech-choices.md) document, there is a Hapi/Postgres/React/Redux suggestion and a Hapi/Postgres/Handlebars suggestion.

I assume this is a hangover from when hapi was in the curriculum? Should this be updated to replace hapi with express in the advised stacks?

The only contributor who is listed on that document is @jsms90 so maybe you could chime in?

**Comment by sofer** [comment]
@ZooeyMiller I think this can be closed.
