### ISSUE TITLE
Week 5 - Node.js 2/2 (cohort feedback)

### ISSUE THREAD

**Issue by mantagen** [foundersandcoders/master-reference#632]
## [Test driven development server](https://github.com/foundersandcoders/tdd-node-server-with-shot-and-tape)
Suggestions: 
- Add a more complicated route to show a practical example of how shot testing
can work on larger projects

## [Error handling](https://github.com/foundersandcoders/error-handling-workshop)
Suggestions: 
The workshop was changed between week 5 in London and week 5 in Nazareth/Gaza 
so some of the comments from the London students may no longer apply. @polyccon 
and @y-zaky could you have a look through the workshop and say if any of 
your comments still apply:

> The file structure was confusing, and should be similar to the structure of 
week 4, the code was not solid (typos) and was complicated, most people didn't 
even finish the exercise... as they felt it was very complicated...

Nazareth / Gaza
- add more in-depth explanations of the differences between error handling 
methods and the best ways to use them
- re-write to more clearly explain _everything_
- allocate more time:

> I recall not completing it and getting a bit lost within it

## [Node shell](https://github.com/foundersandcoders/Node-Shell-Workshop/)
Suggestions:
- shrink the workshop and replace the first part with an error handling morning 
challenge
- rewrite to have more of an emphasis on creating your own custom scripts

or 

- cut the workshop entirely:
> At this stage - node week 2 - people just want to solidify the basic knowledge 
of Node. They don't care about custom scripts or anything which isn't the core 
basics... [...] Nobody used anything from this workshop in their projects
- transfer it to a different week

Note -- after the planning hangout I had a chat with some other people on FACA11
not assigned to the week and they went so far as to say that the Node Shell 
workshop was their favourite of the week and almost the course (@BartBucknill).
It might be worth asking the wider community for their thoughts because there 
was the same division of opinion in my cohort (pretty sure the plan was 
actually to drop it from the curriculum for FAC 11/N2/G2..?)

## [Research afternoon](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-5/research-afternoon.md)
Suggestions:
- Continuous integration
  - Needs more focus
  - Travis and Codecov should __not__ be a research topic, instead it should be 
  a workshop that the whole cohort participates in

I'm not clear on what's going to happen with research afternoons in general plus
we were running short on time, so we left the rest of this section 
for a later discussion.

## [Request module workshop](https://github.com/RhodesPeter/request-module-workshop)
Suggestions:
Keep as is :)

## [The project](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-5/project.md)
> Mainly people struggled on two points, the fact that they wanted an api call 
that continually updates but also the server side validation

Suggestions:
- Either expand the project so there's more time to focus on the huge 
requirements or reduce the total requirements to be suitable for the project 
days 
- "Would be more helpful if the project was more specific"
- Remove Travis and Codecov from the project requirements until there's a full
workshop on continuous integration. 

-----

[Week schedule](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/week-5)

Week facilitator: @finnhodgkin 
FACG2: @Qamar-93 @hanatj 
FACN2: @paulhanna1933
FAC11: @polyccon @y-zaky 

#### SGCs
+ [FAC11 students](https://github.com/foundersandcoders/london-programme/blob/master/stop-go-continue/fac-11/cohort-week-5.md)
+ [FAC11 mentors](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/minutes/node-2/summer-2017-mentor-retrospective.md)
+ [FACN2 students](https://github.com/foundersandcoders/nazareth-programme/blob/master/stop-go-continue/facn2/week5.md)
+ [FACG2 students](https://github.com/foundersandcoders/gaza-programme/blob/master/stop-go-continue/FACG2/)

#### Open issues that relate to your week
[Week 5 issues](https://github.com/foundersandcoders/master-reference/issues?q=is%3Aopen+is%3Aissue+label%3Aweek-node-2)

**Comment by Qamar-93** [comment]
The error handling workshop:
https://github.com/foundersandcoders/error-handling-workshop
no enough focus on what is the best way to handle errors, especially in the case of different and multiple callbacks.

**Comment by hanatj** [comment]
there are many project requirements, so it is much better if we divided these requirements into two weeks. because most of the groups didn't complete the project neither making the tests for it which is an important aim for this week. 

https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-5/project.md

**Comment by Qamar-93** [comment]
more practical exercises on testing to show how much it's important 
https://github.com/foundersandcoders/tdd-node-server-with-shot-and-tape

**Comment by hanatj** [comment]
continuous integration is an important topic and it have to be like an outcome from any of the week workshops. 

https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-5/research-afternoon.md#continuous-integration

**Comment by Qamar-93** [comment]
in lesson 1 in the node shell workshop:
 https://github.com/foundersandcoders/Node-Shell-Workshop/blob/master/LESSON1.md
it's better to make another example of scripts that can be used to make tasks easier such as tests for different files or run the server in different modes (node or nodemon).

**Comment by sajedazoabi** [comment]
The Error handling workshop was good because it offers multiple ways to handle errors, but sometimes I felt lost.
 you should put the pros & cons for each, so we can decide the best.
The research topics were fine because we made a demo and tried the things that we learned.

**Comment by finnhodgkin** [comment]
Hi all :wave:

I've added the SGC notes from each campus for week 5. Have a quick read through to see if there are any issues you've missed in your notes :smile:.

**Comment by Qamar-93** [comment]
### [Error handling workshop:](https://github.com/foundersandcoders/error-handling-workshop)


**Thoughts**
+ Very important 
+ More in-depth explainations of the differences between error handling methods and which is the best way to use. 
+ More explaination on how to handle errors in case of multiple callbacks.

---
### [Testing:](https://github.com/foundersandcoders/tdd-node-server-with-shot-and-tape)
**Thoughts**
+ More practical exercises need to be added.

---

### Continuous Integration:
**Thoughts**
+ [From the afternoon research](
https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-5/research-afternoon.md#continuous-integration) 
+ Very Interesting and useful tool for test checking 
+ it should be added to one of the week's workshop.

--- 
### [Node shell workshop](https://github.com/foundersandcoders/Node-Shell-Workshop/blob/master/LESSON1.md)
**Thoughts**
+ Effective ways to use scripts 
+ Another example of using scripts such as testing files or run server in different modes(node or nodemon).

--- 
### [Project requirement:](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-5/project.md) 
**Thoughts**
+ More focusing on how to finish tests and handle errors. 
+ More specific requirement 

---
### [Morning challenge:](https://github.com/RhodesPeter/request-module-workshop)
**Thoughts** 
+ Important and Clear

**Comment by polyccon** [comment]
### Project Requirements
I think this is the most important item in that list to address. They need to be made clearer (or broader -whichever is more appropriate), as most teams struggled coming up with ideas that fit the requirements and spent half of the time allocated to the project in deciding which idea was a better fit.

### Research afternoon
Unlike the traditional research and present topics to each other, this time round each team split into two pairs which would spent time learning about Travis and the request module, the two topics necessary for the weekly project, which worked quite well as the topics were practical. Some people were unhappy with this form at the time as they required more guidance with the use of the module in particular.
