### ISSUE TITLE
Week 8 - Express (cohort feedback)

### ISSUE THREAD

**Issue by mantagen** [foundersandcoders/master-reference#635]
[Week schedule](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/week-8)

Week facilitator: @des-des 
FACG2: @mahmoudalwadia @aajour 
FACN2: @tyeung2017 
FAC11: @BartBucknill @mineshmshah 

#### SGCs
+ [FAC11 students](https://github.com/foundersandcoders/london-programme/pull/384)
+ [FAC11 mentors](https://github.com/foundersandcoders/master-reference/blob/7923b180af086b3fd2521737b73444a256df0d6f/curriculum-planning/minutes/express/summer-2017-mentor-retrospective.md)
+ [FACN2 students](https://github.com/foundersandcoders/nazareth-programme/blob/master/stop-go-continue/facn2/week8.md)
+ [FACG2 students](https://github.com/foundersandcoders/gaza-programme/blob/master/stop-go-continue/FACG2/)

#### Open issues that relate to your week
[Week 8 issues](https://github.com/foundersandcoders/master-reference/issues?q=is%3Aopen+is%3Aissue+label%3Aweek-express)

Note: this week was created & delivered for the first time based on [this propsoal](https://github.com/foundersandcoders/master-reference/issues/251)

**Comment by mantagen** [comment]
E.g.

**Problem**

'Promises and Fetch' from Research Topics was not relevant to the rest of the week.
https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-8/research-afternoon.md#promises-and-fetch

**Comment by mahmoudalwadia** [comment]
[Introduction to express workshop](https://github.com/foundersandcoders/introduction-to-express) needs to add some new information like:

- The difference between pure working, and working with frameworks, and efficiency for them.

- Compare between the frameworks and difference between them. 

<hr>
Add new workshop, which cares about famous middlewares.
<hr>
Add new workshop, which cares about express authentication.
<hr>

[App Drawer morning challange](https://github.com/foundersandcoders/morning-challenge-animated-app-drawer) not suitable for this week.

**Comment by matthewdking** [comment]
### Express Workshop
From SGC notes:
> + pretty good

**Thoughts**
+ Everyone found this useful and got fairly far through the workshop.

---

### Express-Handlebars Code Along
From SGC notes:
> + good but very long
> + copy and paste from the html

**Thoughts**
+ Overall its very good because gives a really good base understanding.
+ Try to make it within time limit.
+ Overall point on code alongs - have enough mentors floating around to give help to students whilst main mentor is typing.

---

### Create Animated App Drawer

**Thoughts**
+ This should be moved to earlier in the course. Week 1/2?
+ Not related to express or handlebars.

---

### Creating and Testing Express Routes
From SGC notes:
> + problems with workshop
> + issues have been raised PR created
> + good workshop useful


**Thoughts**
+ The workshop would be really useful if there weren't any errors.
+ Some of the instructions weren't that clear. Specifically the instructions for the server.js middleware.
+ Would be nice have some examples of good tests to write.

---

### Express-handlebars morning challenge
From SGC notes:
> + too short
> + maybe slightly harder
> + good explanations and liked the visual of the final results


**Thoughts**
+ Way too short half the cohort finished very quickly. Could go more in depth.

---

### Research Topics
+ Promises and fetch could become a workshop?
+ Express Middleware should have more guidance towards useful and common middleware
+ Session management could be a workshop. This wasn't covered very well in the presentation and is fairly important.
+ Templating and serverside rendering - is this necessary? We are already doing a project on serverside rendering so will alreaddy have a good understanding of this.

**Comment by matthewdking** [comment]
### Addition to Express-Handlebars Code Along
The code along was fairly slow because lots of questions were being asked throughout as we went. Some things become clearer as more of the code comes together. Maybe implementing break points in the code along to ask questions where it is easy to show the answers. At times it felt like the code along was losing momentum and some understanding doesn't come immediately.

**Comment by aajour** [comment]
# Gaza
## Week 8 - Express (cohort feedback)
### [Introduction to express workshop](https://github.com/foundersandcoders/introduction-to-express) : 
#### Thoughts: 
- Should mention the difference between pure working, and working with frameworks, and efficiency of them, with a coding example.

- Compare between the frameworks and difference between them. 
<hr>

### [Express Workshop](https://github.com/foundersandcoders/express-workshop):
#### Thoughts: 
-The workshop is pretty good, but we suggest to add links for external resources.
<hr>

### [Express handlebars workshop](https://github.com/foundersandcoders/express-handlebars-workshop):
#### Thoughts: 
- Should mention another examples of template engines, like EJS, and why we choose the handlebars.
<hr>

### [App Drawer morning challenge](https://github.com/foundersandcoders/morning-challenge-animated-app-drawer) :
#### Thoughts: 
- Good challenge, but not suitable for this week, and should be moved away from this week.
<hr>

### [Express and testing workshop](https://github.com/foundersandcoders/express-and-testing-workshop) :
#### Thoughts: 
- Great one, and with more time will be greater!
<hr>

### [Research topics](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-8/research-afternoon.md) :
#### Thoughts: 
- All the topics are very **important**, so we suggest to turn it into a long workshop like [Node girls workshop](https://github.com/node-girls/workshop-cms)
<hr>

### [Express Handlebars Challenge](https://github.com/foundersandcoders/express-handlebars-challenge) :
#### Thoughts: 
- Lite, easy, short **unlike** the previous challenges :stuck_out_tongue_winking_eye:
<hr>

**Comment by BartBucknill** [comment]
# London

### Express Workshop
From SGC notes:
* The structure of each step building on the last was good and easy to follow.


**Thoughts**
* The structure prevented people from being left behind (a common code-along problem), helpful comments.
* Ex. 6: naming could be improved.
* Ex. 7: mylogger middleware - caused some confusion about purpose. Also need to verify that it works correctly.
* Ex. 11: handleErrors: the code is already complete on master - possible change to make it a code along.

---

### Express-Handlebars Code Along
From SGC notes:
* Steps for completion were not clear.
* Fruit/fruits naming of files confusing.
* Too big.

**Thoughts**
* Set the scene at the beginning, to explain the files you're about to jump into.
* Stronger instructions, like what was said verbally.

---

### Create Animated App Drawer
From SGC notes:
* Was nice to do css for a change.

**Thoughts**

---

### Creating and Testing Express Routes
From SGC notes:

**Thoughts**
* There was confusion about how to structure combined use of supertest and tapetest: this could be clarified.

---

### Express-handlebars morning challenge
From SGC notes:
* Was much easier than the workshop.

**Thoughts**
* Would renaming to 'handlebars helpers challenge' be helpful?
* Could it be expanded?
---

### Research Topics
* One of the topics was Promises: many people on FAC 11 London have expressed in interest in a dedicated time for learning Promises.

### Overall Thoughts / Other From SGC
* Middleware workshop intro - see how it works and how it is used. Also the value of using it in projects.
* Flexibility in choice of project was appreciated (specific to this week).
* Presentation on part II - Was good to hear about what is to come in terms of an explanation of the things post reading week. Could potentially have come earlier.

**Comment by des-des** [comment]
This just went in: https://github.com/foundersandcoders/master-reference/pull/639

**Comment by des-des** [comment]
https://gitter.im/foundersandcoders/week10-autumn-17

**Comment by rebeccaradding** [comment]
@des-des do you have a list of suggested changes that you plan to present to the curiculum working group tonight?

**Comment by des-des** [comment]
## Priorities from previous meeting:
 + Dismantle research afternoon, and place its content around the week
 + Replace css challenge with promises challenge
 + Revamp handlebars workshop

Next steps:
  + Try to find another week to host the css challenge. We thought that having some curriculum time to look at promises would be more important!
 + Go through the handlebars workshop, work out changes required
 + create promises workshop

**Comment by BartBucknill** [comment]
@des-des Regarding dismantling research afternoon, it seems pretty clear from the above campus feedback summaries that a more workshop like approach to the topics was desired. 

Last time we spoke it seemed that the CSS challenge was probably here to stay. Given this, it seems unrealistic to cover each topic in a useful amount of depth. 

How about replacing research afternoon with a new workshop on a single topic, perhaps promises or a session management in express? 

What process would we have to go through to get a decision, and how soon could we come to a decision? Creating a new workshop will of course take some time.

**Comment by des-des** [comment]
@BartBucknill sorry for the slow response! I think November 10th is deadline. Ill chat to everyone else and see if 1. people are happy with this decision and 2, if I can push deadline to Monday?

**Comment by des-des** [comment]
@BartBucknill we already have permission to remove research afternoon.

**Comment by BartBucknill** [comment]
@des-des OK, glad we've got the decision to remove research afternoon. 
When do you think we can decide what to replace it with? We need to know ASAP if we are going to make a decent workshop.

Personally I think a promises workshop would be good. In FAC 11 London most people starting using promises this week or in the projects later, but probably would have benefited from some time set apart for learning them. 

@aajour @matthewdking @tyeung2017 @mahmoudalwadia @mineshmshah any opinions?

**Comment by astroash** [comment]
@BartBucknill there's a promises morning challenge being added to week 7. Feel free to user test if for me ;)

https://github.com/foundersandcoders/mc-promise-me-this

**Comment by BartBucknill** [comment]
@astroash thanks for letting us know.

**Comment by BartBucknill** [comment]
@aajour @matthewdking @tyeung2017 @mahmoudalwadia 
@mineshmshah and I have agreed with @des-des to write an express middleware authentication / session management workshop using passport to take the place of research afternoon (promises are being introduced in week 7). @mineshmshah  is starting work on this, and I am continuing work on improving the express-handlebars workshop.

@mineshmshah did you make an issue for the creation of the new workshop?
