### ISSUE TITLE
Curriculum working group: 2nd meeting

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/master-reference#643]
**Purpose**: to review/approve suggested curriculum updates for each week

**Date**: please fill out the poll https://doodle.com/poll/xazpkapb7n6ng8ng by Friday, September 23

@mantagen @des-des @yvonne-liu @oliverjam @ZooeyMiller @finnhodgkin @jsms90 @sohilpandya @ronanyeah @bo-bok @HilbertSpitzer @ronanyeah @shiryz (and @m4v15  @mattlub and others)

After this meeting, we can set a regular meetings with topics planned in advance so that further polls are less necessary!

**Comment by shiryz** [comment]
Unfortunately, can't do any of these dates so will have to skip this one.

**Comment by rebeccaradding** [comment]
Update: all working group participants are available on Monday and Tuesday evenings. @sofer do plan to attend/have a preference?

@mantagen @jsms90 @m4v15 @shiryz would Monday daytime work for a second hangouts call with week facilitators, so that the final list of changes are ready for a Monday or Tuesday night working group meeting?

**Comment by m4v15** [comment]
Sorry I've got slightly lost in all these discussions, but I think I understand now. By second hangouts call, you mean the students to have another hang outs call like we are doing today? Either monday or tuesday should work fine in that case for us. I guess my only question is what is the aim of the hangouts call? To finalise the list of changes? Can I propose a timeline:

- Today (Wednesday 20th) Groups for each week meet, come up with a list of suggested changes, posted into the initial comment on the week's issue.
- Before next tuesday, Course facilitators in each campus allocate time for students to browse issues for all weeks, reading input from all three campuses and offering comments to other groups.
- Tuesday (26th), the Week Working group has another hangouts call to review the comments from the other students, finalise the changes
- Tuesday evening, the curriculum Working group meet.

I would say tuesday is better as it might be tough to find two timeslots in each of london, gaza, and naz for curriculum planning (one for commenting on other weeks, one for the second hangouts call). However, I think Nazareth can be relatively flexible with its time next monday/tuesday

**Comment by m4v15** [comment]
Also, I think we have confusing naming conventions going on here -  'Week Working Groups' and 'Curriculum Working Group', both of which at various times are being shortened to just ' the Working Group'.

**Comment by jsms90** [comment]
@m4v15 the formulation above sounds fine to me. But when would this happen?
> Week facilitator assigns people in their team (or outside of it) to carry out approved updates/amendments and sets a schedule for completion

Sounds like we need a 3rd hangouts call?

Also how long do we need for this?
>  allocate time for students to browse issues for all weeks, reading input from all three campuses and offering comments to other groups.

**Comment by m4v15** [comment]
>allocate time for students to browse issues for all weeks, reading input from all three campuses and offering comments to other groups.

I would say we don't want to force people to do this to much, but still we should ask for some input from everyone as a means of 'paying back'. I'm going to say an hour or so? I know in Nazareth a lot of the students won't be interested in doing it and I don't want it to end up feeling like a chore. If we say an hour, then that's enough time for everyone to at least do something, and then the students who are more keen and passionate about having input can then continue to do so in their own time?

**Comment by m4v15** [comment]
>Week facilitator assigns people in their team (or outside of it) to carry out approved updates/amendments and sets a schedule for completion

I'm not sure this does need a hang outs call, can happen in a gitter chat? But if so it's something we can talk about during the *Curriculum* Working group meeting on Tuesday evening?

**Comment by rebeccaradding** [comment]
@m4v15 agreed that the terminology has been confusing. Any snazzy suggestions for what to call the "week groups" and "week facilitators" to differentiate them from the curriculum working group?

**Comment by m4v15** [comment]
If there is time I think we should also discuss any non week specific changes that have come up:

[FACN2 hackmd file where anyone could contribute](https://hackmd.io/OzBMBMDMEYQWgAyQQDjgFgJwCNxwIYBsw6G+6C4Kmh6kArAMxA==)
[FAC11's SGC about the overall curriculum](https://hackmd.io/s/B1wgHDH9Z)
@mantagen I don't know if a similar document exist for FACG2, I couldn't find one tho

This might actually be topic worthy of it's own meeting, but I think it if we are going to discuss things like this, it is important we do so quite soon

**Comment by rebeccaradding** [comment]
## Agenda for Curriculum Working Group - 25 September 2017

### Review and approve suggested changes to each week

Each week faciltator presents their group's suggested changes to the curriculum working group; working group provides feedback and authorisation to proceed with suggested updates (10 minutes/week)
- Week 1 #628 
- Week 2 #629 
- Week 3 #630 
- Week 4 #631 
- Week 5 #632 
- Week 6 #633 
- Week 7 #634 
- Week 8 #635

### Possible structural changes (we may not have time to discuss tomorrow, but for next meeting's reference):
1. Expectations of graduate mentors #646
1. Repurposing business development as a time slot for self-organising #645

**Comment by m4v15** [comment]
## Action steps

Rebecca: Deadline for weeks 1-4 should be merged by final day of week 16 in London (week 15 Naz, week 14 Gaza)

- Week facilitators go out and assign tasks by Monday 2nd October
- Week facilitator and maintainers of MR should be assigned to changes
- Week facilitator should be the one to make the final merge
- Campus CF's will find time in the schedules for people to make these changes (a day or 1/2 day once a week)

**Comment by rebeccaradding** [comment]
@m4v15 
- Week facilitators "go out and get volunteers for tasks" might be a tad more accurate, no?
- Did we say maintainers of MR need to be assigned?
