### ISSUE TITLE
Online version of curriculum

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#65]
The [coursebook](https://github.com/foundersandcoders/master-reference/tree/master/coursebook) folder contains, or will contain, the curriculum as it is run in our schools. By making it open-source here we aim to ensure that the maximum number of people can benefit from it, regardless of location.

I think we should create a separate folder for an online version of the curriculum, however; one that is specifically designed for progression by people virtually.

I'd love for us to make a prototype available to those in the coding for everyone community by the end of the next curriculum, as I think the sooner it's created and we have more people using our resources, the faster we'll be able to identify issues and improve them to meet the needs of our students.

Continue discussion here if you have any ideas for how this could be implemented, what structure it should have, what content it should have, how it might relate to application, coding for everyone, etc.

**Comment by shiryz** [comment]
@bradreeder is this something you'd still like to do? or should we close this issue?

**Comment by bradreeder** [comment]
@shiryz it feels unlikely that I'll pick this up and I don't mind it being closed. If it's an idea others are interested in feel free to assign them to it. (Hope you're well!)

**Comment by bradreeder** [comment]
Re-open if anyone feels the need to pick this one up!
