### ISSUE TITLE
Curriculum updates - ACTION STEPS

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/master-reference#651]
As of October 1, all week facilitators have presented their group's lists of suggestions to the [curriculum working group](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/working-group/members.md) (composed of all week facilitators + other interested alumni).

### COURSE FACILITATORS @jsms90 @m4v15 @mantagen:
- Please post (as a comment in this issue) the timeslots when students in each location will be working on updates

### ACTION STEPS:
- Beginning tomorrow (October 2), week facilitators will be communicating with their groups (over whatever medium groups prefer) and getting volunteers to make updates 
- Week facilitators will ensure that someone in their group communicates with the original owner of the material
- Course facilitators have allocated time over the next 2+ weeks for FAC11/FACN2/FACG2 to work on making updates that they have volunteered for
- When making updates, assign your week facilitator + other members of your group to review your PR
- Week facilitator will merge

### DEADLINES FOR MERGING UPDATES:
- **Week 1:** OCTOBER 13
- **Weeks 2-5:** OCTOBER 20
- **Week 6:** OCTOBER 27
- **Week 7:** NOVEMBER 3
- **Week 8:** NOVEMBER 10

**Comment by jsms90** [comment]
London:
- Monday 2nd October 10am-4pm
- Monday 9th October 10am-4pm

**Comment by m4v15** [comment]
Nazareth (times in London time as I think most WF's are UK based (atm...) :

- Thursday 5th October 12:00-16:00 (London Time)
- Monday 9th October 12:00-16:00 (London Time)
- Wednesday 11th October 12:00-16:00 (London Time)
- Monday 16th October 12:00-16:00 (London Time)
