### ISSUE TITLE
Update week 1 schedule readme

### ISSUE THREAD

**Issue by Jen-Harris** [foundersandcoders/master-reference#656]
Relates to epic #628 
A few changes need to be made to the week schedule: 
* add "course overview" talk to day 1 - explain the overview of what gets taught in weeks 1-8 and then weeks 10-16 (#565)
* remove consensus based decision making talk - move into biz dev time as something more interactive (following what @rebeccaradding did in Nazareth)
* move pair programming back into the afternoon, where consensus talk is now, in order to give enough time for course overview talk in the morning
* remove 15 mins "introduce research topics" - move to after lunch
*  add 15 minute introduction on "How to code review" #402
* move presentation prep right before presentations #403
* move cohort SGC after presentations

**Comment by jsms90** [comment]
@Jen-Harris Can you change the `general/week-schedule.md` file too?

**Comment by jsms90** [comment]
@Jen-Harris I somehow missed that you've moved consensus based decision making into day 2

This should be within biz dev time:
> remove consensus based decision making talk - move into biz dev time as something more interactive (following what @rebeccaradding did in Nazareth)

**Comment by shiryz** [comment]
@Jen-Harris can you turn the list in the description to a checklist? there are still some links missing but not sure if it's already been done or if something still needs fixing  :sweat_smile:.
