### ISSUE TITLE
Fix typos in node girls workshop

### ISSUE THREAD

**Issue by dangerdak** [foundersandcoders/master-reference#660]
There are typos in the workshop. We should fix them :)

https://github.com/node-girls/workshop-cms

**Comment by claireinez** [comment]
We'd be really grateful if you would! cc/ @msmichellegar and @minaorangina

**Comment by mattlub** [comment]
@dangerdak see [here](https://github.com/foundersandcoders/master-reference/issues/631#issuecomment-328791552)- @msmichellegar said you are welcome to make issues/PR's on the repo for the workshop itself: https://github.com/node-girls/workshop-cms/issues

**Comment by eliascodes** [comment]
fixed by node-girls/node-workshop#46
