### ISSUE TITLE
Playbook PR/Merge appears to be off...

### ISSUE THREAD

**Issue by nelsonic** [foundersandcoders/master-reference#68]
I want to _share_ the notes on code reviews with someone but could not.
visiting https://github.com/foundersandcoders/master-reference/blob/master/code-reviews.md
shows 404:
![masterref-code-reviews](https://cloud.githubusercontent.com/assets/194400/21996681/5a26c4f0-dc23-11e6-958b-39008df44dc4.png)

relates to #45

**Comment by bradreeder** [comment]
@nelsonic I think it may be because the file has been moved to coursebook/general.
https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/code-reviews.md appears to work.

**Comment by bradreeder** [comment]
Resolved. See comment above.
