### ISSUE TITLE
Update Playbook files

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#69]
The following files in the playbook folder are not a part of the curriculum as it has been taught in recent iterations (afaik). We should aim to not hold onto historic information here and for the master-reference to be reflective of the present blueprint. Discussion should happen as to how they will be used/adapted, or some are potentially outdated:

* [journey.md](https://github.com/foundersandcoders/master-reference/blob/master/playbook/journey.md)
* [mvps.md](https://github.com/foundersandcoders/master-reference/blob/master/playbook/mvps.md)
* [projects.md](https://github.com/foundersandcoders/master-reference/blob/master/playbook/projects.md)
* [schedule.md](https://github.com/foundersandcoders/master-reference/blob/master/playbook/schedule.md)
* [workshops.md](https://github.com/foundersandcoders/master-reference/blob/master/playbook/workshops.md)

The following are outdated and should be removed (imo):

* [before-arrival.md](https://github.com/foundersandcoders/master-reference/blob/master/playbook/before-arrival.md) -- we have a [precourse](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/precourse) in coursebook now.
* [part2.md](https://github.com/foundersandcoders/master-reference/blob/master/playbook/part2.md) -- reflects a curriculum overview that's out of date.

There are other files that have been moved to coursebook that will need to be reviewed/updated like [house-rules.md](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/house-rules.md), [teaching.md](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/teaching.md) & [teams.md](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/teams.md)

**Comment by bradreeder** [comment]
Cool cool, outdated files removed and those in the coursebook are now up to date. At some point the files in the playbook need to be reviewed but it's not a priority for now.

**Comment by jsms90** [comment]
Some of this information is out of date and was confusing to the students when they were browsing the `master-reference` during the [github scavenger hunt](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/github-scavenger-hunt.md).

Remove the following files:
+ [Readme](https://github.com/foundersandcoders/master-reference/blob/master/playbook/README.md) - all the links in the are dead
+ [Developer journey](https://github.com/foundersandcoders/master-reference/blob/master/playbook/journey.md) - out of date. We don't have 5 kinds of dev or a panel any more.
+ [Schedule](https://github.com/foundersandcoders/master-reference/blob/master/playbook/schedule.md) - out of date and we now have the [general week schedule](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/week-schedule.md) as an outline
+ [Workshops](https://github.com/foundersandcoders/master-reference/blob/master/playbook/workshops.md) - out of date

Save (move to `fragments` for now)
+ [MVPs](https://github.com/foundersandcoders/master-reference/blob/master/playbook/mvps.md) - very useful explanation for the second half of the course
+ [Projects](https://github.com/foundersandcoders/master-reference/blob/master/playbook/projects.md) - perfect for https://github.com/foundersandcoders/master-reference/issues/405
+ Pieces of ["teaching"](https://github.com/foundersandcoders/master-reference/blob/master/playbook/teaching.md) would be useful for https://github.com/foundersandcoders/master-reference/issues/365

**Comment by zurda** [comment]
I have just tried all the links in the previous comment, and it appears all of them were removed (please feel free to double check me on that).

I propose closing this issue

**Comment by zurda** [comment]
@jsms90 , @bradreeder, this issue appears to be complete? If I'm misunderstanding something - I'm happy to help out with a PR (I might need some guidence :) )

**Comment by astroash** [comment]
closing as no longer relevant. Feel free to reopen if this is not the case 🙂
