### ISSUE TITLE
Initial meeting to discuss first pass at curriculum as requested by Brad

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/master-reference#7]
@bradreeder As requested, both @nelsonic and I are available for a meeting next week to discuss the first pass at the curriculum as follows:
+ Monday 5th December between 12h00 & 17h30
+ Thursday 8th December from 11h00 onwards

@sofer @des-des Please check if either of the above matches availabilities of yours as well please.

**Comment by des-des** [comment]
Monday is best for me!

**Comment by bradreeder** [comment]
Monday is best for me too, but any of these times are fine for me.

**Comment by sofer** [comment]
I am out of town next week, but I am happy for you to proceed without me. My main points:
- please make sure there is time for two [5% time](https://github.com/foundersandcoders/business/issues/116) slots in the weekly schedule;
- please make sure there is time for weekly team retrospectives (introduced belatedly last week);
- please make sure that we remember to rotate the team after 3 and 6 projects;
- please use mentors' time carefully; let's not create a programme that's too reliant on the presence of alumni or that puts too much on the shoulders of the course facilitator;
- Beyond the 10-week core, let's retain some flexibility about what the curriculum might look like and don't lose sight of the peer-led nature of the programme (i.e. if in doubt, let the students decide!).

**Comment by iteles** [comment]
@bradreeder @des-des Monday at 12h00 for an hour?

**Comment by jsms90** [comment]
Can I come? Even if it's just to listen.

**Comment by bradreeder** [comment]
Hey Jen, the meeting was on Monday I'm afraid. I'll be running a curriculum planning day next Monday with you all in which we'll go over what we've been discussing here, so there will be plenty of chance to get involved shortly.
