### ISSUE TITLE
Update curriculum overview file

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#70]
Upon completion of curriculum planning and final decisions on weeks 9-12, [curriculum-overview.md](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/curriculum-overview.md) should be updated to reflect them so it doesn't confuse the next cohort of students.

**Comment by des-des** [comment]
related: #14

**Comment by eliascodes** [comment]
Has been removed.
