### ISSUE TITLE
Introduce project before research topics on Day 2

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#715]
So that students understand the relevance of the research topics to the project.

**Comment by astroash** [comment]
@sofer can this issue be closed?

**Comment by eliascodes** [comment]
@astroash this change was made for the week 1 and 2 schedules but not for any of the other weeks.

**Comment by astroash** [comment]
@eliascodes do you know if there's a reason this is happening week by week? I'm happy to make a pull request that reschedules weeks 3 - 8 to get this resolved.
