### ISSUE TITLE
Guidance on use of slash mark when writing copy (don't use spaces on the sides)

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/master-reference#717]
Members of this organisation regularly use the **/** mark in written documentation, frequently with a space on either side. For example:

> FAC11 / FACN2 / FACG2 curriculum overview #641

A minor point: slash marks **do not take spaces on either side,** unless they are being used for line breaks in poetry. The above example should read:

> FAC11/FACN2/FACG2 curriculum overview #641

**For reference**
- http://www.thepunctuationguide.com/slash.html
- http://apvschicago.com/2011/06/slashes-uses-and-restrictions.html

**Comment by claireinez** [comment]
Best use of an issue ever :smiley:

**Comment by eliascodes** [comment]
@rebeccaradding under what circumstances can this be closed?

**Comment by rebeccaradding** [comment]
@eliascodes great question - I probably should have had an action point in mind when I opened it. Perhaps the contributing guide needs an appendix with grammar guidance?
