### ISSUE TITLE
Workshops week: overview

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#73]
In the week before the design sprints we currently have a week of workshops. This time around it consists of:
- 3 days on WebRTC with IP Cortex;
- 1 day on mobile gaming with Storienteer.

In future, I propose that we set aside five days for workshops on a variety of topics that we do not have time to cover in the core curriculum. These might include:
- front-end frameworks (e.g. React);
- Progressive web apps;
- Visualisation (D3);
- mobile gaming/VR;
- arduino (Johnny-five)
- WebRTC (e.g. keevio)
- mobile payments (e.g. gocardless)

with an emphasis on what we collectively think is most relevant or interesting and also on the availability of job opportunities with employment partners (it's an opportunity for students and employers to get to know each other).

It might make sense to run this week before any mooted project week, so students can have an opportunity to get familiar with tools that might be interesting for their projects.

Also, I do understand that this week might be bumped or truncated, because of the pressure on time (only 16 weeks!), however that would make me sad, because properly curated, I think this week could be very useful and fun as well as being a great way to engage our alumni, partners and the wider tech community.

**Comment by shiryz** [comment]
@sofer, is this still relevant? if not, can you please close?

**Comment by zurda** [comment]
I'm really glad React week was chosen - very valuable! 
@sofer , is there further action/ discussion needed, or could we close?

**Comment by astroash** [comment]
closing as no longer relevant. Feel free to reopen if this is not the case 🙂

**Comment by sofer** [comment]
Thank you for closing.
