### ISSUE TITLE
Good coding practices

### ISSUE THREAD

**Issue by tbtommyb** [foundersandcoders/master-reference#74]
A lot of the course's content is focused on various tools and how to use them. Discussion on how to write good code has tended to be covered by presentations from external speakers (e.g. the Guardian devs doing a code review).

Mutual code reviewing is useful but limited by what people know to look for (so it was a really cool addition to have previous, more experienced, cohorts also reviewing our projects).

I wonder if we could find a way to cover off good coding practices early on so that our code would stand up well to review (and for potential employers).

I'm thinking mostly of simple things that would be caught by using (and enforcing) a common linter style guide (spaces not tabs, consistent indentation, consistent double/single quotes) and perhaps drawing in some basic ideas relevant to #62 such as trying to write pure functions, avoiding side effects etc (which would make FP easier to grasp when people get to it).

In FAC9's pre-course material it did say to use DWYL's style guide but I don't think this was enforced and we frequently ended up with projects that combined different styles and looked messy.

I thought this might be suitable for #24 week one's toolkit, but it seems pretty busy already. However, I think it should be possible to quickly go through some things that people could bear in mind when reviewing each other's code and so.

**Comment by eliascodes** [comment]
@tbtommyb is this related to #22 or is this slightly lower level?

**Comment by tbtommyb** [comment]
@eliascodes it's lower level and a bit more basic but it definitely fits into the same vein. Perhaps the simple 'how to lint' etc could happen earlier on and discussion of things like pure functions, encapsulation etc could fit in with the design patterns (I'm not sure if that's appropriate, your call).

**Comment by jsms90** [comment]
Great points @tbtommyb !

There was some conversation today about when to introduce a linter. I don't remember what the take away was - which week is doing this?

It seems like crafty @Jwhiles will be getting some FP in there (no, not FP, just pure functions :wink:) for testing week. I'm all for [adding FP](#62)

@bradreeder @nelsonic @iteles what do you think of us putting dwyl's style guide into the 'general' folder?

@Cleop @njsfield and I could make sure that students are pointed to the code-reviews.md file and that we verbally go through this with them before they start? I've been thinking that it might be a good idea to chromecast the bullet points under "Guide: Ask yourself (the code author) the following Questions" while they're doing their first code review, just for reference. But maybe we could cast a shorter version of the list, and then add various points in as they become relevant.
e.g. This means nothing to them until they're in week 4+
> Do the tests pass? (following the instructions in the repo's readme) e.g: npm i && npm test (for node.js based projects...)

Tom, was there anything else that you think Week 1 could do to help?

**Comment by shiryz** [comment]
We now have students install prettier in week 1/2 (depends on the cohort), and then a linter in week 5. Other coding practices are mentioned during code reviews and some of the workshops.
Will close this issue, but if anyone feels it's still relevant please reopen
