### ISSUE TITLE
Duplicated fizzbuzz workshops

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/master-reference#741]
There are now two fizzbuzz workshops (see #727).

Ideally these should be consolidated.

**Comment by astroash** [comment]
There was feedback from the latest fizzbuzz workshop that it is too easy as it gives all the answers [sgc link](https://github.com/foundersandcoders/london-programme/blob/master/stop-go-continue/fac-12/week-2.md#workshop-with-all-answers)
