### ISSUE TITLE
Replacing week 7 callbacks morning challenge with promises

### ISSUE THREAD

**Issue by astroash** [foundersandcoders/master-reference#742]
Week 7's [current morning challenge](https://github.com/foundersandcoders/mc-do-this-then-do-that) was added last cohort as students were struggling with callbacks, however feedback was that it was too easy. 

I suggest that this is replaced with a  promises mc that serves as an intro to promises syntax. I have made a repo here so feedback appreciated ❤️ 

https://github.com/astroash/mc-promise-me-this

**Comment by ronanyeah** [comment]
I think Week 7 is one of the hardest/most info heavy weeks on the curriculum, so introducing one of the trickiest things to understand in JS as a morning challenge is not a good idea.

Maybe another (earlier) week would be better suited for this.

**Comment by morkeltry** [comment]
How do we go about suggesting it to an earlier week, which would be another group's responsibility. FAC11 gitter room, perhaps?

**Comment by astroash** [comment]
I don't agree with week 7 being an overloaded or difficult week, personally I found it the most relaxed week post node:

**Week 4** - first intro to backend and everything being async
**Week 5** - the pain that is error handling and still `wtf is node?`
**Week 6** - databases and learning a new language to query SQL databases
**Week 7** - adding on preexisting knowledge with cookies & hashing passwords
**Week 8** - redoing everything you thought you knew with an express overhall and new way to write html

**Comment by maxgerber** [comment]
A lot of FAC11 felt that promises should be taught at some point in the course, and we currently have a slot free in Authentication week. My personal opinion is that it would go well here, but if it moves somewhere else, the two questions we'd need to answer are:
1. Where would it go instead?
2. What could take its place?

**Comment by ronanyeah** [comment]
Thanks everybody, I hear you, I'm trying to get others on the Curric group/other campuses to weigh in. 👍

**Comment by ronanyeah** [comment]
Relevant related issue: https://github.com/foundersandcoders/master-reference/issues/262

Apparently promises are a research topic?

Similar to what @jsms90 [says](https://github.com/foundersandcoders/master-reference/issues/262#issuecomment-321628534), I don't think its right to casually drop in something like Promises.

**Comment by mattlub** [comment]
@ronanyeah I don't see a problem with it, I think promises are fairly easy to get using at first, and then later when you come across difficulties you might find out properly how they work. So to me a morning challenge seems not a bad idea.

Agree it may be problematic if people are still confused about callbacks/async though. @ronanyeah any other reasons why you don't think it's a good idea?

**Comment by eliascodes** [comment]
The promise API is quite small.

Promises are also not at all necessary, so it's not as though we're introducing vital information in the morning challenge. Doing it this way sounds primarily a way to partially demystify the idea for when the students encounter it further in the future. I wouldn't expect anyone doing the morning challenge to actually properly understand promises afterwards.

As with most things, I think the downsides can be mitigated by appropriate framing.

**Comment by ronanyeah** [comment]
> I think the downsides can be mitigated by appropriate framing.

I like that.

Another thing. The reason this callback workshop was introduced, is because apparently one of the cohorts was having trouble with callbacks.

And this change would be, 'no actually, we're SO ok with callbacks that we're going to move completely past them to a different async approach'.

No problems there, but it does indicate a level of volatility and 'churn' that is not ideal in a 'curriculum'.

Should morning challenges even be on the curriculum? Or should we have a bank of them that are drawn from on a weekly basis depending on the per-cohort, per-week needs?

**Comment by ronanyeah** [comment]
Imagine this: Students vote every Friday on what they would like the 3 morning challenges to be on the next week.

**Comment by astroash** [comment]
@ronanyeah I think it is an interesting idea, is it worth opening this up in another issue?

**Comment by eliascodes** [comment]
> No problems there, but it does indicate a level of volatility and 'churn' that is not ideal in a 'curriculum'.

Tend to agree

> Should morning challenges even be on the curriculum? Or should we have a bank of them that are drawn from on a weekly basis depending on the per-cohort, per-week needs?

I'm attracted to this idea tbh.

**Comment by ronanyeah** [comment]
@astroash Yeah I think so, but no rush, it'll can a proposal for the next round of changes. I was intending [this PR](https://github.com/foundersandcoders/master-reference/pull/636/files#diff-59cf1dbbeb2af586ebf75e55de0d62fd) to be the start of creating the resource stockpile.

**Comment by ronanyeah** [comment]
So action steps:
- I'd like to get these merged first (https://github.com/foundersandcoders/master-reference/pull/636, https://github.com/foundersandcoders/master-reference/pull/668)
- Then we can add the promise MC to the resource list (and add it to the FAC org if @astroash is OK with that)
- Then we can put it in week 7 as there seems to be a fervent appetite for it 😄
- And we can return to the MC/curriculum issue in due course

**Comment by astroash** [comment]
I've transferred ownership of the repo to FAC. If anyone is free to user test it would be super appreciated!

https://github.com/foundersandcoders/mc-promise-me-this
