### ISSUE TITLE
When to introduce linters?

### ISSUE THREAD

**Issue by astroash** [foundersandcoders/master-reference#745]
In FAC11 linters were introduced during week 4. I was wondering if there are any suggestions on the best time for this to be introduced and whether, if there's agreement on a week, this should be timetabled in master reference (or decided individually in each campus?).

**Comment by shiryz** [comment]
@astroash I feel like introducing linters after the introduction to node seems fitting, so week 4 or 5, I would suggest week 5 day 3 before they start working on projects.

**Comment by ZooeyMiller** [comment]
Week 5 should work. The introduction will probably be smoothed out by having a proper resource for set up and time slot to do so.

**Comment by m4v15** [comment]
Yeah I think having a proper resource is quite important, and also clarifying exactly what we mean by introducing it, they way I see it their are a few different things going on:

- Having and configuring a linting tool on people's computers
- Setting up atom/editor with a linting plugin to show any linting errors in the editor.
- Having a linting script within a project, possibly along with a pre-commit hook

Should all three of these be introduced at the same time?

**Comment by ZooeyMiller** [comment]
One thing that would make code review easier would also be to have a standard FAC set up for linting. If we decide on a style guide, then we can just hold students to that style guide, would mean we didn't have as many style based issues. 

re @m4v15 
I think all of your points should be included in a linter guide, but I don't think a pre-commit hook would be good to introduce at this point. I think for the students who are feeling comfortable in week 5 pre-commit may be easy to get your head around, but for people maybe feeling a little less comfortable it may just feel like a stressful extra.

**Comment by astroash** [comment]
>One thing that would make code review easier would also be to have a standard FAC set up for linting.

It made life easier in FAC11 being told to use `airbnb config`. We didn't have to discuss what style guide to use so setup was easier whilst we were still getting used to things . Then in the second half we started using `semi standard` as we wanted something less strict. I don't know enough about individual style guides to have preferences but starting off with a **highly recommended** one was useful.

We'll be introducing this in London on Wednesday, so I can make an md file with all the suggestions we have here and in #758.

As a starting point I can include:
- global installation of eslint
- local configuration of linter for a project
- text editor packages to include _(this should be setup from precourse)_ 
- a sentence on learning from manually changing syntax

The only thing to check is what `config` everyone would prefer to start with?

**Comment by ZooeyMiller** [comment]
@astroash that sounds like a sensible subset of information. Maybe introduce semi standard rather than airbnb to start with if y'all preferred it. 

airbnb is so strict that some people just end up not fixing the errors which obvs really misses the point.

**Comment by m4v15** [comment]
Yeah I agree no need for a pre-commit hook at all, was just bringing it up as a thing that could potentially have been introduced. @astroash those look great to me and yeah I think semi-standard seems like a good option. Happy to help you introduce them on wednesday if you want

**Comment by astroash** [comment]
@m4v15 that would be awesome! Just had a play around at initialling eslint and `airbnb` is easier to install as you can pick it from the option of `popular style guides` whereas for `semistandard` you need to install a bunch of npm installs to get it running then set up your `.eslintrc` file.

I think to start with it might actually be easier to use `airbnb`

**Comment by m4v15** [comment]
Lol, yeah I was just doing the same thing actually and came up with the idea of using the 'standard' style guide and then using that opportunity to talk about the `.eslintrc` file and adding in the rule
` "semi": [2, 'always'],` to turn it into semi-standard, and can then talk about it being totally configurable.

**Comment by m4v15** [comment]
But yeah or can use airbnb, and talk about configuring it seperately, no huge difference.

**Comment by astroash** [comment]
![linting](https://user-images.githubusercontent.com/14337958/33060979-3e87aa40-ce92-11e7-881a-bc3360e5be2a.gif)

**Comment by m4v15** [comment]
![terminal-lint](https://user-images.githubusercontent.com/23310908/33074121-eea88d8e-cebc-11e7-85f5-35b9cdba4a1d.png)
