### ISSUE TITLE
write scripts to automate the precourse installation process?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#747]
## Background
Every cohort has to [install the same pieces of tech](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/precourse#installation-list) in order to get started on their first day at FAC.

We hold an installation party for each cohort. Not everyone is able to physically come to FAC. Even for those who do, our mentors are not always able to help. Particularly when they aren't familiar with the student's OS.

Information about the struggles that each student experienced is not passed on well. Each subsequent cohort probably repeats the same struggles unnecessarily.

## Why
We assist some people at the installation party, but not every student is able to attend. Some people still have issues when they arrive on day 1. Often, students continue to experience issues well into the first 8 weeks & this can hinder progress during workshops.

When students are still having trouble with their environment whilst trying to complete workshops, this takes away time from the curriculum when they could be focusing on the learning outcomes of the week.

Sometimes, when problems have taken to long to sort out during a workshop, students are encouraged to pair with someone whose environment is set up correctly. These students are then left to sort this out their computer in their own time. In the worst case scenario, these students can fall behind.

## What
Automate the environmental setup

## How
I've asked someone in the DevOps team at Beamery to help me write this.

@eliascodes @des-des @ronanyeah @ZooeyMiller @anyone_else Thoughts?

**Comment by astroash** [comment]
An install script sounds hella cool but I kinda think learning to install things is all part of the journey. Reading docs and online trouble shooting is a skill that all devs need to learn n without it you run the risk of students not getting this exposure and not knowing how things work.

**Comment by eliascodes** [comment]
Agree with @astroash. Having to actually engage with and try to understand your environment is no bad thing, and week 1 is probably not the worst time to be doing that.

Which specific parts of the install list are consistently a problem? As far as I remember, actually installing Linux and/or setting up SSH keys. Not all that much can be done to automate those. Beyond that, everything's typically fairly straightforward.

**Comment by ZooeyMiller** [comment]
I agree with the sentiments already expressed. Learning to install things, especially from the command line is really important, and I don't think we should automate that for students.

**Comment by jsms90** [comment]
Thanks guys. Totally agree with everything you're saying actually and it's much more in the spirit of learning fundamentals and fully understanding everything you're doing. Setting up your environment shouldn't feel like magic, any more than writing code itself 👍 

If there do continue to be any problems with people's environments not being set up, perhaps a better solution would be to set aside time during week 1 or at the beginning of each relevant workshop so that no one is left struggling.
