### ISSUE TITLE
Getting alumni in for morning challenges

### ISSUE THREAD

**Issue by emilyb7** [foundersandcoders/master-reference#75]
During FAC9 most of our (excellent) morning challenges were run by alumni (FAC <= 7), rather than by the week mentors.

Is there are system for getting people in? Is anyone following this repo keen to get involved?

Specifically, we are looking for someone to help us introduce parallel functions during a morning challenge in Week 3.

But I guess mentors for other weeks during FAC10 might also be keen to get extra help with morning challenges?

**Comment by eliascodes** [comment]
@emilyb7 There's no system beyond asking.

I could run one or two, but preferably not in week 3 since I'm already doing the workshop then 👍
