### ISSUE TITLE
From what point should we introduce/allow automated code formatting?

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/master-reference#758]
If we introduce linters in week 5 as #745 suggests, should we also use this time to introduce automated code formatting? 

I used `fix on save` with ESlint during the first 8 weeks, and then after that started using [prettier](https://github.com/prettier/prettier), and then when writing elm, `elm-format`. [In week 1 we introduce `atom-beautify`](https://github.com/foundersandcoders/accessibility-challenge/blob/master/README.md) which is the same thing. If we're comfortable introducing this week-1 I see no reason why we should stop people using automated code formatting if they're found it themselves. 

I think automated code-formatting is sensible and a good tool to use for consistency in a project, and readability. However, I do also think students should learn to format their code themselves. If people are using some kind of automated formatting before they come to FAC, I don't think we should stop them from using it.

Perhaps week 5 is a time to introduce `fix on save`/prettier to students as well? I remember there being some contention about this when it was brought up last cohort so that's why I raise a separate issue about it.

**Comment by m4v15** [comment]
Has it been decided when linting get's introduced yet? Maybe could be a good idea to have linting/a linter set up without prettier or whatever for a while so the linter can tell people exactly where they're going wrong with their formatting, and then after they have got used to it and are generally formatting correctly, introducing an automated code formatting tool. Means people actually know what the automated formatter thing does. 

Agree tho as well definitely shouldn't stop people from using them if they are using it already, although maybe just making sure they know why/what exactly it's doing could be a good idea.

**Comment by m4v15** [comment]
Sorry obviously did not read your whole comment properly/follow the links. So if linting get's introduced in week 5 I think maybe waiting until the second half of the course to introduce a code formatter. But tbh I don't feel massively strongly about it.

**Comment by ZooeyMiller** [comment]
@m4v15 that's a fair point. I feel like week 8 onwards should be people's chance to explore different technologies on their own, including things like style-guides, linting, formatting, dev environment etc. Maybe we could have something about automated formatting/prettier in [our tech choices guide](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/weeks-10-12/build-sprint/tech-choices.md).

Though I would note, if we introduce linters in week 5, people are likely to find the `fix on save` option and use it, which as long as we're okay with that, is fine.

**Comment by astroash** [comment]
> Though I would note, if we introduce linters in week 5, people are likely to find the fix on save option and use it, which as long as we're okay with that, is fine.

I agree. I don't think we need to be super strict, we're just advising what we think people will learn most from

**Comment by ZooeyMiller** [comment]
@astroash I am not 100% on all of the nuances of the differences between Prettier and Beautify, I think it's partly that prettier works for a smaller subset of file types, and that it's also more opinionated, where Beautify is more configurable. But honestly, I've not looked that much into it, I've just used prettier since week 9 and not looked back.

**Comment by ameliejyc** [comment]
The selling point of Prettier is that it removes cognitive load on trivial decisions like 'should this go on one line or two' or 'does this need to be indented' and allows students to focus on meatier problems. Students can also work faster because their code is way more consistent and readable.

I'm inclined to think these outcomes are more valuable for students than spending unnecessary time formatting. I'd be a fan of introducing Prettier with linters in week 5, or just replacing the suggestion of atom-beautify with Prettier in week 1.
