### ISSUE TITLE
advise Create React App in advised tech stack document

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/master-reference#760]
In our [tech-choices document](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/weeks-10-12/build-sprint/tech-choices.md) one of our advised stacks is "Express + PostgreSQL + React + Redux".

I think in the description for this we should advise the use of [create-react-app](https://github.com/facebookincubator/create-react-app). I think for people's first react apps having a pre-configured app makes a lot of sense. I feel that adding learning webpack into learning react/redux is too much to start with. Not to mention that the set up from CRA is going to generally be a lot better than someone just learning the build tools will be able to do, which is beneficial when it comes to working on grad projects as well.

Happy to PR this if it's deemed appropriate.

**Comment by finnhodgkin** [comment]
Couldn't agree more. It's so easy to get bogged down in unnecessary Webpack configuration.

**Comment by astroash** [comment]
Completely agree! I would also recommend students don't use redux for their first react project so that they have an awareness of what each is doing.

**Comment by ZooeyMiller** [comment]
@astroash I've toyed with this thought too, but I think it's perhaps a discussion for another issue.
