### ISSUE TITLE
advise React without Redux in advised tech stack document

### ISSUE THREAD

**Issue by astroash** [foundersandcoders/master-reference#762]
in #760 #761 it's being discussed to use `create-react-app` in our advised stack of "Express + PostgreSQL + React + Redux".

I think that we should advise students not to use redux for their first react project as:
- it adds an extra load of tech they need to learn before getting started
- it makes it difficult to mentally separate the two technologies when you've only seen and used them together
- it's very _FAC_ to master one tech at a time 

I'm curious to hear others opinions so that they can be reflected in #761

**Comment by eliascodes** [comment]
I think we can raise all the points you mention without outright advising against it. I've seen some student projects use both React+Redux quite successfully.

We can also de-emphasise Redux if you like, e.g "Express + PostgreSQL + React (+ Redux?)".

Ideally mentors and alumni should be in a position to judge whether it would be detrimental to a team to adopt Redux into their project.

**Comment by shiryz** [comment]
Agree with @eliascodes, I think learning Redux helps and would advise students to learn it even before React, would use '[ ]' instead of '( )' to hint that it's optional.
To reiterate we should help students with their tech choice instead of giving them a set of predefined ones.

**Comment by ZooeyMiller** [comment]
On a similar page to @eliascodes and @shiryz. I don't think we should explicitly advise against using Redux, but I do think we should explicitly bundle Redux in with React. Something like @eliascodes' suggestion seems sensible to me.
