### ISSUE TITLE
Week3 - making API requests in the browser

### ISSUE THREAD

**Issue by rebecacalvoquintero** [foundersandcoders/master-reference#766]
In this afternoon workshop, github went down: It  would have been useful to send around the JSON response in this situation

Important: **There should a simpler syntax solution which is refactored less --> the current one is quite complex**

**Comment by ZooeyMiller** [comment]
[this is the workshop being discussed for those unfamiliar with it](https://github.com/emilyb7/workshop-APIs)

**Comment by ZooeyMiller** [comment]
I'm unsure if there's much we can do if github goes down. I don't think we can have a mock response... 

When dealing with an API there's always going to be the potential for it to go down, and github is quite a reliable api with very little downtime. I'm unsure if we can realistically expect to account for the situation of it being down with this workshop, unless we just use a different API (where we could have the same problem/worry).
