### ISSUE TITLE
Documenting unused morning challenges/workshops

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/master-reference#775]
We have an assortment of morning challenges/workshops which are not currently used in the curriculum, some of them are documented in the fragments section of the coursebook, some of them are in separate repos. 

Rather than have some of the documentation in the fragments section, I think we should have a document inside of the fragments section which tracks all of the MCs/WSs that we have but aren't currently in the curriculum. 

This would mean that during curriculum planning students could see the workshops/morning challenges that already exist but are not used, such that they could decide if they want to use any of them, and course facilitators could easily see what material already exists, such that if the students are struggling with a topic they can throw in an extra workshop/morning challenge.

The action steps for this would be: 
+ take any workshops/morning challenges currently in the fragments section and create separate repos for them
+ take any workshops/morning challenges in the foundersandcoders organisation and change their title in accordance with the current guidelines
+ create a document in the fragments section which lists all of the content, with a brief description of each.

I'm happy to make these changes, but would like to make sure no one has a huge ideological dispute with it before I do it.

**Comment by shiryz** [comment]
@ZooeyMiller why not add the descriptions to [`resource-index`](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/resource-index.md)?

**Comment by ZooeyMiller** [comment]
@shiryz That would be the _perfect place_. I did not know it existed :flushed:
