### ISSUE TITLE
Introduce workshop on testing database queries in Week 6

### ISSUE THREAD

**Issue by azayneeva** [foundersandcoders/master-reference#776]
Currently week 6 research topics include testing databases. FAC11 found it impossible to find information on it, that's why we decided to introduce [database queries testing workshop](https://github.com/foundersandcoders/ws-database-testing) instead of this research topic.

This workshop is designed to be 1 hour long to be run before research afternoon, so the other topics can still take place.

**Comment by astroash** [comment]
It's worth noting that students need to be extremely confident with error first callbacks to complete this workshop as the tests are a nested inside db_build. This caught a number of people out in London.
