### ISSUE TITLE
MC to get students acquainted with array methods (esp reduce)

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/master-reference#779]
## Problem

Some students are not very comfortable with array methods (including reduce) by over mid-way through the course. (Anecdotal - source - seeing people using for loops, using forEach when they should be using map, etc).

## Solution

introduce a morning challenge which introduces some commonly used array methods, focusing on reduce.

-------------

I made this morning challenge, I tested it on @Jwhiles and @stevehopkinson, I think it could fit in well at some point during the course, or even as an optional extra for CFs to implement if the students seem to need it. I don't know when, or where, but if others see value in it I will transfer ownership to Founders and Coders, and document it in fragments as part of #775 

Oh, here's the link https://github.com/ZooeyMiller/mc-array-methods-reduce

**Comment by ZooeyMiller** [comment]
Similar to the challenge created by @eliascodes in #723

**Comment by Jwhiles** [comment]
hot

**Comment by m4v15** [comment]
this is great we should use this (I've raised an issue you may or may not want to ignore in your repo)

**Comment by shiryz** [comment]
Zooey I :heart: it.

**Comment by ZooeyMiller** [comment]
Workshop has been moved to the foundersandcoders organisation. 

Will close this issue when I make a PR to link it in https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/resource-index.md
