### ISSUE TITLE
Week 8 - Replace research afternoon with project technical spikes

### ISSUE THREAD

**Issue by astroash** [foundersandcoders/master-reference#784]
In London we've decided to replace week 8 research afternoons with specific project spikes. Teams will be asked to pick one of the following challenges:
- use promises
- use express middleware for session management

Day 2 afternoon will then be used to setup their express servers and research their challenge. On the beginning of Day 3 each group will present their findings as ⚡️ Lightening Talks ⚡️ 

This change has come about due to a new workshop being too advanced, so it is being moved to week 13 instead. Documenting here incase other campus CF's feel their week 8 mentors will be interested in doing the same.

**Comment by eliascodes** [comment]
This was only done in London this time around, and isn't being taken forward for next iteration.
