### ISSUE TITLE
mentor-assignment-list.md is out of date

### ISSUE THREAD

**Issue by astroash** [foundersandcoders/master-reference#786]
[mentor-assignment-list.md](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/mentor-assignment-list.md) is out of date. I'm unsure of what the process for updating this is, but it feels a little too late this cohort.

**Comment by eliascodes** [comment]
Not sure anyone actually ended up using this. Happy to be corrected. If not, don't mind getting rid of it.

**Comment by yvonne-liu** [comment]
Could add links to these:

https://github.com/foundersandcoders/nazareth-programme/tree/master/facn3/mentor-assignments
https://github.com/foundersandcoders/gaza-programme/tree/master/facg3/mentors-assignments
https://github.com/foundersandcoders/london-programme/blob/master/current-cohort/mentors.md

Related, should we start archiving information by cohort differently in `london-programme`?

**Comment by m4v15** [comment]
Yeah this was initially I think imagined as a master reference so london mentors could talk directly to Naz/Gaza mentors, but it wasn't really used at all and I think basically managed by the FC's so I see this doc as pretty unnecessary/unwieldy to use. @yvonne-liu's suggestion makes sense to me.
