### ISSUE TITLE
Document roles in terms of curriculum planning and MR maintainance

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/master-reference#792]
Might be useful for reference to have an MD file with:

- Current maintainers of master reference
- Current CF's in each campus
- List of week facilitators for each week (defaulting to MRM's)
- Students who are in the week working groups/mentoring each week

**Comment by astroash** [comment]
@m4v15 could this be an update/amalgamation to the doc mentioned here #786 ?

**Comment by m4v15** [comment]
Errr maybe I think that doc was more about helping co-ordinate during the delivery of the course, but yeah, this could probably be seen as a replacement for that.
