### ISSUE TITLE
WK8 Enhancements: London mentor suggestions

### ISSUE THREAD

**Issue by BartBucknill** [foundersandcoders/master-reference#795]
**front end js & back end rendering confusion**
FAC 12 London had some confusion over the options regarding making api calls from the front end for data and alternatively redirecting/serving a new page page and using server side rendering to change the view.
For future cohorts it would be good to provide:
* greater clarity on two ways of doing things with specific details (e.g. server side rendering probably using html forms on the front end vs front end xhr requests to get data which is subsequently rendered through dom manipulation).
* ideally some guidance regarding advantages / disadvantages / best practice should be provided.

**promises**
The project was introduced with two additional bonus challenges, either a) use promises, or b) use express middleware for session management. The groups were given Tuesday afternoon for technical spikes on their chosen bonus challenge. In practice most (all?) groups used promises, but several ended up nesting promises in a way that suggested that they had not fully grasped how to use them appropriately.
My personal view is that we should have a promises workshop, possibly wk8 Tuesday afternoon, to provide a proper, guided learning experience for promises.

**error handling best practice in express not clear**
The code-along/workshops introduce the idea of using express middleware for 404s and express error handling middleware (4 args!) for 500s. They do not address how other types of errors should be handled, and FAC12 raised questions about this (at least some of FAC11 also had confusion on this point). What should be in error handling middleware, and what (if any) should be in route handlers? Is there widely used middleware that can help with this?
Ideally someone should research best practice. This could probably then be incorporated into the express code along error handling exercise.

**Comment by astroash** [comment]
> front end js & back end rendering confusion

It's worth noting that _Templating and Serverside rendering_ is a research topic. This was not covered in London due to London running a technical spike afternoon instead https://github.com/foundersandcoders/master-reference/issues/784

**Comment by astroash** [comment]
> error handling best practice in express not clear

I feel that some of the issues experienced by fac12 could have been alleviated by them reading expresses [error handling documentation](https://expressjs.com/en/guide/error-handling.html). It could be useful to link to this in the [project.md](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-8/project.md)

**Comment by BartBucknill** [comment]
Always good to link to the docs; actually the problems I saw in London were mostly around the overall error handling pattern, not just how to define error handling middleware. The basic idea of handling errors in middleware (and how error handling middleware is defined) is covered in the code along. We even emphasised this point, and I felt like a lot of students took this on board.

Neither the docs linked to above nor the code along do much more than demonstrate handling a specific error type, and then catching anything else with a generic 500 error.

The confusion was about how to structure error handling for multiple error types as they occur across the app. Should the error handling middleware differentiate between different error types (perhaps custom error types thrown/passed to next in route handlers), and send back appropriate responses 😄  ? How about using a module to do this for us 😃  ? Or is it OK to handle errors directly in route handlers 😞 ?

It would be great if someone who uses express professionally could confirm what best practice is and FAC12 could extend the code along to illustrate it.
