### ISSUE TITLE
Add link to complaints form in code-of-conduct.md

### ISSUE THREAD

**Issue by astroash** [foundersandcoders/master-reference#796]
I think it would be useful to have a link to the [complaints form](https://github.com/foundersandcoders/london-membership/blob/master/complaints-policy.md) in the `code-of-conduct.md`. Currently the document mentions reaching out on gitter if there are issues.

This may have to wait until we have similar forms for other campuses, as currently the above link is just for London's campus.

**Comment by yvonne-liu** [comment]
@astroash 👍 ! On a related note, talked to @sofer about this in passing, but I think our current code of conduct is a due for an update.

**Comment by claireinez** [comment]
The complaints form is already linked in the CoC, at the [bottom of the file](https://github.com/foundersandcoders/master-reference/blame/master/code-of-conduct.md#L31). If this is not clear enough, I'm happy to discuss moving it up to the top of the file.

**Comment by astroash** [comment]
@claireinez so it does, I completely missed that. I think it would be worth moving it up to the "Need Help?" section. In here it mentions "reaching out on gitter" which is a bit of a red herring.

**Comment by claireinez** [comment]
I guess Gitter should still be recommended, esp for non-London campuses as they don't have complaints forms (that I'm aware of) but I think the text should also be updated to mention the course facilitator as they should be first port of call:

"Please reach out to us! Our contact details are on our website or you can find your course facilitator or @sofer on Gitter. If you wish to make a complaint in London, please use the [complaints form](https://github.com/foundersandcoders/london-membership/blob/master/complaints-policy.md). Don't stay silent!"

I'm obvs open to language changes.
