### ISSUE TITLE
Tech proposal template

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/master-reference#8]
See here: https://github.com/dwyl/technology-stack/issues/18

(add notes link)

(fill this in)

Needs to include
a. way to measure result!
b. capture in sgc

WE need to capture decision process!

**Comment by bradreeder** [comment]
@stevehopkinson proposed developing an architecture map for the start of the course to show people how key concepts relate (client, server, db, etc.) I feel this ties into this and could be a part of the same resource.
