### ISSUE TITLE
Personal user manuals 

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#800]
Perhaps we could encourage students to write [personal user manuals](https://qz.com/1046131/writing-a-user-manual-at-work-makes-teams-less-anxious-and-more-productive/) in Week 1.

The suggested sections are:
+ My style
+ What I value
+ What I don’t have patience for
+ How to best communicate with me
+ How to help me
+ What people misunderstand about me

Suggested by [Alison Coward](http://bracketcreative.co.uk/about/).

**Comment by sofer** [comment]
I also like the idea of adding some sort of [team role inventory](https://en.wikipedia.org/wiki/Team_Role_Inventories) to the user manuarl, perhaps using our own categories instead of Belbin's roles, and allowing people to self-identify, instead of doing a questionnaire.

**Comment by Gbaja** [comment]
I think this is a good idea. Might be best to introduce it after the first week though. My reason is because in day1/week1, people are still getting used to the space and might not be as open as they would be if they do it in week 2.

**Comment by sofer** [comment]
The other possibility is that we ask people to complete a user manual as part of the application process. This will have the advantage of giving us hints about the likely balance in a cohort when we select them. We can't do this for FAC13, but we could for FAC14.

**Comment by lucymk** [comment]
@sofer I like that idea - the only issue might be people answering in a way that they think will be desirable for the selection committee, rather than completely honestly.

**Comment by polyccon** [comment]
Although it sounds like a good idea I agree with Lucy. I wasn't there for the talk, but sounds like a tool for helping people work together when they already are, and also implies that you already know yourself well enough to answer those questions. The course experience rather makes you more aware of yourself (mostly because of all the intense pairing you hadn't done before) so I would introduce it in a later week. Of course nothing wrong with trying it out as part of application process with FAC14 and see if it's helpful and it can always be  updated and/or adjusted appropriately during the course.

**Comment by sofer** [comment]
Incidentally, for identifying personal strengths, I like the [VIA Survey](https://www.viacharacter.org/www/).

**Comment by shannonjensen** [comment]
I would also add something like "how I learn" (i.e. I'm a visual learner, i like to think through stuff before coding, i think to figure things out through experimentation, etc)

**Comment by sofer** [comment]
Re: Myers-Briggs: https://youtu.be/Q5pggDCnt5M

**Comment by matthewdking** [comment]
I loved this talk and thought this would be really interesting to implement for FAC13. I had a few ideas on how to implement this...

- create personal user manual on Friday Week 1 after completing the first project
- each student can iterate on this every week
- when new teams are created there is an allocated time ~15mins to go over user manuals with your teammates 

Hopefully this will improve how students are working together throughout the course. Any thoughts on this would great.

**Comment by shannonjensen** [comment]
I think the process @matthewdking laid out would be perfect. It's something that you update along the way and always share with teammates when teams switch around... Perhaps everyone keeps their own in a hackmd file or such and then sends links in group gitter chat for example.

**Comment by matthewdking** [comment]
@shannonjensen glad you think its a good idea! After speaking to @nogainbar about it, we thought it could work well with each manual as a card in a project board within the fac-13 organisation. Then cards could be moved around as teams change. Something like this...

![usermanuals](https://user-images.githubusercontent.com/25408167/36061069-5c0f5e7c-0e5d-11e8-84a9-b3db084cba74.gif)

**Comment by zurda** [comment]
I had no idea this was relatively new, and it makes me value the face we had it on our cohort even more. Personally speaking, it was an excellent tool for me. Updating it in as the weeks go by makes you learn a lot about yourself and the way you work in a team. 

I would be curious to know how it's working out for others and on other programs. I believe for FAC-16 @charlielafosse and @boi87 had the cohort fill these in on week 1 (if I'm not mistaken)

**Comment by charlielafosse** [comment]
correct @zurda . See #953 for how @boi87 and I structured Week 1 Day 1. Also see #958 - another issue on user manuals

**Comment by sofer** [comment]
@zurda I am loving your comments on old open issues. closing this now, though.
