### ISSUE TITLE
DOM Manipulation Basics link expired 

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/master-reference#810]
Looks like [Call Me Nick](https://callmenick.com/) is in the process of [moving some contents](https://callmenick.com/dev/) around on his site, so this is now unavailable for the precourse: 

[Call Me Nick - DOM Manipulation Basics](http://callmenick.com/post/basics-javascript-dom-manipulation) 

Does anyone have an alternative they think FAC13 could benefit from for the precourse? Please share!

**Comment by eliascodes** [comment]
I never read that resource so I don't know what exactly we need to replace, but a quick google gives the following that seem OK:

IMO MDN is typically the best resource for API docs but I dunno if the descriptions are super-beginner focussed:
https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction

Two more:
https://www.sitepoint.com/dom-manipulation-vanilla-javascript-no-jquery/
https://plainjs.com/javascript/

This one seems focussed on vanilla counterparts to common jQuery patterns:
https://blog.garstasio.com/you-dont-need-jquery/dom-manipulation/

None of these are exercises though...

**Comment by m4v15** [comment]
Yeah as far as I can remember it was very similar to a lot of the links @eliascodes has posted. I had a look at his site and I _think_ it was probably [this](https://callmenick.com/dev/jquery-functions-javascript-equivalents/) or something similar

**Comment by matjack1** [comment]
Hello, if you are interested you can see the original content in the [web archive capture](https://web.archive.org/web/20170427004409/http://callmenick.com/post/basics-javascript-dom-manipulation).

I would recommend this from MDN: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents which has an exercise.

Plus, I've found these two videos as a good basic introduction:
  - [The DOM: What's the Document Object Model?](https://www.freecodecamp.org/videos/the-dom-whats-the-document-object-model).
  - [Live coding introduction to the DOM](https://www.youtube.com/watch?v=eaLKqoB9Fu0) with JavaScript examples.

**Comment by VirtualDOMinic** [comment]
Just to add to the above, the original post by "Call Me Nick" can be seen via the internet archive:

https://web.archive.org/web/20170611185943/http://callmenick.com:80/post/basics-javascript-dom-manipulation

**Comment by zurda** [comment]
@eliascodes , @yvonne-liu , was this resolved? If so, can we close this?

**Comment by yvonne-liu** [comment]
@zurda Yes, thanks for the reminder.
