### ISSUE TITLE
Recommend syntax highlighting in style_guide.md

### ISSUE THREAD

**Issue by astroash** [foundersandcoders/master-reference#818]
It would be useful if we recommend that blocks of code in markdown are tagged with the correct language so that they have syntax highlighting

<img width="288" alt="screen shot 2018-01-23 at 16 46 43" src="https://user-images.githubusercontent.com/14337958/35288851-b92aa3a4-005d-11e8-9e50-eb1d711cfdf7.png">

**Comment by eliascodes** [comment]
Agree, PR welcome. Link: https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting
