### ISSUE TITLE
Accessibility resources - broken links

### ISSUE THREAD

**Issue by matjack1** [foundersandcoders/master-reference#846]
Hello,

there are a couple of broken/outdated links in the [accessibility section](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-1/resources.md#accessibility) of week-1 resources.

In particular:
- `Aria - Usage` is 404
- `videos` is linking to a page with many link, most of them are broken though, I don't think it's very useful now.

I've found this YouTube playlist from Google: https://www.youtube.com/watch?v=HtTyRajRuyY&index=30&list=PLNYkxOF6rcICWx0C9LVWWVqvHlYJyqw7g or this video in particular about screen readers: https://www.youtube.com/watch?v=5R-6WvAihms

**Comment by eliascodes** [comment]
The aria - usage link could be replaced by this: https://www.w3.org/TR/aria-in-html/

The a11y video series seems good, we can replace the "videos" link with a link to that.

**Comment by zurda** [comment]
I tried the links and they seem to work. Can someone else double check, and close if this was resolved?

**Comment by oliverjam** [comment]
Looks good to me
