### ISSUE TITLE
Testing resources - broken links

### ISSUE THREAD

**Issue by matjack1** [foundersandcoders/master-reference#847]
I've found these two broken links in the week-2 resources:
- pros and cons of TDD
- Benefits of testing as you go

If you really think they are worth you can swap the links with the archived versions:
- https://web.archive.org/web/20150826234753/http://codesolid.com/pros-and-cons-of-test-driven-development/
- https://web.archive.org/web/20150828031556/http://codesolid.com/in-praise-of-100-test-coverage-or-how-i-made-my-code-smell-bad-to-martin-fowler/

**Comment by m4v15** [comment]
Thank you! I'm not sure how necessary it is to have the _exact_ same links, but they should be replaced with something equally relevant if not.

**Comment by zurda** [comment]
I just tried the links in [week 2 resources](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-2/resources/README.md), and didn't find the broken ones. I assume this was resolved?

**Comment by oliverjam** [comment]
The two Codesolid ones appear to be broken—although the URL works it just goes to the homepage not an article.
