### ISSUE TITLE
Too much for week 2!!

### ISSUE THREAD

**Issue by IsraaMoqbel** [foundersandcoders/master-reference#866]
This is a high level project to do early!

**Comment by ibraghada** [comment]
@IsraaMoqbel Can you elaborate on this?

what were the points where you struggled or thought it was too much and can you think of ways we can tackle this issue? 

Let's also talk about this in the SGC and engage the rest of G4 @foundersandcoders/facg4

**Comment by zurda** [comment]
Is this an ongoing discussion or was it resolved?
