### ISSUE TITLE
Week 5 Project Requirements

### ISSUE THREAD

**Issue by tspeed90** [foundersandcoders/master-reference#871]
The requirements for the project in Week 5 state that teams need to "include server-side validation to protect your server from potentially malicious user input" which caused a bit of confusion for FAC13 because we hadn't really discussed this by Week 5. It might be that this was introduced in week 5 sometime in the past and wasn't removed from the requirements. FAC13 decided as a group to drop that requirement for our projects, should it maybe be removed from the master reference as a requirement entirely or should there be a workshop/research topic added onto week 5?

**Comment by njseeto** [comment]
Thanks for raising this Tammy 😊 
Another note I would add would include putting a little more emphasis on error handling and testing the server for a post request, I think both points were raised in the week 5 SGC 🙌
