### ISSUE TITLE
Week 5, Day 2 timetable 🗓

### ISSUE THREAD

**Issue by haydnba** [foundersandcoders/master-reference#889]
Day 2 has two slots for introducing research topics - assuming we don't need this? In Naz we are doing the Node Shell Workshop all morning until lunch and then we will introduce research in the afternoon slot...

![screen shot 2018-07-30 at 10 15 54](https://user-images.githubusercontent.com/22300973/43382831-c159a314-93e1-11e8-949a-4216fa16b769.png)

**Comment by eliascodes** [comment]
Yep, oversight, sorry.
