### ISSUE TITLE
Weeks 10-16: Self-selecting teams of two 

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#89]
Following on from discussions with @izaakrogan and @besarthoxhaj, with @nikhilaravi and with @markwilliamfirth, I would like to suggest that in the second half of the programme we shift from selecting teams of four to allowing teams to self-select and encouraging smaller team of as few as two.

Teams of four are good for building a cohesive classroom group and for providing strong peer-led support (see https://github.com/foundersandcoders/old-playbook/blob/master/teams.md). 

Teams of two have been found to be more productive in environments such at MIT and EF, where individuals generally all have a high degree of preparedness.

This suggestion is related to #88

**Comment by markwilliamfirth** [comment]
Personally I think pairs are far more effective (and pairs can always consult other pairs of individuals if they are stuck). Maybe introduce pairings and also "pairs of pairs" whereby 2 sets of pairs check in together maybe once or twice in the week to discuss their projects and learn from the other pair about what they're doing wrong/right.

**Comment by jsms90** [comment]
@markwilliamfirth 
> I think pairs are far more effective

Effective in terms of writing good code, solving problems, building something quickly, learning new concepts, building a cohesive classroom group or providing strong peer-led support? There's a lot to think about in terms of what we think is most important for students.

I agree with Dan, that groups of 4 are better for peer-led classroom learning. I also think that it encourages people to use git properly - it easy to slip into bad habits when the only other person that has to be across your code base is the person sitting next to you, writing the code with you. So I wouldn't want to see weeks 1-8 change from 4s to pairs (toooo much). But if weeks 10-16 are going to be more project based, and less about the whole group learning a new technology at the same time, then pairs might be better.

Despite what I said about weeks 1-8, it might help that the week 8 project is now going to be in pairs (adding oauth to the same project that they built in 4s during the previous week). We've specified that the code review should be done by the other pair from their group of 4 from week 7: https://github.com/foundersandcoders/master-reference/issues/34#issuecomment-274062083. But maybe we should get them to do this too:
> check in together maybe once or twice in the week to discuss their projects and learn from the other pair about what they're doing wrong/right

Anyway, week 8 might be a good transition into pairs, not 4s, during weeks 10-16 :+1: 

I certainly felt much more focused when I was in a pair with @Cleop for week 2 - ping-pong TDDing. But is it also be worth thinking about how pairing (as opposed to 4s) would affect the introduction of different team roles #21?

**Comment by markwilliamfirth** [comment]
To further define what I meant by more effective, from my personal experience I've tended to see that pairs communicate faster and more effectively than teams of four and are more productive together. That being said there are benefits to working in a four, such as learning how to communicate in larger teams and dividing responsibilities.

The answer is probably a combination of working in fours and in pairs and the transition period is perhaps a good suggestion to remedy this. I always found it strange that during the course everyone worked in teams of four and then as soon as "real work" started everyone worked in pairs.

**Comment by jsms90** [comment]
We have 4 teams of 2 & 1 team of 4 here.

My observations of the team of 4:
+ They've run into more complications than the teams of 2. This seems to be down to working on a larger project than ever before & learning how to manage the team at the same time.  
e.g. When I first arrived, they were wrangling with giant PRs.
+ They have had slightly more communication issues (often asking "so what are you working on"), so they're constantly wrangling with what workflow will be effective for them.
+ They've organically decided to start holding "meetings", which are gradually becoming shorter and turning more into stand ups

In terms of encouraging 2s or 4s next time, I think it should depend on what we want students to get out of the week. Any of the points above could be seen as good or bad, depending on which learning outcomes we want to focus on.

Or maybe we want to leave it up to students to organise themselves again.

Hopefully SGC from FACN1 & FAC10 will be illuminating.

**Comment by bradreeder** [comment]
Personally I'm in favour of the students self-organising themselves into teams for weeks 10-12. This time round we had one team of 2, two teams of 3, and two teams of 4. 

It evolved that way so each student got to work on the project of their preference. This wouldn't have been possible if we had enforced a limit. Like @jsms90 said, you simply have different lessons to learn in a larger team, it's not necessarily a bad thing.

(As long as the team isn't as large as 16. Can we promise never to do that again, pls? 😆 )

Working in pairs for graduate projects makes sense though. For the reasons described but also for the financial reason that's less people to divide pay between.

**Comment by jsms90** [comment]
@bradreeder I'm actually greatly in favour of them working in 4 person teams because of one of the learning outcomes of the week being Agile roles / processes / methodologies.

I don't believe you learn as much about the different roles involved when you're in a team of 2

**Comment by jsms90** [comment]
@sofer @bradreeder @des-des @ronanyeah @eliascodes
For the next cohorts, are we happy to agree on self-selection in terms of team size in weeks 10-16?

If so, we can put this in the documents that are getting created for the 2nd half of the course.

**Comment by des-des** [comment]
@jsms90 I am still unsure of this. I think that teams of 3 can be *bad*.

I think in the case where there are three strong students, it is fine, but in the case where one student is weaker than the other 2, it leads to bad cohesion.

We could leave it as self selection but with a *strong* recommendation that teams are an even size..?

**Comment by jsms90** [comment]
@des-des I agree that 3 is generally a bad idea

Self selection between 2 or 4? or self-selection + strong recommendation?

**Comment by sofer** [comment]
@jsms90 @des-des there have been several teams of 3 in recent weeks on FAC10. It might be worth getting feedback from those teams.

**Comment by zurda** [comment]
@sofer , I think it's worth chatting with FAC-16 about this one. Because they're a cohort of 15, they have a team of 3 each week. It would be extremely interesting to get their feedback about how this changes the work process: both advantages and disadvantages. For example, I noticed the team of 3 usually work all 3 in front of one computer, which happens less in teams of 4 (worth asking them, because I was only with them for 1 week).

**Comment by sofer** [comment]
@zurda you are right that FAC16 have had shown that teams of three can sometimes collaborate effectively.  I am closing this, as we have settled into teams of 4 (with the occasional exception) in recent cohorts, and I don't see this changing any time soon.
