### ISSUE TITLE
Precourse Material - Dual boot Linux: inadequate documentation

### ISSUE THREAD

**Issue by MissArray** [foundersandcoders/master-reference#897]
Having spent several hours of frustration trying unsuccessfully to install Linux Mint on a replacement laptop, some of which (hours of frustration) were shared by Michael (also FAC14), who kindly offered to help, I finally cracked it and discovered that the problem didn't lie in Windows, but in the guide to installing Linux alongside Windows. I'd strongly suggest that [this guide](https://askubuntu.com/questions/1031993/how-to-install-ubuntu-18-04-alongside-windows-10) is added to the instructions. Happy to help (if I can) anyone struggling with dual installation at the FAC15 party.

**Comment by m4v15** [comment]
Thanks @MissArray - our precourse material often gets forgotten about, and especially installing linux can be a nightmare. I will put in a PR.
