### ISSUE TITLE
Add Weeks 10-16

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#903]
Weeks 10-16 [as delivered in London](https://github.com/foundersandcoders/london-programme/tree/master/weeks-10-16) now feels pretty stable and would probably benefit from moving into the master reference.

**Comment by rebeccaradding** [comment]
I was wondering about this. Assigning @arrested-developer - thoughts?

**Comment by arrested-developer** [comment]
100% - I've been going off [weeks 10-12](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/weeks-10-12) in Master Reference. The duplication is confusing.

**Comment by arrested-developer** [comment]
It also needs to be generalised a bit - some of this is FAC14 specific, e.g. speakers

**Comment by zurda** [comment]
@arrested-developer , Is there another action item on this issue, or can it be closed? Happy to help, if I can!

**Comment by charlielafosse** [comment]
The second half of the course is now going to be 10-18, technically, so will need some small changes there to the schedule.

@sofer and I have also been working on rejigging Week-10 a little, there's a PR inbound at some point soon with proposed changes.

**Comment by charlielafosse** [comment]
We could probably close this? We'll still need to merge changes on the schedule for 10-16 into `london-programme` anyway, before we start thinking about merging those changes into master reference...
