### ISSUE TITLE
Add a testing LO to each week

### ISSUE THREAD

**Issue by arrested-developer** [foundersandcoders/master-reference#917]
It's very easy to think you should test *everything* in your codebase, especially if students are collecting coverage.

We should specify in the LOs what students will learn to test each week, and specify in the projects what kind of tests we expect to see.

This helps prevent students sinking too much time into testing things they're not adequately prepared to test (yet)

**Comment by arrested-developer** [comment]
(I'm happy to draft these if people are in agreement)

**Comment by eliascodes** [comment]
Agreed. I think some project/week descriptions attempt to do this but probs better to have it slightly more formalised.
