### ISSUE TITLE
Remove or archive "facilitation"

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/master-reference#927]
No longer in use: https://github.com/foundersandcoders/master-reference/tree/master/facilitation

**Comment by m4v15** [comment]
These still happen but minutes are no longer kept. Regardless I don't think the master reference is even the place for this if they were - more like HQ?

Happy to move into an archive or something if @sofer agrees.

**Comment by rebeccaradding** [comment]
This folder then: https://github.com/foundersandcoders/hq/tree/master/minutes/archive
