### ISSUE TITLE
Precourse survey - how to make iterative improvements

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#93]
We have S-G-Cs to improve the content and delivery of each week of the curriculum, but no real method of making sure that we are streamlining and improving the contents of the precourse (or pre-reqs, but that's a separate issue).

I suggest that we send out a survey to our new cohort members, shortly before week 1 begins, to try and ascertain whether the content is doing our students justice. This is particularly relevant as the number of applicants is increasing, awareness increases, and the time that people spend on pre-reqs increases. I think it would be all too easy for us to design a precourse that would have been relevant for us, but falls short for the next cohort.

Thoughts welcome. Particularly on how to present the questions in this survey.

**Comment by Cleop** [comment]
Only thought is - is it possible to know what you think of the pre course materials before the course has begun? You may have enjoyed the materials but that wouldn't be much good if they weren't relevant or didn't prepare you for actually taking the course... but you may only discover this when you arrive and suddenly find there's a gap in your knowledge.

**Comment by jsms90** [comment]
Yeah good point. I wondered about doing it after week 1. But hopefully the kind of thing you're talking about will come out in S-G-Cs during the first couple of weeks. Otherwise the same could be said of having retrospectives at the end of each week - we don't know how useful API week is in preparing you for node week, but you can still comment on what you thought of API week.

I was thinking more of questions that they are able to answer now:
+ which bits did you do - it might be that not everyone feels they have had the time to do everthing
+ any explanations that you found particularly helpful e.g. plugging gaps in knowledge, helping with something you were struggling with before (i've already good things about Nick's CSS additions)
+ anything you felt was too advanced? (E.g. callback hell in our case)
+ anything too easy or a waste of time? Anything you felt was covered during pre-reqs
+ thoughts on the volume of stuff that was asked of them - too much / too little

**Comment by jsms90** [comment]
@njsfield @Cleop @bradreeder 
Does anyone have any time to do this? I'm happy to, but I can't see myself managing it before next weekend :(

**Comment by jsms90** [comment]
Trying a different way: introduce FAC11 to giving feedback directly within the `master-reference` through raising issues on day 1 in the "github scavenger hunt"

**Comment by zurda** [comment]
Personally, for me, bringing these things up during SGC is really good, because it's documented, and students who go on to be mentors can read exactly what they thought of a certain week before mentoring that week. This was extremely helpful for me before I started mentoring. Just reading what we thought of that week, and the discussion we had. 

Having said that, I can see the benefits of this sort of survey and I'm happy to help. @jsms90 , were you thinking of a google form for this one (the last comment)? I'm happy to help if there's an action point here.

**Comment by astroash** [comment]
closing as no longer relevant. Feel free to reopen if this is not the case 🙂
