### ISSUE TITLE
Week 2: Change 'Event Loop Video'

### ISSUE THREAD

**Issue by zurda** [foundersandcoders/master-reference#956]
We'd like to suggest changes regarding `Event loop Video` which is currently scheduled on [Day-2 at 17:30](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-2/README.md). 

1. We suggest moving it earlier in the day, right after lunch or just before research 
2. We suggest swapping it with a video or presentation that are more explicitly about Callbacks

As discussed in the [mentor feedback session](https://github.com/foundersandcoders/master-reference/issues/933), we found that learning about the event loop before learning about callbacks meant that it was really difficult to understand. We should learn about callbacks prior to the event loop. Also, we think that having a half hour just about callbacks before the workshop the next day will help students with the traffic light callback challenge.

**Comment by sbinlondon** [comment]
I remember this being a point of discussion in our cohort too. It’s a good video, but honestly I think it’s almost wasted if we introduce it that early. I would vote to replace it woth something more specific and even more beginner friendly, and move the current video to later in the course. If we can’t find a resource, I am happy to work with some people to create one. I know @arrested-developer has a pretty snazzy GBBO metaphor for callbacks.

**Comment by martingaston** [comment]
I... really like that video :joy: 

I think it's a biiig watch at that particular part of the course, mind, and I think the mesh of the event loop _along with_ the brainbusting concept of Web APIs _along with_ what I imagine might be the first introduction of the call stack for most people (it certainly was for me) _along with_ the introduction of first-class functions can be a **lot** to take in. 

I think it can also be quite jarring as well as I think it's probably the closest the curriculum gets to a computer science lecture, and popping that at 17:30 is also a pretty big oof. Doesn't it also come after a research afternoon? Double oof.

However, the pros is that I think it's relatively concise and effective. It packs a bunch into those 30 minutes and I think it's a good springboard into those broader concepts. With the exception of casually dropping the concept of a shim I also think it positions it in a relatively nice, friendly tone. But I think there might be a bit of a disconnect from that video and any kind of insight about callbacks, and the FAC14 feedback was pretty much 'omg callbacks' as well :joy: 

I wonder if making space by taking, say, technical spikes out of the research afternoon and replacing it with first-class functions might put more eyes and brains onto the topic before/after the video and help prep for the infamous :traffic_light: challenge. I know it's kind of out of step with the testing theme but it kind of springboards off the back of the pure functions workshop earlier in the day.

**Comment by sbinlondon** [comment]
Casual shims indeed 😂 I like your suggestion @martingaston - that could be a good way of focusing on things that would make callbacks less "OMG"

**Comment by eliascodes** [comment]
@zurda 

> We suggest swapping it with a video or presentation that are more explicitly about Callbacks

Are you thinking of something like [intro-to-functions-slides](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-2/intro-to-functions-slides.md)? I think that could work, if the mentors are well enough prepared.

**Comment by zurda** [comment]
It's worth noting the issue summarising week 2 for FAC-16. As suggested in the comments, we added research topics which went well and seemed to reduce the confusion: https://github.com/foundersandcoders/master-reference/issues/933

**Comment by astroash** [comment]
@zurda are you still in favour of this proposal, or do you think the issue was solved with the updated research topics?

**Comment by zurda** [comment]
This was not an issue for fac16, perhaps as a result of the research topic change. I think this is resolved

**Comment by charlielafosse** [comment]
@zurda I agree! it seemed that the new research topic helped with the understanding of the video
