### ISSUE TITLE
Week 2: confusing TDD workshop links

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/master-reference#965]
It looks like the link to the "Tape" workshop on Week 2 day 1 was updated from the Dwyl "Learn Tape" repo back to the fizzbuzz workshop at some point.

https://github.com/foundersandcoders/master-reference/blame/master/coursebook/week-2/README.md#L21

This is fine, but the stretch goal still links to the last section of the Dwyl repo.

I think FAC16 ended up just working through the "Learn Tape" repo after the fizzbuzz one, so maybe it would be better just to schedule both (or change the stretch goal link to be the beginning of the "Learn Tape" readme)

**Comment by zurda** [comment]
This is definitely confusing. It's worth noting that for FAC-16 we went over the solution about a half hour before the scheduled time. We were able to show a quick example of coverage though.
The only issue I can see with scheduling both is that this morning already has two short intros. IMO having two workshops + 2 intros before 13:00 might make it a bit much for one morning (assuming you need a little breather between each section, and sometimes unexpected events like a non functioning chrome cast can "steal" valuable time). 
I'm leaning towards your second suggestion of changing the link to the beginning of learn-tape, but I would love to hear more suggestions/ feedback

**Comment by oliverjam** [comment]
Yeah I think just changing the link will help. This part of the testing intro still needs a bit of work I think. I'm not convinced the current intro really gets across the concept of testing that well. That's a problem for another issue though 😅

**Comment by zurda** [comment]
I'm closing this issue since the branch was merged (cc: @oliverjam)
