### ISSUE TITLE
Day 5 afternoons in coursebook

### ISSUE THREAD

**Issue by charlielafosse** [foundersandcoders/master-reference#968]
as @zurda and some of the FAC16 students pointed out, the schedule for Day 5 in the coursebook looks like so:

— LUNCH —

14:00-15:00 -Cohort Stop Go Continue (retrospective)

15:00-15:40 - Team retrospectives

15:40-17:00 - Presentations (20 mins per group)

17:00-18:00 - External Speaker or Alumni Project Presentation

--------------------------------

When in fact the way we've been structuring that afternoon in London is like this:

— LUNCH —

14:00-15:20 - Presentations (20 mins per group)

15:20-16:20 -Cohort Stop Go Continue (retrospective)

16:20-17:00 - Team retrospectives

17:00-18:00 - External Speaker or Alumni Project Presentation

--------------------------

What about for the other campuses @m4v15 @shiryz @ishak52 ? As far as I'm aware we've been structuring the afternoon like that for quite a while (but that afternoon hasn't ever been updated to mirror it)

**Comment by shiryz** [comment]
Been doing the same for Naz :sweat_smile:
presentations -> SGC -> retro -> speaker

**Comment by charlielafosse** [comment]
Closing because fixed by #972
