### ISSUE TITLE
Week 4 - stop recommending Request module

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/master-reference#978]
I was considering making an issue about this anyway, then I saw that the maintainer announced [Request's development is over](https://github.com/request/request/issues/3142) 2 days ago.

> The most valuable thing `request` can do for the JavaScript ecosystem is to go into maintenance mode and stop considering new features or major releases.

> The patterns at the core of request are out of date

Request is also enormous as it was built exclusively for Node, and has a totally different API to something like `fetch`, which frontend devs will eventually be more familiar with in the browser.

Obviously removing `request` would require revisiting our promises introduction, since whatever we replace it with would inevitably require understanding promises. However I think this is a good sign that promises are the default now, so the curriculum needs to be less scared of them.

If we don't want to teach promises at this point yet we could just stop recommending `request` and make the [request morning challenge](https://github.com/foundersandcoders/mc-request-module-workshop/) a module-agnostic way for students to implement their own wrapper around Node's `http`. They can then use that in their projects until they learn promises and can use `node-fetch` or something.

**Comment by starsuit** [comment]
This could probably be closed now as [this PR](https://github.com/foundersandcoders/mc-request-module-workshop/pull/8) removed teaching the Request module in Week5.
