### ISSUE TITLE
Schedule page in coursebook

### ISSUE THREAD

**Issue by lucymonie** [foundersandcoders/master-reference#98]
@bradreeder, should there be a schedule.md in each week folder in the coursebook? Or does this information go in the main README for the week?

**Comment by bradreeder** [comment]
@lucymonie it should go in the main readme.md for the week for now. Once all the weeks have finished their gitbooks I'll have a look over and tidy/edit. 

(sorry for delay in responding, working on the Anna Freud sprint!)
