### ISSUE TITLE
Checklist of things to think about & challenges after first 8 weeks

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#990]
Currently sitting in a [hackmd file](https://hackmd.io/UJxDTRNvT3y35yjozfqTUg). It probably makes sense for this checklist to be copied into master-reference and maintained here.

**Comment by charlielafosse** [comment]
Agree, it's an awesome checklist ( big up @m4v15 )

**Comment by charlielafosse** [comment]
I'm happy to make a PR for it if you want @m4v15

**Comment by m4v15** [comment]
Go for it!
